/** String lists for new-intake / flash offers. Keep this file free of the estate catalogue. */

export const NEW_INTAKE: { name: string; group: string }[] = [
  { name: "雋東邨", group: "東涌" },
  { name: "翔東邨", group: "東涌" },
  { name: "裕興苑", group: "東涌" },
  { name: "錦柏苑", group: "馬鞍山" },
  { name: "恆光街項目", group: "馬鞍山" },
  { name: "青福里項目", group: "屯門" },
  { name: "欣寶路項目", group: "屯門" },
  { name: "滿田邨", group: "屯門" },
  { name: "鴻鵠臺", group: "九龍" },
  { name: "柏傲莊III", group: "新界" },
  { name: "101 Kings Road", group: "港島" },
  { name: "Belgravia Place I", group: "九龍" },
  { name: "Blue Coast I & II", group: "港島" },
  { name: "Finnie", group: "港島" },
  { name: "Miami Quay II", group: "九龍" },
  { name: "One Central Place", group: "港島" },
  { name: "Spring Garden", group: "港島" },
  { name: "The Haddon", group: "九龍" },
  { name: "安樺苑", group: "九龍" },
  { name: "安麗苑", group: "九龍" },
  { name: "樂翹都匯", group: "新界" },
  { name: "樂嶺都匯", group: "新界" },
  { name: "盛緻苑", group: "九龍" },
  { name: "啟盈苑", group: "九龍" },
  { name: "朗天苑", group: "新界" },
  { name: "朗日峰", group: "新界" },
  { name: "朗天峰", group: "新界" },
  { name: "日出康城第12期", group: "新界" },
  { name: "古雋邨", group: "新界" },
  { name: "鳳凰嶺邨", group: "新界" },
  { name: "曉茵邨", group: "九龍" },
  { name: "世運道簡約公屋", group: "九龍" },
  { name: "柴灣常安街簡約公屋", group: "港島" },
  { name: "宏緻苑", group: "九龍" },
  { name: "彩石邨", group: "新界" },
  { name: "安楹苑", group: "九龍" },
  { name: "上然", group: "大埔" },
  { name: "富蝶邨", group: "大埔" },
  { name: "攸壆路簡約公屋", group: "新界" },
  { name: "彩興路簡約公屋", group: "九龍" },
  { name: "彩園路簡約公屋", group: "新界" },
  { name: "順安道簡約公屋", group: "九龍" },
  { name: "彩石里簡約公屋", group: "九龍" },
  { name: "青發街簡約公屋", group: "屯門" },
  { name: "Sierra Sea", group: "大埔" },
  { name: "黃金海灣", group: "屯門" },
  { name: "飛揚", group: "屯門" },
  { name: "凱和山", group: "屯門" },
  { name: "Double Coast", group: "九龍" },
  { name: "海盈山", group: "港島" },
  { name: "晉環", group: "港島" },
  { name: "揚海", group: "港島" },
  { name: "YOHO West", group: "新界" },
  { name: "NOVO LAND", group: "屯門" },
  { name: "傲華", group: "港島" },
  { name: "滙都", group: "新界" },
  { name: "維港雙鑽", group: "九龍" },
  { name: "天璽海", group: "九龍" },
  { name: "天璽天", group: "九龍" },
  { name: "啟德海灣", group: "九龍" },
  { name: "壹沐", group: "九龍" },
  { name: "應天", group: "港島" },
  { name: "璟南", group: "港島" },
  { name: "Beacon Peak", group: "九龍" },
  { name: "尚岸", group: "屯門" },
  { name: "維港灣畔", group: "九龍" },
  { name: "海德園", group: "港島" },
  { name: "業旺邨", group: "屯門" },
  { name: "顯發邨", group: "屯門" },
  { name: "邑庭居", group: "新界" },
  { name: "樂嶺軒", group: "新界" },
  { name: "樂嶺樓", group: "新界" },
  { name: "盛頤居", group: "新界" },
  { name: "Miami Quay I", group: "九龍" },
  { name: "首匯", group: "九龍" },
  { name: "首岸", group: "九龍" },
  { name: "高宏苑", group: "九龍" },
  { name: "清濤苑", group: "新界" },
  { name: "The Monet", group: "九龍" },
  { name: "博峯", group: "九龍" },
  { name: "漁映樓", group: "港島" },
  { name: "兆翠苑", group: "屯門" },
  { name: "啟悅苑", group: "九龍" },
  { name: "瑜一", group: "九龍" },
  { name: "安秀苑", group: "九龍" },
  { name: "安柏苑", group: "九龍" },
  { name: "冠山苑", group: "九龍" },
  { name: "昭明苑", group: "新界" },
  { name: "啟欣苑", group: "九龍" },
  { name: "驥華苑", group: "港島" },
  { name: "啟鑽苑", group: "九龍" },
  { name: "柏蔚森", group: "九龍" },
  { name: "尚逸", group: "港島" },
  { name: "泓璟", group: "九龍" },
  { name: "滶晨", group: "港島" },
  { name: "朗賢峯", group: "九龍" },
  { name: "峻譽渣甸山", group: "港島" },
  { name: "One Stanley", group: "港島" },
  { name: "Mount Pokfulam", group: "港島" },
  { name: "滿．意", group: "其他地區" },
  { name: "恒莆新苑", group: "新界" },
  { name: "路德會雙魚薈", group: "新界" },
  { name: "新田部屋", group: "新界" },
  { name: "路德會七星薈", group: "新界" },
  { name: "悅安居", group: "新界" },
  { name: "恒攸新苑", group: "新界" },
  { name: "流浮東寓", group: "新界" },
  { name: "善樓", group: "大埔" },
  { name: "樂善村", group: "大埔" },
  { name: "博愛昇平村", group: "其他地區" },
  { name: "光廈", group: "九龍" },
  { name: "華第", group: "新界" },
  { name: "吉喆", group: "港島" },
  { name: "瑜意", group: "九龍" },
  { name: "薈淳", group: "九龍" },
  { name: "THE BOUNDARY", group: "九龍" },
  { name: "名鑽", group: "九龍" },
  { name: "Upper Central", group: "港島" },
  { name: "One Wood Road", group: "港島" },
  { name: "Elize Park", group: "九龍" },
  { name: "恒珀", group: "九龍" },
  { name: "隆敍", group: "九龍" },
  { name: "澐璟", group: "九龍" },
  { name: "曉柏峰", group: "九龍" },
  { name: "凱柏峰", group: "新界" },
  { name: "連方", group: "九龍" },
  { name: "北都滙", group: "新界" },
  { name: "映居", group: "九龍" },
  { name: "柏瓏", group: "新界" },
  { name: "UNI Residence", group: "新界" },
  { name: "蔚藍東岸", group: "九龍" },
  { name: "天瀧", group: "九龍" },
  { name: "天御", group: "港島" },
  { name: "半山名滙", group: "港島" },
  { name: "幸薈", group: "九龍" },
  { name: "朗然", group: "九龍" },
  { name: "海璇", group: "港島" },
  { name: "朗譽", group: "九龍" },
  { name: "南首", group: "九龍" },
  { name: "海嵎", group: "港島" },
  { name: "雅盈峰", group: "港島" },
  { name: "堅尼地道33號", group: "港島" },
  { name: "太子壹號", group: "九龍" },
  { name: "Coasto", group: "港島" },
  { name: "高臨", group: "九龍" },
  { name: "泰峯", group: "九龍" },
  { name: "薈鳴", group: "九龍" },
];

export const NEW_INTAKE_NAMES = new Set(NEW_INTAKE.map((item) => item.name));

/** HKBN / HGC fibre offers for public / HOS new-move-in estates (blocks inherit the parent). */
export const HKBN_INTAKE_OFFER_ESTATES = [
  "盛緻苑",
  "樂嶺都匯",
  "樂翹都匯",
  "安麗苑",
  "安樺苑",
  "宏緻苑",
  "滿田邨",
  "古雋邨",
  "鳳凰嶺邨",
  "曉茵邨",
  "世運道簡約公屋",
  "柴灣常安街簡約公屋",
  "彩石邨",
  "安楹苑",
  "翔東邨",
  "裕興苑",
  "錦柏苑",
  "恆光街項目",
  "青福里項目",
  "欣寶路項目",
  "雋東邨",
  "鴻鵠臺",
  "啟盈苑",
  "朗天苑",
  "綠置居",
  "攸壆路簡約公屋",
  "彩興路簡約公屋",
  "彩園路簡約公屋",
  "順安道簡約公屋",
  "彩石里簡約公屋",
  "青發街簡約公屋",
  "漁映樓",
  "兆翠苑",
  "高宏苑",
  "清濤苑",
  "樂嶺軒",
  "樂嶺樓",
  "啟悅苑",
  "安秀苑",
  "安柏苑",
  "冠山苑",
  "昭明苑",
  "啟欣苑",
  "驥華苑",
  "啟鑽苑",
] as const;

/** Netvigator fibre for a subset of new-move-in estates (blocks inherit the parent). */
export const NETVIGATOR_INTAKE_OFFER_ESTATES = [
  "盛緻苑",
  "樂嶺都匯",
  "宏緻苑",
  "滿田邨",
  "鳳凰嶺邨",
  "曉茵邨",
  "世運道簡約公屋",
  "柴灣常安街簡約公屋",
  "綠置居",
  "彩石邨",
  "裕興苑",
  "錦柏苑",
  "欣寶路項目",
  "漁映樓",
  "兆翠苑",
  "高宏苑",
  "清濤苑",
  "啟悅苑",
  "安秀苑",
  "安柏苑",
  "啟欣苑",
  "啟鑽苑",
] as const;

/** Fibre coverage currently Netvigator-only; blocks inherit the parent. */
export const NETVIGATOR_ONLY_ESTATES = ["上然"] as const;

/** HKBN flash fibre for listed estates only. 白田邨 is excluded. */
export const HKBN_FLASH_OFFER_ESTATES = [
  "寶庭居",
  "賢庭居",
  "仁愛居",
  "樂翹樓",
  "錦暉苑",
  "長沙灣邨",
  "康東邨",
  "連翠邨",
  "洪福邨",
  "滿東邨",
  "銀灣邨",
  "常樂邨",
  "東匯邨",
  "寶田邨",
  "啟福居",
] as const;

/** HKBN flash fibre for listed LPR estates (public / HOS / private). */
export const HKBN_LPR_FLASH_ESTATES = [
  "安泰邨",
  "榮昌邨",
  "美盈苑",
  "宏富苑",
  "藍澄灣",
  "逸瓏園",
  "翠怡花園",
  "樂嘉中心",
  "逸意居",
  "帝景灣",
  "彩頤居",
] as const;

