import { HKBN_FLASH_OFFER_ESTATES, HKBN_INTAKE_OFFER_ESTATES, HKBN_LPR_FLASH_ESTATES, NETVIGATOR_INTAKE_OFFER_ESTATES, estateUnlocksPlan, isNetvigatorOnlyEstate } from "./estate-new-intake.ts";

export type Category = "broadband" | "mobile" | "home5g" | "business";
export type Housing = "public" | "hos" | "private" | "village";
export type Generation = "4g" | "5g";
export type SpeedMbps = 200 | 500 | 1000 | 2000 | 2500 | 5000 | 10000;

export type ProviderId =
  | "hkbn"
  | "netvigator"
  | "cmhk"
  | "hgc"
  | "smartone"
  | "three"
  | "csl"
  | "icable";

export type Provider = {
  id: ProviderId;
  name: string;
  nameEn: string;
  initial: string;
  tone: string;
};

export const PROVIDERS: Provider[] = [
  { id: "hkbn", name: "香港寬頻", nameEn: "HKBN", initial: "寬", tone: "bg-provider-hkbn" },
  { id: "netvigator", name: "網上行", nameEn: "Netvigator", initial: "網", tone: "bg-provider-netvigator" },
  { id: "cmhk", name: "中國移動香港", nameEn: "CMHK", initial: "移", tone: "bg-provider-cmhk" },
  { id: "hgc", name: "HGC 寬頻", nameEn: "HGC", initial: "H", tone: "bg-provider-hgc" },
  { id: "smartone", name: "數碼通", nameEn: "SmarTone", initial: "S", tone: "bg-provider-smartone" },
  { id: "three", name: "3香港", nameEn: "3HK", initial: "3", tone: "bg-provider-three" },
  { id: "csl", name: "csl.", nameEn: "csl.", initial: "C", tone: "bg-provider-csl" },
  { id: "icable", name: "有線寬頻", nameEn: "i-Cable", initial: "線", tone: "bg-provider-icable" },
];

export const PROVIDER_MAP = Object.fromEntries(PROVIDERS.map((p) => [p.id, p])) as Record<
  ProviderId,
  Provider
>;

export type Plan = {
  id: string;
  providerId: ProviderId;
  category: Category;
  name: string;
  monthlyFee: number;
  freeMonths: number;
  contractMonths: number;
  rebate?: number;
  speedMbps?: number;
  dataGb?: number;
  highSpeedGb?: number;
  fupNote?: string;
  voice?: string;
  roaming?: string;
  install: string;
  housing: Housing[] | "all";
  network: string;
  perks: string[];
  portInPerk?: string;
  prepaid?: string;
  limits?: string;
  hot?: boolean;
  latestOffer?: boolean;
  quotePick?: boolean;
  newIntakeOffer?: boolean;
  flashOffer?: boolean;
  onlyEstates?: string[];
  bestFor: string;
};

const LIMITS_HKBN_10G =
  "本計劃為自動續約。優惠適用於指定公屋、居屋及私人住宅，且該地址於登記前 120 日內未曾使用香港寬頻之寬頻服務。實際安裝費用及網絡覆蓋視乎個別大廈基礎設施而定。不適用於村屋。";
const LIMITS_HKBN_5G =
  "本計劃為自動續約。家居 5000M 光纖入屋現時主要由香港寬頻提供，適用於指定公屋、居屋及私人住宅。不適用於村屋。";
const LIMITS_HKBN_FTTH =
  "本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。適用於指定公屋、居屋及私人住宅。不適用於村屋。";
const LIMITS_HKBN_VILLAGE_27 =
  "僅適用於指定村屋地址。本計劃為 27 個月合約。可選擇延遲服務生效日（最長 365 日）。香港寬頻之公屋、居屋及私人樓宇計劃不適用於村屋地址。實際覆蓋須另行核對。";
const LIMITS_HKBN_VILLAGE_SELECT_24 =
  "僅適用於指定村屋地址。本計劃為 24 個月合約。可選擇延遲服務生效日（最長 365 日）。實際覆蓋須另行核對。";
const LIMITS_NETVIGATOR_FTTH =
  "可選擇先安裝後啟動服務（最長 365 日）。實際覆蓋視乎個別樓宇而定。";
const LIMITS_NETVIGATOR_INTAKE =
  "僅適用於指定新入伙屋苑。可選擇先安裝後啟動服務（最長 365 日）。實際覆蓋同安裝期以電訊商確認為準。";
const LIMITS_NETVIGATOR_10G =
  "家居 10000M 光纖入屋現時主要由香港寬頻及電訊盈科網上行提供，適用於公屋、居屋及私人住宅。首次安裝須繳付安裝費。實際覆蓋視乎個別樓宇基礎設施而定。";
const LIMITS_NETVIGATOR_VILLAGE_WAIVED =
  "適用於指定村屋及唐樓地址。豁免安裝費。實際覆蓋須核對門牌。網上行之公屋、居屋及私人樓宇計劃不適用於村屋或唐樓。";
const LIMITS_HGC_VILLAGE =
  "適用於村屋地址。馬灣或若干指定村落未必享有額外特別優惠，詳情請向當值銷售員查詢。不適用於公屋、居屋及私人樓宇。實際覆蓋須核對門牌。";
const LIMITS_ICABLE_FTTH_NO_VILLAGE = "適用於公屋、居屋及私人樓宇。不適用於村屋。";
const LIMITS_HKBN_FLASH = "僅適用於指定屋苑。須繳付安裝費。實際覆蓋同安裝期以電訊商確認為準。";
const LIMITS_HKBN_FLASH_2500 =
  "僅適用於指定屋苑。本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。實際覆蓋同安裝期以電訊商確認為準。";
const LIMITS_HKBN_FLASH_63 =
  "僅適用於指定屋苑。本計劃為自動續約。免 3 個月月費。實際覆蓋同安裝期以電訊商確認為準。";
const LIMITS_HOME5G_SPEED =
  "實際速度介乎 100M 至 1000M，視乎訊號覆蓋、裝置數量及現場環境而定。";
const LIMITS_CMHK_HOME5G =
  "實際速度介乎 100M 至 1000M，視乎訊號覆蓋、裝置數量及現場環境而定。本計劃為自動續約。P2P 及 Thunder 下載期間限速至 128kbps。";
const PERK_CMHK_HOME_ROUTER = "租借 Wi-Fi 7 路由器";
const PERK_CMHK_HOME_COOL = "7 日冷靜期（服務啟用後連續使用 7 日）";
const PERK_CMHK_HOME_DEPOSIT = "以信用卡自動轉賬可豁免按金 HK$1,500";
const PERK_NETVIGATOR_NOWTV =
  "Now TV 體驗組合或國際新聞組合（智能電視版）；可加 HK$38 升級機頂盒";
const PERK_NETVIGATOR_MOVE = "搬遷費津貼 HK$1,000";
const PERK_NETVIGATOR_RELO = "豁免搬遷費";
const PERK_NETVIGATOR_APPLIANCE = "可加購每月 HK$68 換購指定家電（須符合資格）";
const PERK_THREE_HOME_MOVE = "不鎖定地區，可隨時搬遷";
const PERK_THREE_HOME_COOL = "7 日冷靜期";
const PERK_THREE_HOME_VISIT = "專人上門測試訊號";
const PERK_THREE_TUNNEL = "豁免隧道費（原價每月 HK$28）";
const PERK_THREE_CN_NUM = "內地副號";
const PERK_THREE_SOCIAL =
  "任用社交組合 15 個應用程式（Facebook、Instagram、WhatsApp、LINE、WeChat、Signal、Zoom、YouTube、Netflix、Apple TV、myTV SUPER、Disney+、hmvod、Douyin 及 Teams；不包括下載）";
const VOICE_THREE_3000 = "本地 3,000 分鐘";
const FUP_THREE_128K = "其後 128kbps 無限任用";
const FUP_THREE_1M = "其後 1Mbps 無限任用";
const FUP_THREE_STOP = "用完即停，不設其後限速數據";
const PERK_THREE_CGA = "中國內地、香港、澳門三地共用";
const PERK_THREE_ADMIN = "每月行政費 HK$28";
const PERK_THREE_ADMIN_PORT = "轉台可豁免每月行政費 HK$28";
const PERK_SMARTONE_PORT = "攜號轉台本地數據雙倍";
const PERK_HKBN_PORT = "攜號轉台適用";
const PREPAID_HGC_300 = "須預繳 HK$300";
const PREPAID_HKBN_200 = "須預繳 HK$200，第 1 至第 4 個月每月從預繳費用中扣減月費 HK$50";
const PERK_HKBN_365 = "可選擇延遲服務生效日（最長 365 日）";
const PERK_HKBN_SAFE = "SAFE 網絡安全防護及防毒軟件 6 個月";
const LIMITS_HKBN_INTAKE =
  "僅適用於指定新入伙屋苑。本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。豁免安裝費。實際覆蓋同安裝期以電訊商確認為準。";
const PERK_HKBN_INTAKE_OTT_6 =
  "六選一：Disney+ 標準計劃 12 個月、Netflix 標準計劃 12 個月、HBO Max 標準計劃 12 個月、myTV GOLD 12 個月、愛奇藝黃金計劃 36 個月或 weTV 月費計劃 36 個月";
const PERK_HKBN_INTAKE_OTT_4_12 =
  "四選一：Disney+ 標準計劃 12 個月、Netflix 標準計劃 12 個月、HBO Max 標準計劃 12 個月或 myTV GOLD 12 個月";
const PERK_HKBN_INTAKE_OTT_4_24 =
  "四選一：Disney+ 標準計劃 24 個月、Netflix 標準計劃 24 個月、HBO Max 標準計劃 24 個月或 myTV GOLD 24 個月";
const PERK_HKBN_OTT_3_24 =
  "三選一：Disney+ 標準計劃 24 個月、Netflix 標準計劃 24 個月或 HBO Max 標準計劃 24 個月";
const VOICE_CMHK_UNLIMITED = "本地通話無限";
const VOICE_CMHK_3000 = "本地 3,000 分鐘";
const FUP_CMHK_1M = "其後限速無限上網（最高 1Mbps）";
const FUP_CMHK_5M = "其後限速無限上網（最高 5Mbps）";
const FUP_CMHK_2M = "其後無限（最高 2Mbps）";
const FUP_CMHK_128K = "其後無限（最高 128kbps）";
const FUP_CMHK_GBA = "大灣區其後無限（最高 384kbps）";
const LIMITS_CMHK_MOBILE = "實際月費、數據用量及轉台條款以電訊商確認為準。";
const LIMITS_CMHK_SLASH =
  "s/ash 每一實際使用人只可辦理一個計劃。實際月費、數據用量及轉台條款以電訊商確認為準。";
const LIMITS_CMHK_ELDER_60 = "須年滿 60 歲。實際月費、數據用量及申請資格以電訊商確認為準。";
const LIMITS_CMHK_ELDER_65 =
  "須年滿 65 歲並持綜援或長者生活津貼證明。實際月費、數據用量及申請資格以電訊商確認為準。";
const LIMITS_CMHK_YOUTH =
  "須符合 18 至 29 歲或教職員資格。實際月費、數據用量及申請資格以電訊商確認為準。";
const LIMITS_CMHK_3HK =
  "須核對現用 3香港客戶身份，只適用於由 3香港轉台之客戶。實際月費、數據用量及轉台條款以電訊商確認為準。";
const LIMITS_CMHK_TRIAL = "優惠代碼互斥；部分至 2026/09/30。實際月費、數據用量及轉台條款以電訊商確認為準。";
const LIMITS_CMHK_LOW = "限時計劃至 2026/09/30。實際月費、數據用量及轉台條款以電訊商確認為準。";
const LIMITS_CMHK_ULTIMATE36 = "轉台免 6 個月月費至 2026/09/30。實際月費、數據用量及轉台條款以電訊商確認為準。";
const LIMITS_CMHK_LIMITED = "限時計劃。實際月費、數據用量及轉台條款以電訊商確認為準。";
const PERK_CMHK_ADMIN_PORT = "轉台可豁免每月行政費 HK$18";
const PERK_CMHK_ADMIN_STUDENT = "轉台或學生上台可豁免每月行政費 HK$18";
const PERK_CMHK_ADMIN_WAIVED = "豁免每月行政費 HK$18";
const PERK_CMHK_ADMIN_LIMITED = "每月行政費 HK$18，限時可豁免（至 2026/09/30）";
const PERK_CMHK_ADMIN = "每月行政費 HK$18";
const PERK_CMHK_SOCIAL = "送任用社交及娛樂數據組合（原價 HK$38／月）";

export const PLANS: Plan[] = [
  {
    id: "hkbn-ftth-1000-36m-98",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 連 Wi-Fi 7 路由器（BE220・36 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: [
      "送 TP-Link Archer BE220 Wi-Fi 7 路由器",
      "首 36 個月額外免費 1000M 副線",
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    hot: true,
    quotePick: true,
    bestFor: "適合公屋、居屋或私人住宅，需要 1000M 光纖及路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-36m-108",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 連 Wi-Fi 7 路由器（36 個月）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: ["送 TP-Link Archer BE230 Wi-Fi 7 路由器（36 個月）", PERK_HKBN_365],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合需要 1000M 光纖及 Wi-Fi 7 路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-24m-109",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 家居寬頻（24 個月）",
    monthlyFee: 109,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: [
      "加購可享首 24 個月額外免費 1000M 副線",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合租住單位、接受 24 個月合約之住戶",
  },
  {
    id: "hkbn-ftth-1000-24m-199-mobile",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 四合一（Wi-Fi 7、OTT 及 5G 30GB｜24 個月）",
    monthlyFee: 199,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    voice: VOICE_CMHK_3000,
    roaming: "中國內地及澳門 4GB；通話 10 分鐘",
    prepaid: PREPAID_HKBN_200,
    perks: [
      "送 TP-Link Archer BE220 Wi-Fi 7 路由器（價值每月 HK$39；24 個月，合約後無須歸還）",
      PERK_HKBN_OTT_3_24,
      "24 個月 5G 流動通訊 30GB 本地數據，送任用 15 款熱門串流及社交數據（原價每月 HK$98）",
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    quotePick: true,
    latestOffer: true,
    bestFor: "適合公屋、居屋或私人住宅，需要 1000M 光纖、Wi-Fi 7、影視會籍及手機數據之住戶",
  },
  {
    id: "hkbn-ftth-1000-36m-128",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 連 Mesh Wi-Fi 7（36 個月）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: ["送 TP-Link Deco BE25 兩件裝 Wi-Fi 7 路由器（36 個月）", PERK_HKBN_365],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合較大單位、需要全屋 Mesh 覆蓋之住戶",
  },
  {
    id: "hkbn-ftth-1000-12m-168",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 基本月費計劃（12 個月）",
    monthlyFee: 168,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "須繳付安裝費 HK$680",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "四選一：TP-Link Archer BE220 路由器、愛奇藝黃金會員 12 個月、JOOX VIP 12 個月或 WeTV 12 個月",
      "SAFE 防毒軟件 6 個月",
      "可選擇延遲服務生效日（最長 365 日）",
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合接受 12 個月合約及自選禮遇之住戶",
  },
  {
    id: "hkbn-ftth-1000-12m-2800",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 一次過付款連影視／路由器（12 個月）",
    monthlyFee: 233,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "一次過支付 HK$2,800（平均每月約 HK$233.3）",
      "四選一：Disney+ 標準版 12 個月、Netflix 標準版 12 個月、愛奇藝鑽石會員 12 個月或 TP-Link Archer BE220 路由器",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合一次過付款、需要影視會籍或路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-12m-mytv",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 一次過付款連 myTV Gold（12 個月）",
    monthlyFee: 233,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "一次過支付 HK$2,800（平均每月約 HK$233.3）",
      "12 個月 myTV Gold 服務",
      "12 個月 myTV SUPER 基本版（智能電視版）",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合一次過付款、需要 myTV Gold 之住戶",
  },
  {
    id: "hkbn-ftth-2500-24m-149",
    providerId: "hkbn",
    category: "broadband",
    name: "2500M 光纖連家居電話（24 個月＋Wi-Fi 7）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["送指定 TP-Link BE230 Wi-Fi 7 路由器", "家居電話服務"],
    limits: LIMITS_HKBN_FTTH,
    hot: true,
    quotePick: true,
    bestFor: "適合需要 2500M 光纖及家居電話之住戶",
  },
  {
    id: "hkbn-ftth-2500-12m-218",
    providerId: "hkbn",
    category: "broadband",
    name: "2.5Gbps 高速上網連 Wi-Fi 7（12 個月）",
    monthlyFee: 218,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 2500,
    install: "首次需繳付 HK$680 安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "送指定 TP-Link Archer BE230 Wi-Fi 7 路由器（12 個月）",
      "SAFE 網絡安全防護及防毒軟件 6 個月",
      "可選擇延遲服務生效日（最長 365 日）",
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合需要 2500M 光纖及 Wi-Fi 7 路由器之住戶",
  },
  {
    id: "hkbn-ftth-5000",
    providerId: "hkbn",
    category: "broadband",
    name: "5000M 光纖連家居電話（24 個月）",
    monthlyFee: 249,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 5000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["家居電話服務", PERK_HKBN_SAFE, PERK_HKBN_365, "Money-Back 雙重保證（速度保證、低時延保證）"],
    limits: LIMITS_HKBN_5G,
    bestFor: "適合公屋、居屋或私人住宅，需要 5000M 光纖及家居電話之住戶",
  },
  {
    id: "hkbn-ftth-10000-entertainment",
    providerId: "hkbn",
    category: "broadband",
    name: "10000M 連 Wi-Fi 7 及娛樂組合（24 個月）",
    monthlyFee: 998,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "送 TP-Link Aginet EB810v Wi-Fi 7 路由器（24 個月）",
      "24 個月 Disney+ 標準計劃",
      "24 個月 Netflix 標準計劃",
      "24 個月 iQIYI 愛奇藝黃金會員",
      "myTV SUPER 解碼器",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
      "Money-Back 雙重保證（速度保證、低時延保證）",
    ],
    limits: LIMITS_HKBN_10G,
    quotePick: true,
    bestFor: "適合需要 10000M 光纖、Wi-Fi 7 及影視娛樂之住戶",
  },
  {
    id: "hkbn-ftth-10000-ge800",
    providerId: "hkbn",
    category: "broadband",
    name: "10000M 連遊戲路由器及娛樂組合（24 個月）",
    monthlyFee: 998,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: "須預繳 HK$3,600，第 1 至第 24 個月每月回贈 HK$150",
    perks: [
      "送 TP-Link Archer GE800 Wi-Fi 7 路由器（24 個月）",
      "12 個月 WTFast 電競玩家專用網絡",
      "24 個月 Disney+ 標準計劃",
      "24 個月 Netflix 標準計劃",
      "24 個月 iQIYI 愛奇藝黃金會員",
      "myTV SUPER 解碼器",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_10G,
    bestFor: "適合需要 10000M 光纖及電競路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-36m-99-intake",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 新入伙特選（36 個月＋OTT）",
    monthlyFee: 99,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: [
      "送 TP-Link Archer BE220 Wi-Fi 7 路由器",
      "首 36 個月額外免費 1000M 副線",
      PERK_HKBN_INTAKE_OTT_6,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_INTAKE,
    quotePick: true,
    newIntakeOffer: true,
    onlyEstates: [...HKBN_INTAKE_OFFER_ESTATES],
    bestFor: "適合指定新入伙屋苑、需要 1000M 光纖及影視會籍之住戶",
  },
  {
    id: "hkbn-ftth-2500-24m-149-intake",
    providerId: "hkbn",
    category: "broadband",
    name: "2500M 新入伙特選（24 個月＋OTT）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: [
      "送 TP-Link Archer BE230 Wi-Fi 7 路由器",
      "24 個月家居電話服務及 0030 IDD 每月 30 分鐘",
      PERK_HKBN_INTAKE_OTT_4_12,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_INTAKE,
    quotePick: true,
    newIntakeOffer: true,
    onlyEstates: [...HKBN_INTAKE_OFFER_ESTATES],
    bestFor: "適合指定新入伙屋苑、需要 2500M 光纖、家居電話及影視會籍之住戶",
  },
  {
    id: "hkbn-ftth-2500-36m-149-intake",
    providerId: "hkbn",
    category: "broadband",
    name: "2500M 新入伙特選（36 個月＋OTT）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: [
      "送 TP-Link Archer BE230 Wi-Fi 7 路由器",
      "36 個月家居電話服務及 0030 IDD 每月 30 分鐘",
      PERK_HKBN_INTAKE_OTT_4_24,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_INTAKE,
    quotePick: true,
    newIntakeOffer: true,
    onlyEstates: [...HKBN_INTAKE_OFFER_ESTATES],
    bestFor: "適合指定新入伙屋苑、接受 36 個月合約及影視會籍之住戶",
  },
  {
    id: "hkbn-ftth-2x1000-36m-75-intake",
    providerId: "hkbn",
    category: "broadband",
    name: "2×1000M 新入伙特選（36 個月）",
    monthlyFee: 75,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: [
      "免費升級至 2×1000M 光纖",
      "送 TP-Link Archer BE220 Wi-Fi 7 路由器",
      "12 個月 myTV SUPER 智能電視版",
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_INTAKE,
    quotePick: true,
    newIntakeOffer: true,
    onlyEstates: [...HKBN_INTAKE_OFFER_ESTATES],
    bestFor: "適合指定新入伙屋苑、需要雙線 1000M 光纖之住戶",
  },
  {
    id: "hkbn-village-200-27m",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 200M 光纖（27 個月）",
    monthlyFee: 298,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 200,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["第 13 至第 15 個月免費", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_27,
    bestFor: "適合指定村屋、需要 200M 光纖之住戶",
  },
  {
    id: "hkbn-village-500-27m",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 500M 光纖（27 個月）",
    monthlyFee: 328,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["第 13 至第 15 個月免費", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_27,
    bestFor: "適合指定村屋、需要 500M 光纖之住戶",
  },
  {
    id: "hkbn-village-1000-27m",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 1000M 光纖（27 個月）",
    monthlyFee: 378,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["第 13 至第 15 個月免費", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_27,
    hot: true,
    bestFor: "適合指定村屋、需要 1000M 光纖之住戶",
  },
  {
    id: "hkbn-village-2500-upgrade",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 2500M 升級旗艦（27 個月＋Wi-Fi 7）",
    monthlyFee: 424,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 2500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: [
      "原 1000M 計劃加購每月 HK$46（24 個月），合約期內自動升級至 2500M",
      "送 TP-Link BE230 Wi-Fi 7 路由器（合約後無須歸還）",
      "可選擇延遲服務生效日（最長 365 日）",
    ],
    limits: LIMITS_HKBN_VILLAGE_27,
    bestFor: "適合指定村屋、需要升級至 2500M 及 Wi-Fi 7 之住戶",
  },
  {
    id: "hkbn-village-2000-24m",
    providerId: "hkbn",
    category: "broadband",
    name: "特選村屋 2000M 光纖（24 個月）",
    monthlyFee: 229,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_SELECT_24,
    quotePick: true,
    bestFor: "適合特選村屋、需要 2000M 光纖之住戶",
  },
  {
    id: "hkbn-village-2000-be230",
    providerId: "hkbn",
    category: "broadband",
    name: "特選村屋 2000M 連 Wi-Fi 7（24 個月）",
    monthlyFee: 275,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 TP-Link BE230 Wi-Fi 7 路由器", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_SELECT_24,
    bestFor: "適合特選村屋、需要 2000M 光纖及 Wi-Fi 7 之住戶",
  },
  {
    id: "hkbn-village-2500-24m",
    providerId: "hkbn",
    category: "broadband",
    name: "特選村屋 2500M 光纖（24 個月）",
    monthlyFee: 258,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_SELECT_24,
    bestFor: "適合特選村屋、需要 2500M 光纖之住戶",
  },
  {
    id: "hgc-ftth-1000-public-36m",
    providerId: "hgc",
    category: "broadband",
    name: "公居屋轉台 1000M（36 個月）",
    monthlyFee: 75,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    hot: true,
    bestFor: "適合公屋或居屋轉台、需要 1000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-2000-hos-36m",
    providerId: "hgc",
    category: "broadband",
    name: "新居屋／簡約公屋 2000M（36 個月＋Wi-Fi 7）",
    monthlyFee: 75,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 7 路由器", "豁免搬遷費"],
    hot: true,
    quotePick: true,
    newIntakeOffer: true,
    onlyEstates: [...HKBN_INTAKE_OFFER_ESTATES],
    bestFor: "適合指定新入伙居屋或簡約公屋住戶",
  },
  {
    id: "hgc-ftth-1000-public-39m",
    providerId: "hgc",
    category: "broadband",
    name: "公居屋 1000M（39 個月＋Wi-Fi 6＋電話）",
    monthlyFee: 89,
    freeMonths: 0,
    contractMonths: 39,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送指定 TP-Link Wi-Fi 6 路由器", "家居電話服務", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要路由器及家居電話之住戶",
  },
  {
    id: "hgc-ftth-2000-public-36m",
    providerId: "hgc",
    category: "broadband",
    name: "公居屋 2000M（36 個月）",
    monthlyFee: 119,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要 2000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-1000-private-39m",
    providerId: "hgc",
    category: "broadband",
    name: "私人樓宇 1000M（39 個月＋Wi-Fi 6＋電話）",
    monthlyFee: 89,
    freeMonths: 0,
    contractMonths: 39,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 TP-Link Wi-Fi 6 路由器", "家居電話服務", "豁免搬遷費"],
    quotePick: true,
    bestFor: "適合私人屋苑轉台、需要 1000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-2000-private-36m",
    providerId: "hgc",
    category: "broadband",
    name: "私人樓宇 2000M（36 個月）",
    monthlyFee: 129,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合私人屋苑、需要 2000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-1000-student",
    providerId: "hgc",
    category: "broadband",
    name: "留學生 1000M（12 個月）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "安裝費 HK$180",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合留學生短約之住戶",
  },
  {
    id: "hgc-village-1g-phone-24m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 1G 連電話（24 個月）",
    monthlyFee: 319,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "家居／寬頻電話服務",
      "24 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 1G 光纖及電話之住戶",
  },
  {
    id: "hgc-village-1g-router-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 1G 連路由器＋電話（30 個月）",
    monthlyFee: 329,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 TP-Link EX141 路由器",
      "家居／寬頻電話服務",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要路由器之住戶",
  },
  {
    id: "hgc-village-2g-24m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 純寬頻（24 個月）",
    monthlyFee: 329,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: ["24 個月 100 分鐘 hgc on air Wi-Fi", "1GB 電郵儲存量", "豁免搬遷費"],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 2G 光纖之住戶",
  },
  {
    id: "hgc-village-2g-tv-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 連電視娛樂（30 個月）",
    monthlyFee: 329,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 24 個月 myTV SUPER 組合（基本、TVB 外購節目、精選基本、跨屏幕同時睇）",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要影視娛樂之住戶",
  },
  {
    id: "hgc-village-2g-wifi6-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 連 Wi-Fi 6＋電話（30 個月）",
    monthlyFee: 349,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 TP-Link Wi-Fi 6 路由器",
      "家居／寬頻電話服務",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 Wi-Fi 6 之住戶",
  },
  {
    id: "hgc-village-2g-wifi7-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 連 Wi-Fi 7＋電話（30 個月）",
    monthlyFee: 359,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 TP-Link Wi-Fi 7 旗艦路由器",
      "家居／寬頻電話服務",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 Wi-Fi 7 之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月＋家居電話）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE, "可加 HK$10 選配 Linksys EA9350 Wi-Fi 6 路由器"],
    limits: LIMITS_NETVIGATOR_FTTH,
    hot: true,
    quotePick: true,
    bestFor: "適合私人樓宇、需要 1000M 光纖及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m-198",
    providerId: "netvigator",
    category: "broadband",
    name: "指定私人樓宇1000M光纖優惠",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: [PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE, "新客戶可加每月 HK$98 升級 2500M"],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、可升級 2500M 之住戶",
  },
  {
    id: "netvigator-ftth-1000-specified-24m-198",
    providerId: "netvigator",
    category: "broadband",
    name: "指定私人樓宇1000M光纖優惠",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: [PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE, "新客戶可加每月 HK$98 升級 2500M"],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、可升級 2500M 之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-24m",
    providerId: "netvigator",
    category: "broadband",
    name: "獨家私人樓宇 1000M 光纖＋Wi-Fi 6 路由器＋家居電話＋手提電話服務",
    monthlyFee: 186,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 6 路由器", "家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、需要 Wi-Fi 6 及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-1000-exclusive-36m-186",
    providerId: "netvigator",
    category: "broadband",
    name: "獨家私人樓宇 1000M 光纖＋Wi-Fi 6 路由器＋家居電話＋手提電話服務",
    monthlyFee: 186,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 6 路由器", "家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、需要 Wi-Fi 6 及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-2500-private-24m",
    providerId: "netvigator",
    category: "broadband",
    name: "獨家私人樓宇 2500M 光纖＋Wi-Fi 7 路由器＋家居電話＋手提電話服務",
    monthlyFee: 244,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 7 路由器", "家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: `${LIMITS_NETVIGATOR_FTTH}僅適用於指定獨家私人樓宇。`,
    bestFor: "適合指定獨家私人樓宇、需要 2500M 光纖及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-2500-exclusive-36m-244",
    providerId: "netvigator",
    category: "broadband",
    name: "獨家私人樓宇 2500M 光纖＋Wi-Fi 7 路由器＋家居電話＋手提電話服務",
    monthlyFee: 244,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 7 路由器", "家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: `${LIMITS_NETVIGATOR_FTTH}僅適用於指定獨家私人樓宇。`,
    bestFor: "適合指定獨家私人樓宇、需要 2500M 光纖及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-1000-public-36m-98",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 1000M 光纖（36 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: [PERK_NETVIGATOR_MOVE, "家居固網電話", PERK_NETVIGATOR_NOWTV],
    limits: LIMITS_NETVIGATOR_FTTH,
    quotePick: true,
    bestFor: "適合公屋或居屋、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-36m-78-intake",
    providerId: "netvigator",
    category: "broadband",
    name: "1000M 新入伙特選（36 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: [
      "包 Linksys MX4050 Wi-Fi 6 路由器",
      PERK_NETVIGATOR_NOWTV,
      "可選擇先安裝後啟動服務（最長 365 日）",
    ],
    limits: LIMITS_NETVIGATOR_INTAKE,
    quotePick: true,
    newIntakeOffer: true,
    onlyEstates: [...NETVIGATOR_INTAKE_OFFER_ESTATES],
    bestFor: "適合指定新入伙屋苑、需要 1000M 光纖及 Wi-Fi 6 路由器之住戶",
  },
  {
    id: "netvigator-ftth-1000-public-36m-108",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 1000M 光纖（36 個月＋路由器）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["包 Linksys EA9350 Wi-Fi 6 路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    hot: true,
    bestFor: "適合公屋或居屋、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-public-36m-128",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 1000M 光纖（36 個月＋Wi-Fi 6）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["12 個月 Disney+", "包 Linksys EA9350 Wi-Fi 6 路由器", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_NOWTV],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合公屋或居屋、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-2500-public-36m-158",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 2500M 光纖（36 個月＋Wi-Fi 7）",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["12 個月 Disney+", "包 Wi-Fi 7 路由器", "家居固網電話", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_NOWTV],
    limits: LIMITS_NETVIGATOR_FTTH,
    quotePick: true,
    bestFor: "適合公屋或居屋、需要 2500M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m-118",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月＋路由器）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["包 Linksys EA9350 Wi-Fi 6 路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    bestFor: "適合私人屋苑、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m-128",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月＋Wi-Fi 6）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["12 個月 Disney+", "包 Linksys EA9350 Wi-Fi 6 路由器", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_NOWTV],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-2500-private-36m-176",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 2500M 光纖（36 個月＋Wi-Fi 7）",
    monthlyFee: 178,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["12 個月 Disney+", "包 Wi-Fi 7 二合一路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    quotePick: true,
    bestFor: "適合私人屋苑、需要 2500M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-village-24m",
    providerId: "netvigator",
    category: "broadband",
    name: "村屋 1000M 光纖計劃（24 個月）",
    monthlyFee: 278,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 Now TV 頻道", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_APPLIANCE],
    limits: LIMITS_NETVIGATOR_VILLAGE_WAIVED,
    bestFor: "適合村屋、需要 1000M 光纖及 24 個月合約之住戶",
  },
  {
    id: "netvigator-ftth-1000-village-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "村屋 1000M 光纖計劃（36 個月）",
    monthlyFee: 278,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 Now TV 頻道", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_APPLIANCE],
    limits: LIMITS_NETVIGATOR_VILLAGE_WAIVED,
    bestFor: "適合村屋、需要 1000M 光纖及 36 個月合約之住戶",
  },
  {
    id: "netvigator-ftth-2500-village-24m",
    providerId: "netvigator",
    category: "broadband",
    name: "村屋 2500M 光纖計劃（24 個月）",
    monthlyFee: 376,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 Now TV 頻道", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_APPLIANCE],
    limits: LIMITS_NETVIGATOR_VILLAGE_WAIVED,
    bestFor: "適合村屋、需要 2500M 光纖及 24 個月合約之住戶",
  },
  {
    id: "netvigator-ftth-2500-village-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "村屋 2500M 光纖計劃（36 個月）",
    monthlyFee: 376,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 Now TV 頻道", PERK_NETVIGATOR_MOVE, PERK_NETVIGATOR_APPLIANCE],
    limits: LIMITS_NETVIGATOR_VILLAGE_WAIVED,
    bestFor: "適合村屋、需要 2500M 光纖及 36 個月合約之住戶",
  },
  {
    id: "netvigator-ftth-10000",
    providerId: "netvigator",
    category: "broadband",
    name: "10000M 光纖入屋（24 個月）",
    monthlyFee: 998,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "首次安裝須繳付 HK$480",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [],
    limits: LIMITS_NETVIGATOR_10G,
    bestFor: "適合公屋、居屋或私人住宅，需要 10000M 光纖之住戶",
  },
  {
    id: "icable-ftth-200-36m",
    providerId: "icable",
    category: "broadband",
    name: "200M 光纖（36 個月）",
    monthlyFee: 68,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 200,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    hot: true,
    bestFor: "適合需要入門光纖之住戶",
  },
  {
    id: "icable-ftth-1000-48m-58",
    providerId: "icable",
    category: "broadband",
    name: "1000M 光纖入屋（48 個月）",
    monthlyFee: 58,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    limits: LIMITS_ICABLE_FTTH_NO_VILLAGE,
    hot: true,
    latestOffer: true,
    quotePick: true,
    bestFor: "適合公屋、居屋或私人樓宇、需要 1000M 光纖之住戶",
  },
  {
    id: "icable-ftth-1000-private-36m",
    providerId: "icable",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合私人樓宇、需要 1000M 光纖之住戶",
  },
  {
    id: "icable-ftth-1000-public-48m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 1000M 光纖（48 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link EX141 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要 1000M 光纖之住戶",
  },
  {
    id: "icable-ftth-1000-public-36m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 1000M 光纖（36 個月）",
    monthlyFee: 93,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link EX141 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、接受 36 個月合約之住戶",
  },
  {
    id: "icable-ftth-2000-private-36m",
    providerId: "icable",
    category: "broadband",
    name: "私人樓宇 2000M 光纖（36 個月）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合私人樓宇、需要 2000M 光纖之住戶",
  },
  {
    id: "icable-ftth-2000-public-36m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 2000M 光纖（36 個月）",
    monthlyFee: 129,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link AX55 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要 2000M 光纖之住戶",
  },
  {
    id: "icable-ftth-2000-public-24m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 2000M 光纖（24 個月）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link AX55 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、接受較短合約之住戶",
  },
  {
    id: "cmhk-ftth-1000",
    providerId: "cmhk",
    category: "broadband",
    name: "1000M 光纖入屋（36 個月）",
    monthlyFee: 98,
    freeMonths: 3,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["首 3 個月免月費"],
    bestFor: "適合公屋、居屋或私人住宅之入門 1000M 住戶",
  },
  {
    id: "cmhk-ftth-2500",
    providerId: "cmhk",
    category: "broadband",
    name: "1000M 光纖入屋（36 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["豁免安裝費"],
    bestFor: "適合公屋、居屋或私人住宅之 1000M 住戶",
  },
  {
    id: "hkbn-ftth-1000-24m-0-flash",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 家居寬頻計劃（24 個月）",
    monthlyFee: 0,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "須繳付 HK$780 安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["指定屋苑專享"],
    limits: LIMITS_HKBN_FLASH,
    quotePick: true,
    flashOffer: true,
    onlyEstates: [...HKBN_FLASH_OFFER_ESTATES],
    bestFor: "適合指定屋苑、月費 $0 之 1000M 住戶",
  },
  {
    id: "hkbn-ftth-2500-36m-148-flash",
    providerId: "hkbn",
    category: "broadband",
    name: "2500M GigaFast 寬頻（36 個月）",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: [
      "送 TP-Link Archer BE230 Wi-Fi 7 路由器（36 個月）",
      "送 HK$1,000 惠康超級市場及 Market Place 現金券（$50 × 20）",
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FLASH_2500,
    quotePick: true,
    flashOffer: true,
    onlyEstates: [...HKBN_FLASH_OFFER_ESTATES, ...HKBN_LPR_FLASH_ESTATES],
    bestFor: "適合指定屋苑、需要 2500M 光纖及路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-36m-63-flash",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 家居寬頻計劃（36 個月）",
    monthlyFee: 63,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: ["免 3 個月月費", PERK_HKBN_SAFE],
    limits: LIMITS_HKBN_FLASH_63,
    quotePick: true,
    flashOffer: true,
    onlyEstates: [...HKBN_LPR_FLASH_ESTATES],
    bestFor: "適合指定屋苑、需要 1000M 光纖及免 3 個月月費之住戶",
  },
  {
    id: "smartone-ftth-1000",
    providerId: "smartone",
    category: "broadband",
    name: "1000M 家居寬頻（36 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [],
    bestFor: "適合公屋、居屋或私人住宅、需要 1000M 光纖之住戶",
  },
  {
    id: "three-home5g-a-118",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 300GB（30 個月）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    highSpeedGb: 300,
    fupNote: "其後提供 5G 任用數據",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免租／買機優惠", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要 30 個月合約及 300GB 高速數據之住戶",
  },
  {
    id: "three-home5g-b-158",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 真無限（30 個月）",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    fupNote: "5G 真無限",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免租／買機優惠", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要 30 個月合約及 5G 真無限之住戶",
  },
  {
    id: "three-home5g-c-190",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 7 真無限（30 個月）",
    monthlyFee: 190,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    fupNote: "5G 真無限",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: ["免租／買機優惠", "送指定 Wi-Fi 7 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要 30 個月合約及 Wi-Fi 7 真無限之住戶",
  },
  {
    id: "three-home5g-w6",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 300GB（48 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 300,
    fupNote: "其後提供 5G 任用數據",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免還機", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    hot: true,
    bestFor: "適合需要較長合約、免還機及 300GB 高速數據之住戶",
  },
  {
    id: "three-home5g-e-108",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 500GB（48 個月）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後提供 5G 任用數據",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免還機", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要較長合約、免還機及 500GB 高速數據之住戶",
  },
  {
    id: "three-home5g-w7",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 7 真無限（48 個月）",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    fupNote: "5G 真無限",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: ["免還機", "送指定 Wi-Fi 7 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要較長合約、免還機及 Wi-Fi 7 真無限之住戶",
  },
  {
    id: "smartone-home5g-w6",
    providerId: "smartone",
    category: "home5g",
    name: "5G 家居寬頻 Wi-Fi 6",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "免拉線，隨插即用",
    housing: "all",
    network: "5G 無線",
    perks: ["送指定 5G 路由器"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要即插即用之住戶",
  },
  {
    id: "cmhk-home5g-350-48-88",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 350GB（48 個月，租借 Wi-Fi 7）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 350,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    hot: true,
    bestFor: "適合需要較長合約及 350GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-350-30-118",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 350GB（30 個月，租借 Wi-Fi 7）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    highSpeedGb: 350,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 30 個月合約及 350GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-w7",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 350GB（24 個月，租借 Wi-Fi 7）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    highSpeedGb: 350,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 24 個月合約及 350GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-500-48-118",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 500GB（48 個月，租借 Wi-Fi 7）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要較長合約及 500GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-500-30-148",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 500GB（30 個月，租借 Wi-Fi 7）",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 30 個月合約及 500GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-500-24-178",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 500GB（24 個月，租借 Wi-Fi 7）",
    monthlyFee: 178,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，免拉線，隨插即用",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 24 個月合約及 500GB 高速數據之住戶",
  },
  {
    id: "csl-home5g-wifi6",
    providerId: "csl",
    category: "home5g",
    name: "5G 家居寬頻包 Wi-Fi 6 路由器",
    monthlyFee: 108,
    freeMonths: 1,
    contractMonths: 36,
    speedMbps: 1000,
    install: "免拉線，隨插即用",
    housing: "all",
    network: "5G 無線",
    perks: ["豁免第一個月月費", "包指定 Wi-Fi 6 路由器", "14 日冷靜期", "可同時申請 csl 流動服務"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合現有 csl 或網上行客戶，需要 Wi-Fi 6 路由器之住戶",
  },
  {
    id: "csl-home5g",
    providerId: "csl",
    category: "home5g",
    name: "5G 家居寬頻包 Wi-Fi 7 路由器",
    monthlyFee: 138,
    freeMonths: 1,
    contractMonths: 36,
    speedMbps: 1000,
    install: "免拉線，隨插即用",
    housing: "all",
    network: "5G 無線",
    perks: ["豁免第一個月月費", "包指定 Wi-Fi 7 路由器", "14 日冷靜期", "可同時申請 csl 流動服務"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合現有 csl 或網上行客戶，需要 Wi-Fi 7 路由器之住戶",
  },
  {
    id: "hkbn-home5g",
    providerId: "hkbn",
    category: "home5g",
    name: "5G 家居寬頻連路由器",
    monthlyFee: 168,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    highSpeedGb: 300,
    fupNote: "其後無限任用，惟降低網絡優先權",
    install: "免拉線，隨插即用，路由器隨計劃提供",
    housing: "all",
    network: "5G 無線",
    perks: ["計劃包含指定路由器", "7 日免費試用"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合香港寬頻客戶加設無線後備線路",
  },
  {
    id: "three-45g-10-58",
    providerId: "three",
    category: "mobile",
    name: "4.5G 10GB 入門（36 個月）",
    monthlyFee: 58,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_THREE_128K,
    voice: VOICE_THREE_3000,
    roaming: "大灣區 2GB",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["首 10GB 數據全速", "2GB 大灣區數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合以即時通訊為主、較少串流之用戶",
  },
  {
    id: "three-5g-22-78",
    providerId: "three",
    category: "mobile",
    name: "5G 22GB Plan B（30 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 22,
    highSpeedGb: 22,
    fupNote: FUP_THREE_STOP,
    voice: VOICE_THREE_3000,
    roaming: "大灣區 2GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["22GB 5G 本地數據", "2GB 大灣區數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合輕用量、不需要其後限速數據之用戶",
  },
  {
    id: "three-5g-33-98",
    providerId: "three",
    category: "mobile",
    name: "5G 33GB Plan C（28 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 28,
    dataGb: 33,
    highSpeedGb: 33,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "內地及澳門 4GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["4GB 內地及澳門數據", PERK_THREE_SOCIAL, PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    hot: true,
    bestFor: "適合中等數據用量，以及使用即時通訊與串流應用之用戶",
  },
  {
    id: "three-45g-unl-116",
    providerId: "three",
    category: "mobile",
    name: "4.5G 全速無限（24 個月）",
    monthlyFee: 116,
    freeMonths: 0,
    contractMonths: 24,
    voice: VOICE_THREE_3000,
    roaming: "內地及澳門 10GB",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["本地數據全速無限任用", "10GB 內地及澳門數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    hot: true,
    bestFor: "適合本地串流用量高、需要全速無限數據之用戶",
  },
  {
    id: "three-5g-cga-10-116",
    providerId: "three",
    category: "mobile",
    name: "5G 三地共用 10GB（24 個月）",
    monthlyFee: 116,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "10GB 中港澳三地共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [PERK_THREE_CGA, PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合間中往返中港澳之用戶",
  },
  {
    id: "three-5g-cga-20-128",
    providerId: "three",
    category: "mobile",
    name: "5G 三地共用 20GB（24 個月）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 20,
    highSpeedGb: 20,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "20GB 中港澳三地共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [PERK_THREE_CGA, PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合經常往返中港澳之用戶",
  },
  {
    id: "three-5g-cga-30-138",
    providerId: "three",
    category: "mobile",
    name: "5G 三地共用 30GB（24 個月）",
    monthlyFee: 138,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "30GB 中港澳三地共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [PERK_THREE_CGA, PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合較高三地數據用量之用戶",
  },
  {
    id: "three-5g-105-148",
    providerId: "three",
    category: "mobile",
    name: "5G 105GB Plan D（24 個月）",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 105,
    highSpeedGb: 105,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "內地及澳門 6GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["6GB 內地及澳門數據", PERK_THREE_CN_NUM, PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    hot: true,
    bestFor: "適合高本地數據用量，以及需要內地副號之用戶",
  },
  {
    id: "three-5g-apac-10-158",
    providerId: "three",
    category: "mobile",
    name: "5G 亞太共用 10GB（24 個月）",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "亞太區 10GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["10GB 亞太區共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合間中前往亞太地區之用戶",
  },
  {
    id: "three-5g-cga-50-171",
    providerId: "three",
    category: "mobile",
    name: "5G 三地共用 50GB（24 個月）",
    monthlyFee: 171,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: FUP_THREE_1M,
    roaming: "50GB 中港澳三地共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [PERK_THREE_CGA, "內地通話 3,000 分鐘", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合高三地數據用量，以及需要內地通話之用戶",
  },
  {
    id: "three-5g-global-10-198",
    providerId: "three",
    category: "mobile",
    name: "5G 全球共用 10GB（24 個月）",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "全球 10GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["10GB 全球共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合間中外遊、需要全球數據之用戶",
  },
  {
    id: "three-5g-apac-20-208",
    providerId: "three",
    category: "mobile",
    name: "5G 亞太共用 20GB（24 個月）",
    monthlyFee: 208,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 20,
    highSpeedGb: 20,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "亞太區 20GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["20GB 亞太區共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合較常前往亞太地區之用戶",
  },
  {
    id: "three-5g-apac-30-238",
    providerId: "three",
    category: "mobile",
    name: "5G 亞太共用 30GB（24 個月）",
    monthlyFee: 238,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "亞太區 30GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["30GB 亞太區共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合高亞太數據用量之用戶",
  },
  {
    id: "three-5g-cga-70-257",
    providerId: "three",
    category: "mobile",
    name: "5G 三地共用 70GB（24 個月）",
    monthlyFee: 257,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 70,
    highSpeedGb: 70,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "70GB 中港澳三地共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [PERK_THREE_CGA, "內地通話 100 分鐘", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合高三地數據用量，以及需要內地通話之用戶",
  },
  {
    id: "three-5g-apac-60-268",
    providerId: "three",
    category: "mobile",
    name: "5G 亞太共用 60GB（24 個月）",
    monthlyFee: 268,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 60,
    highSpeedGb: 60,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "亞太區 60GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["60GB 亞太區共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合極高亞太數據用量之用戶",
  },
  {
    id: "three-5g-global-20-268",
    providerId: "three",
    category: "mobile",
    name: "5G 全球共用 20GB（24 個月）",
    monthlyFee: 268,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 20,
    highSpeedGb: 20,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "全球 20GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["20GB 全球共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合較常外遊、需要全球數據之用戶",
  },
  {
    id: "three-5g-family-126-268",
    providerId: "three",
    category: "mobile",
    name: "5G 家庭共享 126GB（24 個月）",
    monthlyFee: 268,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 126,
    highSpeedGb: 126,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "大灣區 3GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["2 張 SIM 卡共享 126GB", "3GB 大灣區數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合兩人共用本地數據之家庭",
  },
  {
    id: "three-5g-global-30-318",
    providerId: "three",
    category: "mobile",
    name: "5G 全球共用 30GB（24 個月）",
    monthlyFee: 318,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_THREE_1M,
    voice: VOICE_THREE_3000,
    roaming: "全球 30GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["30GB 全球共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合高全球數據用量之用戶",
  },
  {
    id: "three-5g-family-150-319",
    providerId: "three",
    category: "mobile",
    name: "5G 家庭共享 150GB（30 個月）",
    monthlyFee: 319,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 150,
    highSpeedGb: 150,
    roaming: "大灣區 10GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["5 張 SIM 卡共享 150GB", "10GB 大灣區數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合多人共用本地數據之家庭",
  },
  {
    id: "three-5g-global-50-348",
    providerId: "three",
    category: "mobile",
    name: "5G 全球共用 50GB（24 個月）",
    monthlyFee: 348,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: FUP_THREE_1M,
    roaming: "全球 50GB 共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["50GB 全球共用數據", PERK_THREE_ADMIN],
    portInPerk: PERK_THREE_ADMIN_PORT,
    bestFor: "適合極高全球數據用量之用戶",
  },
  {
    id: "cmhk-slash-5g-30-98",
    providerId: "cmhk",
    category: "mobile",
    name: "s/ash 5G 30GB（24 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 3GB；送內地通話 50 分鐘（至 2026/12/31）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [PERK_CMHK_SOCIAL, "可 HK$9／月加購移動安全管家－進階版"],
    portInPerk: `轉台本地數據雙倍至 60GB（至 2026/12/31）；${PERK_CMHK_ADMIN_STUDENT}`,
    limits: LIMITS_CMHK_SLASH,
    bestFor: "適合本地中用量、學生或轉台客",
  },
  {
    id: "cmhk-slash-5g-10-78",
    providerId: "cmhk",
    category: "mobile",
    name: "s/ash 5G 10GB（24 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 1GB；限時額外 5GB 中澳（至 2026/12/31）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["額外 5GB 中澳數據至 2026/12/31"],
    portInPerk: `轉台送內地通話 10 分鐘；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_SLASH,
    bestFor: "適合輕用量、以即時通訊為主",
  },
  {
    id: "cmhk-5g-trial-20-98",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 體驗 20GB（24 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 1+1GB；疊優惠再 +1GB（至 2026/09/30）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [
      "20GB 加額外 10GB，合共 30GB",
      "疊優惠可再 +10GB 本地",
      "限時可疊每月 HK$27 折扣（至 2026/09/30，實付約 HK$71）",
    ],
    portInPerk: `轉台可送 20,000 MyLink 積分（至 2026/09/30）；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_TRIAL,
    bestFor: "適合轉台、想用限時折扣再減月費",
  },
  {
    id: "cmhk-5g-trial-10-3hk-68",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 體驗 10GB（3HK 客專享，24 個月）",
    monthlyFee: 68,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_CMHK_5M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "接聽中港澳免費；撥打中港澳 HK$0.65／分鐘",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["3HK 客專屬價", "其後速度最高 5Mbps"],
    portInPerk: `須由 3香港攜號轉台；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_3HK,
    bestFor: "適合現用 3香港、準備轉台",
  },
  {
    id: "cmhk-42m-10-5-98",
    providerId: "cmhk",
    category: "mobile",
    name: "移動 42Mbps 10+5GB（24 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_CMHK_2M,
    voice: VOICE_CMHK_3000,
    install: "不適用",
    housing: "all",
    network: "4G（最高 42Mbps）",
    perks: ["約 30GB（10+5+限時 15GB）", "其後速度 2Mbps，快過多數 1Mbps 計劃"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_MOBILE,
    bestFor: "適合不需要 5G、想要較快限速後備速度",
  },
  {
    id: "cmhk-42m-3gb-38",
    providerId: "cmhk",
    category: "mobile",
    name: "低用量 移動 42Mbps 3GB（24 個月）",
    monthlyFee: 38,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 3,
    highSpeedGb: 3,
    fupNote: FUP_CMHK_128K,
    voice: VOICE_CMHK_3000,
    roaming: "超出後 $0.5／MB（每日上限 HK$48）",
    install: "不適用",
    housing: "all",
    network: "4G（最高 42Mbps）",
    perks: ["限時計劃至 2026/09/30", PERK_CMHK_ADMIN_LIMITED],
    limits: LIMITS_CMHK_LOW,
    bestFor: "適合備用卡、極輕用量",
  },
  {
    id: "cmhk-21m-3-3-38",
    providerId: "cmhk",
    category: "mobile",
    name: "低用量 移動 21Mbps 3+3GB（24 個月）",
    monthlyFee: 38,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 6,
    highSpeedGb: 6,
    fupNote: FUP_CMHK_128K,
    voice: VOICE_CMHK_3000,
    install: "不適用",
    housing: "all",
    network: "4G（最高 21Mbps）",
    perks: ["3GB 加額外 3GB，合共 6GB", "限時計劃至 2026/09/30", PERK_CMHK_ADMIN_LIMITED],
    limits: LIMITS_CMHK_LOW,
    bestFor: "適合備用卡、比 3GB 版需要多一點數據",
  },
  {
    id: "cmhk-elder-care-6gb-38",
    providerId: "cmhk",
    category: "mobile",
    name: "關愛長者 21Mbps 6GB（24 個月）",
    monthlyFee: 38,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 6,
    highSpeedGb: 6,
    fupNote: FUP_CMHK_128K,
    voice: VOICE_CMHK_3000,
    roaming: "超出後 $0.5／MB（每日上限 HK$48）",
    install: "不適用",
    housing: "all",
    network: "4G（最高 21Mbps）",
    perks: [PERK_CMHK_ADMIN_WAIVED, "須年滿 65 歲並持綜援或長者生活津貼證明"],
    limits: LIMITS_CMHK_ELDER_65,
    bestFor: "適合合資格長者",
  },
  {
    id: "cmhk-elder-5g-10-78",
    providerId: "cmhk",
    category: "mobile",
    name: "長者 5G 10GB（24 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 2GB；中港澳接聽免費，撥打 HK$0.65／分鐘",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["免費來電攔截服務（經 MyLink App 申請）", "可疊 HK$10 月費折扣"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_ELDER_60,
    bestFor: "適合 60 歲或以上、想用 5G 的長者",
  },
  {
    id: "cmhk-elder-5g-30-98",
    providerId: "cmhk",
    category: "mobile",
    name: "長者 5G 30GB（24 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 3+3GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["購機券 HK$300"],
    portInPerk: `轉台可雙倍本地數據至 60GB（至 2026/09/30）；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_ELDER_60,
    bestFor: "適合 60 歲或以上、用量接近一般大眾的長者",
  },
  {
    id: "cmhk-elder-5g-10-hkcn-99",
    providerId: "cmhk",
    category: "mobile",
    name: "長者 5G 10GB（中港 2 用，24 個月）",
    monthlyFee: 99,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 15,
    highSpeedGb: 15,
    fupNote: FUP_CMHK_1M,
    voice: "本地通話無限；包 100 分鐘中港通話",
    roaming: "中港共用 10+5GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["免費移動安全管家－基礎版", "可 HK$9／月加購一卡多號"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_ELDER_60,
    bestFor: "適合 60 歲或以上、經常過關探親之長者",
  },
  {
    id: "cmhk-slash-5g-50-138",
    providerId: "cmhk",
    category: "mobile",
    name: "s/ash 5G 50GB（24 個月）",
    monthlyFee: 138,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 4+2GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["50GB 基數及額外 50GB，合共 100GB", "購機券 HK$600", "送中國內地通話 100 分鐘（至 2026/12/31）"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_SLASH,
    bestFor: "適合重用量、短片用戶",
  },
  {
    id: "cmhk-slash-5g-100-178",
    providerId: "cmhk",
    category: "mobile",
    name: "s/ash 5G 100GB（24 個月）",
    monthlyFee: 178,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 200,
    highSpeedGb: 200,
    fupNote: FUP_CMHK_5M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 6+6GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["100GB 基數及額外 100GB，合共 200GB", "購機券 HK$1,200", "送中國內地通話 200 分鐘"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_SLASH,
    bestFor: "適合極重用量或家庭熱點",
  },
  {
    id: "cmhk-5g-ultimate-50-129-24m",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 極致 50GB（24 個月）",
    monthlyFee: 129,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 2+2GB（轉台）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["最多 3 張副卡（純數據 HK$40／語音及數據 HK$80）", "購機券 HK$600"],
    portInPerk: `轉台可免第 4 個月月費（至 2026/09/30）；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_MOBILE,
    bestFor: "適合要副卡、不受 s/ash 一人一計劃限制",
  },
  {
    id: "cmhk-5g-ultimate-50-129-36m",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 極致 50GB（36 個月）",
    monthlyFee: 129,
    freeMonths: 6,
    contractMonths: 36,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 2+2GB（轉台）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [
      "轉台免 6 個月月費（第 3/6/9/12/15/18 個月，至 2026/09/30）",
      "最多 3 張副卡",
      "送 20,000 MyLink 積分",
    ],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_ULTIMATE36,
    bestFor: "適合接受較長合約、轉台想免多個月月費",
  },
  {
    id: "cmhk-5g-limited-50-129",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 限定 50GB（36 個月）",
    monthlyFee: 129,
    freeMonths: 6,
    contractMonths: 36,
    rebate: 400,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: FUP_CMHK_1M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "全中國及澳門 9GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["免 6 個月月費", "送 HK$400 月費回贈", "全中國及澳門數據 9GB", PERK_CMHK_ADMIN],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_LIMITED,
    quotePick: true,
    latestOffer: true,
    bestFor: "適合需要 50GB 本地數據及中澳漫遊之用戶",
  },
  {
    id: "cmhk-5g-ultimate-100-149",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 極致 100GB（24 個月）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: FUP_CMHK_5M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 2+1+2GB（轉台）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["購機券 HK$1,200", "可加副卡"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_MOBILE,
    bestFor: "適合重用量但不想受 s/ash 一人一計劃限制",
  },
  {
    id: "cmhk-5g-ultimate-200-199",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 極致 200GB（24 個月）",
    monthlyFee: 199,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 200,
    highSpeedGb: 200,
    fupNote: FUP_CMHK_5M,
    voice: VOICE_CMHK_UNLIMITED,
    roaming: "中澳 2+2+2GB（轉台）",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["購機券 HK$1,200", "200/300GB 副卡半價（至 2026/09/30，首月正價）"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_MOBILE,
    bestFor: "適合家庭熱點或極重用量",
  },
  {
    id: "cmhk-5g-2places-20-youth-139",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 一咭兩地 20GB（18–29 青年及教職員，24 個月）",
    monthlyFee: 139,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 20,
    highSpeedGb: 20,
    fupNote: FUP_CMHK_1M,
    voice: "本地通話無限；中港首 200 分鐘免費",
    roaming: "中港共用 20GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["青年可以 HK$9／月加購任用社交及娛樂數據組合（原價 HK$38）"],
    portInPerk: PERK_CMHK_ADMIN_PORT,
    limits: LIMITS_CMHK_YOUTH,
    bestFor: "適合 18–29 歲或教職員、經常往返中港",
  },
  {
    id: "cmhk-5g-2places-50-179",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 一咭兩地 50GB（24 個月）",
    monthlyFee: 179,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: FUP_CMHK_1M,
    voice: "本地通話無限；中港首 200 分鐘免費",
    roaming: "中港共用 50GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["送 HK$150 單次旅遊保險券（至 2026/12/31，有效 180 日）", "購機券 HK$600"],
    portInPerk: `轉台可免第 4 個月月費（至 2026/09/30）；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_MOBILE,
    bestFor: "適合每周北上或經常過關",
  },
  {
    id: "cmhk-5g-gba-15-cny-198",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 大灣區 15GB 新春（24 個月）",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 35,
    highSpeedGb: 35,
    fupNote: FUP_CMHK_GBA,
    voice: "本地通話無限；中／港／澳免費任聽；中／澳通話包 100 分鐘",
    roaming: "大灣區 15GB",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["本地 35GB 加 15GB 大灣區數據", "三地免費接聽", "最多 3 張副卡"],
    portInPerk: `轉台首兩月額外 15GB 大灣區數據；${PERK_CMHK_ADMIN_PORT}`,
    limits: LIMITS_CMHK_MOBILE,
    bestFor: "適合經常走粵港澳、司機或大灣區業務",
  },
  {
    id: "csl-45g-78",
    providerId: "csl",
    category: "mobile",
    name: "4.5G 10GB",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: "10GB 高速數據其後以 1Mbps 任用",
    voice: "本地無限分鐘",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["轉台或附禮品（視申請時優惠而定）"],
    bestFor: "適合輕量上網、需要無限通話之用戶",
  },
  {
    id: "csl-5g-30",
    providerId: "csl",
    category: "mobile",
    name: "5G 30GB",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後以 1Mbps 任用",
    voice: "本地無限分鐘",
    roaming: "每月 3GB 中澳數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["轉台或可享 HK$100 回贈（視申請時優惠而定）"],
    portInPerk: "攜號轉台簽訂 36 個月合約或可享月費回贈",
    bestFor: "適合重視地鐵沿線覆蓋之用戶",
  },
  {
    id: "smartone-45g-78",
    providerId: "smartone",
    category: "mobile",
    name: "4.5G 首 10GB（24 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: "首 10GB（42Mbps），其後以 128kbps 任用",
    voice: "無限本地通話",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_SMARTONE_PORT,
    hot: true,
    bestFor: "適合輕量上網、需要無限本地通話之用戶",
  },
  {
    id: "smartone-45g-98",
    providerId: "smartone",
    category: "mobile",
    name: "4.5G 首 14GB（24 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 14,
    highSpeedGb: 14,
    fupNote: "首 14GB（42Mbps），其後以 2Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 1GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_SMARTONE_PORT,
    bestFor: "適合需要中澳數據，以及其後仍保持 2Mbps 之用戶",
  },
  {
    id: "smartone-5g-30-youth",
    providerId: "smartone",
    category: "mobile",
    name: "5G 30GB 青年計劃（36 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 3GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["適用於 18 至 29 歲"],
    portInPerk: PERK_SMARTONE_PORT,
    limits: "適用於 18 至 29 歲客戶。",
    bestFor: "適合 18 至 29 歲、需要 5G 30GB 之用戶",
  },
  {
    id: "smartone-45g-120",
    providerId: "smartone",
    category: "mobile",
    name: "4.5G 42Mbps 無限任用（24 個月）",
    monthlyFee: 120,
    freeMonths: 0,
    contractMonths: 24,
    fupNote: "42Mbps 無限任用",
    voice: "無限本地通話",
    roaming: "每月 1GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["無限本地數據（42Mbps）"],
    portInPerk: PERK_SMARTONE_PORT,
    bestFor: "適合需要 4.5G 無限數據及無限本地通話之用戶",
  },
  {
    id: "smartone-5g-60-youth",
    providerId: "smartone",
    category: "mobile",
    name: "5G 60GB 青年計劃（36 個月）",
    monthlyFee: 138,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 60,
    highSpeedGb: 60,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 4GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["適用於 18 至 29 歲"],
    portInPerk: PERK_SMARTONE_PORT,
    limits: "適用於 18 至 29 歲客戶。",
    bestFor: "適合 18 至 29 歲、需要 5G 60GB 之用戶",
  },
  {
    id: "smartone-5g-30-iphone",
    providerId: "smartone",
    category: "mobile",
    name: "5G 30GB 連手機券（36 個月）",
    monthlyFee: 139,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 2GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["新一代 iPhone 早鳥專屬優惠", "送 HK$1,400 手機券"],
    portInPerk: "攜號轉台本地數據雙倍；另加 HK$18 行政費",
    bestFor: "適合需要換機優惠及 5G 30GB 之用戶",
  },
  {
    id: "smartone-5g-60",
    providerId: "smartone",
    category: "mobile",
    name: "5G Premier 60GB",
    monthlyFee: 179,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 60,
    highSpeedGb: 60,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 2–4GB 中澳數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["可加購家庭副卡"],
    bestFor: "適合流動數據用量中等之用戶",
  },
  {
    id: "hkbn-45g-10",
    providerId: "hkbn",
    category: "mobile",
    name: "4.5G 10GB（24 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: "首 10GB（42Mbps），其後以 128kbps 任用",
    voice: "本地 3,000 分鐘",
    roaming: "每月 1GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    hot: true,
    bestFor: "適合輕量上網、攜號轉台之用戶",
  },
  {
    id: "hkbn-5g-30",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 30GB（28 個月）",
    monthlyFee: 98,
    freeMonths: 2,
    contractMonths: 28,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後按計劃條款任用",
    voice: "本地 3,000 分鐘",
    roaming: "每月 4GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["15 個常用流動應用程式數據任用（須受條款約束）", "每月 10 分鐘中國內地及澳門通話"],
    portInPerk: PERK_HKBN_PORT,
    hot: true,
    bestFor: "適合日常 5G 用量，以及不時前往內地或澳門之用戶",
  },
  {
    id: "hkbn-5g-30-78-youth",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 30GB 本地（含每月 3GB 中國內地及澳門）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後本地無限，限速不超過 1Mbps",
    voice: "本地 3000 分鐘；其後 $1／分鐘",
    roaming: "合約期內每月 3GB 中國內地及澳門",
    network: "5G",
    install: "不適用",
    housing: "all",
    perks: ["學生或年青人專題，須符合資格"],
    hot: true,
    latestOffer: true,
    quotePick: true,
    bestFor: "適合符合學生或年青人資格之用戶",
  },
  {
    id: "hkbn-45g-20",
    providerId: "hkbn",
    category: "mobile",
    name: "4.5G 20GB（24 個月）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 20,
    highSpeedGb: 20,
    fupNote: "其後按計劃公平使用政策任用",
    voice: "本地 3,000 分鐘",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合中等 4.5G 數據用量之用戶",
  },
  {
    id: "hkbn-5g-100",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 100GB（24 個月）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: "其後以 1Mbps 任用",
    voice: "本地 3,000 分鐘",
    roaming: "每月 8GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合高本地數據用量，以及需要較多內地數據之用戶",
  },
  {
    id: "hkbn-5g-100-148",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 100GB 任用（24 個月）",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: "其後按計劃條款任用",
    voice: "本地 3,000 分鐘",
    roaming: "每月 3GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合高本地數據用量之用戶",
  },
  {
    id: "hkbn-5g-cga-70",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 70GB 中港澳共享",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 70,
    highSpeedGb: 70,
    roaming: "香港、內地、澳門共享 70GB",
    voice: "本地 3,000 分鐘",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["香港、內地及澳門共享數據池"],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合一星期多次往返內地或澳門之用戶",
  },
  {
    id: "hkbn-5g-50-cga",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 50GB 中港共用（24 個月）",
    monthlyFee: 179,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: "其後以 1Mbps 任用",
    voice: "本地 3,000 分鐘",
    roaming: "50GB 中港共用數據；另加每月 4GB 澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["送 HK$500 超市現金券"],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合經常往返內地，以及需要澳門數據之用戶",
  },
  {
    id: "hkbn-5g-30-cga",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 30GB 三地共用（24 個月）",
    monthlyFee: 188,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後按計劃條款任用",
    voice: "本地 3,000 分鐘",
    roaming: "30GB 香港、內地及澳門三地共用；另加每月 1GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合需要中港澳三地共用數據之用戶",
  },
  {
    id: "hkbn-5g-200",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 200GB 網上限定",
    monthlyFee: 199,
    freeMonths: 1,
    contractMonths: 24,
    dataGb: 200,
    highSpeedGb: 200,
    voice: "本地 3,000 分鐘",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["200GB 本地高速數據"],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合沒有家居寬頻、主要依靠手機熱點之用戶",
  },
  {
    id: "cmhk-biz-1000",
    providerId: "cmhk",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP 可選"],
    bestFor: "適合店舖或小型寫字樓",
  },
  {
    id: "hgc-biz-1000",
    providerId: "hgc",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 228,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["企業支援"],
    bestFor: "適合需要較穩定上傳之商戶",
  },
  {
    id: "hkbn-biz-1000",
    providerId: "hkbn",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 248,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP 可選"],
    bestFor: "適合中小型商戶",
  },
  {
    id: "netvigator-biz-1000",
    providerId: "netvigator",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 268,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["企業支援熱線"],
    bestFor: "適合需要電訊盈科商用支援之客戶",
  },
  {
    id: "hgc-biz-2500",
    providerId: "hgc",
    category: "business",
    name: "商業 2500M",
    monthlyFee: 388,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP"],
    bestFor: "適合多部電腦同時使用之寫字樓",
  },
  {
    id: "hkbn-biz-2500",
    providerId: "hkbn",
    category: "business",
    name: "商業 2500M",
    monthlyFee: 398,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP 可選"],
    bestFor: "適合中型辦公室",
  },
  {
    id: "hgc-biz-5000",
    providerId: "hgc",
    category: "business",
    name: "商業 5000M",
    monthlyFee: 588,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 5000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP", "企業支援"],
    bestFor: "適合多樓層辦公室",
  },
  {
    id: "hkbn-biz-5000",
    providerId: "hkbn",
    category: "business",
    name: "商業 5000M",
    monthlyFee: 598,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 5000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP"],
    bestFor: "適合頻密上載之商戶",
  },
  {
    id: "hgc-biz-10000",
    providerId: "hgc",
    category: "business",
    name: "商業 10000M",
    monthlyFee: 788,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP", "企業支援"],
    bestFor: "適合大型辦公室",
  },
  {
    id: "hkbn-biz-10000",
    providerId: "hkbn",
    category: "business",
    name: "商業 10000M",
    monthlyFee: 798,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP"],
    bestFor: "適合高流量企業",
  },
  {
    id: "netvigator-biz-10000",
    providerId: "netvigator",
    category: "business",
    name: "商業 10000M",
    monthlyFee: 798,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP", "企業支援"],
    bestFor: "適合經常連海外總部之企業",
  },
];

export type PlansSearch = {
  cat: Category;
  housing?: Housing;
  maxFee?: number;
  speed?: SpeedMbps;
  minSpeed?: number;
  minData?: number;
  provider?: ProviderId;
  portIn?: boolean;
  generation?: Generation;
  gba?: boolean;
  q?: string;
  estate?: string;
  sort?: "fee" | "avg" | "speed" | "data";
  saved?: boolean;
  intake?: boolean;
};

export function averageFee(plan: Plan) {
  const rebate = plan.rebate ?? 0;
  if (!plan.freeMonths && !rebate) return plan.monthlyFee;
  return Math.round(((plan.monthlyFee * (plan.contractMonths - plan.freeMonths) - rebate) / plan.contractMonths) * 10) / 10;
}

export function matchesHousing(plan: Plan, housing?: Housing) {
  if (!housing) return true;
  if (plan.housing === "all") return true;
  return plan.housing.includes(housing);
}

export function isNetvigatorVillage(plan: Plan) {
  return plan.providerId === "netvigator" && plan.housing !== "all" && plan.housing.includes("village");
}

export function isHktPlan(plan: Plan) {
  return plan.providerId === "netvigator" || plan.providerId === "csl";
}

export type CertifiedStaffNoteKey = "hktStaffNote" | "hkbnStaffNote";

export function certifiedStaffNoteKey(plan: Plan): CertifiedStaffNoteKey | null {
  if (plan.providerId === "netvigator" || plan.providerId === "csl") return "hktStaffNote";
  if (plan.providerId === "hkbn") return "hkbnStaffNote";
  return null;
}

export function certifiedStaffNoteKeys(plans: Plan[]): CertifiedStaffNoteKey[] {
  const keys: CertifiedStaffNoteKey[] = [];
  for (const plan of plans) {
    const key = certifiedStaffNoteKey(plan);
    if (key && !keys.includes(key)) keys.push(key);
  }
  return keys;
}

export function hasCertifiedStaff(plan: Plan) {
  return certifiedStaffNoteKey(plan) !== null;
}

export function planGeneration(plan: Plan): Generation | undefined {
  if (plan.category !== "mobile") return undefined;
  return plan.network.startsWith("5G") ? "5g" : "4g";
}

export function hasGba(plan: Plan) {
  const blob = `${plan.roaming ?? ""} ${plan.name} ${plan.perks.join(" ")} ${plan.limits ?? ""}`;
  return /中澳|中港|大灣區|三地|澳門|內地/.test(blob);
}

export function filterPlans(search: PlansSearch, savedIds: string[] = []) {
  let rows = PLANS.filter((plan) => {
    if (plan.category !== search.cat) return false;
    if (
      (search.cat === "broadband" || search.cat === "business") &&
      isNetvigatorOnlyEstate(search.estate) &&
      plan.providerId !== "netvigator"
    ) {
      return false;
    }
    if (plan.onlyEstates?.length) {
      const unlocked = estateUnlocksPlan(search.estate, plan.onlyEstates);
      if (search.intake) {
        if (search.estate && !unlocked) return false;
      } else if (!unlocked) {
        return false;
      }
    }
    if (search.intake && !plan.newIntakeOffer) return false;
    if (!matchesHousing(plan, search.housing)) return false;
    if (search.maxFee && plan.monthlyFee > search.maxFee) return false;
    if (search.speed && plan.speedMbps !== search.speed) return false;
    if (search.minSpeed && (plan.speedMbps ?? 0) < search.minSpeed) return false;
    if (search.minData) {
      const data = plan.dataGb ?? plan.highSpeedGb ?? (plan.fupNote ? 0 : 9999);
      if (data < search.minData) return false;
    }
    if (search.provider && plan.providerId !== search.provider) return false;
    if (search.portIn && !plan.portInPerk) return false;
    if (search.generation && planGeneration(plan) !== search.generation) return false;
    if (search.gba && !hasGba(plan)) return false;
    if (search.saved && !savedIds.includes(plan.id)) return false;
    if (search.q) {
      const provider = PROVIDER_MAP[plan.providerId];
      const extra = plan.providerId === "netvigator" ? "電訊盈科 PCCW" : "";
      const blob =
        `${plan.name} ${provider.name} ${provider.nameEn} ${plan.network} ${plan.perks.join(" ")} ${plan.prepaid ?? ""} ${plan.limits ?? ""} ${extra}`.toLowerCase();
      if (!blob.includes(search.q.trim().toLowerCase())) return false;
    }
    return true;
  });

  const sort = search.sort ?? "fee";
  rows = [...rows].sort((a, b) => {
    if (sort === "avg") return averageFee(a) - averageFee(b);
    if (sort === "speed") return (b.speedMbps ?? 0) - (a.speedMbps ?? 0);
    if (sort === "data") return (b.dataGb ?? b.highSpeedGb ?? 0) - (a.dataGb ?? a.highSpeedGb ?? 0);
    return a.monthlyFee - b.monthlyFee;
  });
  return rows;
}

export function getPlan(id: string) {
  return PLANS.find((p) => p.id === id);
}

export function formatFee(value: number) {
  return Number.isInteger(value) ? `HK$${value}` : `HK$${value.toFixed(1)}`;
}

export function minMonthlyFee(category: Category) {
  return cheapestPlan(category)?.monthlyFee ?? 0;
}

export function minVillageBroadbandFee() {
  return cheapestVillageBroadbandPlan()?.monthlyFee ?? 0;
}

function isVillageCapable(plan: Plan) {
  return plan.housing === "all" || plan.housing.includes("village");
}

function isVillageOnly(plan: Plan) {
  return plan.housing !== "all" && plan.housing.every((item) => item === "village");
}

function pickCheapest(rows: Plan[]): Plan | undefined {
  if (!rows.length) return undefined;
  return [...rows].sort((a, b) => {
    if (a.monthlyFee !== b.monthlyFee) return a.monthlyFee - b.monthlyFee;
    if (!!a.quotePick !== !!b.quotePick) return a.quotePick ? -1 : 1;
    const avg = averageFee(a) - averageFee(b);
    if (avg) return avg;
    const data =
      (b.dataGb ?? b.highSpeedGb ?? 0) - (a.dataGb ?? a.highSpeedGb ?? 0);
    if (data) return data;
    return a.id.localeCompare(b.id);
  })[0];
}

/** Lowest monthly-fee plan in a category. Fibre slot skips village-only rows. */
export function cheapestPlan(category: Category): Plan | undefined {
  return pickCheapest(
    PLANS.filter((plan) => {
      if (plan.category !== category) return false;
      if (plan.onlyEstates?.length) return false;
      if (category === "broadband" && isVillageOnly(plan)) return false;
      return true;
    }),
  );
}

export function cheapestVillageBroadbandPlan(): Plan | undefined {
  return pickCheapest(PLANS.filter((plan) => plan.category === "broadband" && isVillageCapable(plan) && !plan.onlyEstates?.length));
}

export function formatMonthly(value: number) {
  return `${formatFee(value)}／月`;
}

export function formatSpeed(mbps?: number, network?: string) {
  if (!mbps) return network || "視計劃而定";
  return network ? `${mbps}M ${network}` : `${mbps}M`;
}

export function formatPlanSpeed(plan: Plan) {
  if (plan.category === "home5g") return "100M–1000M";
  return formatSpeed(plan.speedMbps);
}

export function formatInstall(plan: Plan) {
  return plan.category === "mobile" ? "不適用" : plan.install;
}

export function formatPrepaidShort(prepaid: string) {
  const match = prepaid.match(/須預繳 HK\$[0-9,]+/);
  return match ? match[0] : prepaid;
}

export function planPerks(plan: Plan) {
  const extra = plan.providerId === "hgc" && !plan.perks.includes("豁免搬遷費") ? ["豁免搬遷費"] : [];
  const list = [...plan.perks, ...extra];
  return list.filter((perk) => {
    if (plan.install.includes("豁免安裝") && perk.includes("豁免安裝")) return false;
    return true;
  });
}

export const CATEGORY_LABEL: Record<Category, string> = {
  broadband: "光纖寬頻",
  mobile: "手機月費",
  home5g: "5G 家居寬頻",
  business: "商業寬頻",
};

export const HOUSING_LABEL: Record<Housing, string> = {
  public: "公屋",
  hos: "居屋",
  private: "私人樓",
  village: "村屋",
};
