const CJK = /[\u3400-\u9FFF]/;

const EXACT: Record<string, string> = {
  "本計劃為自動續約。優惠適用於指定公屋、居屋及私人住宅，且該地址於登記前 120 日內未曾使用香港寬頻之寬頻服務。實際安裝費用及網絡覆蓋視乎個別大廈基礎設施而定。不適用於村屋。":
    "This plan auto-renews. Offer applies to selected public housing, HOS and private homes that have not used HKBN broadband in the 120 days before signup. Installation fees and coverage depend on the building. Not available for village houses.",
  "本計劃為自動續約。家居 5000M 光纖入屋現時主要由香港寬頻提供，適用於指定公屋、居屋及私人住宅。不適用於村屋。":
    "This plan auto-renews. Home 5000M FTTH is currently offered mainly by HKBN for selected public housing, HOS and private homes. Not available for village houses.",
  "本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。適用於指定公屋、居屋及私人住宅。不適用於村屋。":
    "This plan auto-renews. Service start can be deferred up to 365 days. For selected public housing, HOS and private homes. Not available for village houses.",
  "僅適用於指定新入伙屋苑。本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。豁免安裝費。實際覆蓋同安裝期以電訊商確認為準。":
    "Selected new-move-in estates only. This plan auto-renews. Service start can be deferred up to 365 days. Installation waived. Coverage and install dates are confirmed by the carrier.",
  "僅適用於指定屋苑。須繳付安裝費。實際覆蓋同安裝期以電訊商確認為準。":
    "Selected estates only. Installation fee applies. Coverage and install dates are confirmed by the carrier.",
  "僅適用於指定屋苑。本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。實際覆蓋同安裝期以電訊商確認為準。":
    "Selected estates only. This plan auto-renews. Service start can be deferred up to 365 days. Coverage and install dates are confirmed by the carrier.",
  "僅適用於指定村屋地址。本計劃為 27 個月合約。可選擇延遲服務生效日（最長 365 日）。香港寬頻之公屋、居屋及私人樓宇計劃不適用於村屋地址。實際覆蓋須另行核對。":
    "Village-house addresses only. 27-month contract. Service start can be deferred up to 365 days. HKBN public/HOS/private plans do not apply to village houses. Coverage must be confirmed separately.",
  "僅適用於指定村屋地址。本計劃為 24 個月合約。可選擇延遲服務生效日（最長 365 日）。實際覆蓋須另行核對。":
    "Village-house addresses only. 24-month contract. Service start can be deferred up to 365 days. Coverage must be confirmed separately.",
  "可選擇先安裝後啟動服務（最長 365 日）。實際覆蓋視乎個別樓宇而定。":
    "Install first, activate later (up to 365 days). Coverage depends on the building.",
  "可選擇先安裝後啟動服務（最長 365 日）。實際覆蓋視乎個別樓宇而定。僅適用於指定獨家私人樓宇。":
    "Install first, activate later (up to 365 days). Coverage depends on the building. Selected exclusive private buildings only.",
  "家居 10000M 光纖入屋現時主要由香港寬頻及電訊盈科網上行提供，適用於公屋、居屋及私人住宅。首次安裝須繳付安裝費。實際覆蓋視乎個別樓宇基礎設施而定。":
    "Home 10000M FTTH is currently offered mainly by HKBN and HKT Netvigator for public housing, HOS and private homes. Installation fee applies on first install. Coverage depends on the building.",
  "適用於指定村屋及唐樓地址。須另行繳付安裝費。實際覆蓋須核對門牌。網上行之公屋、居屋及私人樓宇計劃不適用於村屋或唐樓。":
    "For selected village houses and tong lau. Installation fee extra. Coverage must be checked against the exact address. Netvigator public/HOS/private plans do not apply to village houses or tong lau.",
  "適用於指定村屋及唐樓地址。豁免安裝費。實際覆蓋須核對門牌。網上行之公屋、居屋及私人樓宇計劃不適用於村屋或唐樓。":
    "For selected village houses and tong lau. Installation waived. Coverage must be checked against the exact address. Netvigator public/HOS/private plans do not apply to village houses or tong lau.",
  "適用於村屋地址。馬灣或若干指定村落未必享有額外特別優惠，詳情請向當值銷售員查詢。不適用於公屋、居屋及私人樓宇。實際覆蓋須核對門牌。":
    "For village-house addresses. Ma Wan or certain villages may not have extra promotions; ask the on-duty sales adviser. Not for public housing, HOS or private buildings. Coverage must be checked against the exact address.",
  "適用於公屋、居屋及私人樓宇。不適用於村屋。":
    "Applies to public housing, HOS and private buildings. Not for village houses.",
  "實際速度介乎 100M 至 1000M，視乎訊號覆蓋、裝置數量及現場環境而定。":
    "Typical speed 100M–1000M, depending on coverage, devices and site conditions.",
  "實際速度介乎 100M 至 1000M，視乎訊號覆蓋、裝置數量及現場環境而定。本計劃為自動續約。P2P 及 Thunder 下載期間限速至 128kbps。":
    "Typical speed 100M–1000M, depending on coverage, devices and site conditions. This plan auto-renews. P2P and Thunder downloads capped at 128kbps.",
  "任用社交組合 15 個應用程式（Facebook、Instagram、WhatsApp、LINE、WeChat、Signal、Zoom、YouTube、Netflix、Apple TV、myTV SUPER、Disney+、hmvod、Douyin 及 Teams；不包括下載）":
    "Unlimited data for 15 apps (Facebook, Instagram, WhatsApp, LINE, WeChat, Signal, Zoom, YouTube, Netflix, Apple TV, myTV SUPER, Disney+, hmvod, Douyin and Teams; downloads excluded)",
  "Now TV 體驗組合或國際新聞組合（智能電視版）；可加 HK$38 升級機頂盒":
    "Now TV trial pack or international news pack (smart TV); add HK$38 for a set-top box",
  "四選一：Disney+ 標準版 12 個月、Netflix 標準版 12 個月、愛奇藝鑽石會員 12 個月或 TP-Link Archer AX23 路由器":
    "Pick one: 12 months Disney+ Standard, 12 months Netflix Standard, 12 months iQIYI Diamond, or a TP-Link Archer AX23 router",
  "四選一：TP-Link Archer AX23 路由器、愛奇藝黃金會員 12 個月、JOOX VIP 12 個月或 WeTV 12 個月":
    "Pick one: TP-Link Archer AX23 router, 12 months iQIYI Gold, 12 months JOOX VIP, or 12 months WeTV",
  "送 24 個月 myTV SUPER 組合（基本、TVB 外購節目、精選基本、跨屏幕同時睇）":
    "Includes 24 months myTV SUPER (basic, TVB acquired titles, selected basic, multi-screen)",
  "原 1000M 計劃加購每月 HK$46（24 個月），合約期內自動升級至 2500M":
    "Add HK$46/month to a 1000M plan (24 months) to auto-upgrade to 2500M during the contract",
  "須預繳 HK$200，第 1 至第 4 個月每月從預繳費用中扣減月費 HK$50":
    "Prepaid HK$200; HK$50/month deducted in months 1–4",
  "須預繳 HK$3,600，第 1 至第 24 個月每月回贈 HK$150":
    "Prepaid HK$3,600; HK$150 rebate/month in months 1–24",
};

const PHRASES: [string, string][] = [
  ["以信用卡自動轉賬可豁免按金 HK$1,500", "HK$1,500 deposit waived with credit-card autopay"],
  ["可加購每月 HK$68 換購指定家電（須符合資格）", "Optional HK$68/month to redeem selected appliances (eligibility applies)"],
  ["可加 HK$10 選配 Linksys EA9350 Wi-Fi 6 路由器", "Add HK$10 for a Linksys EA9350 Wi-Fi 6 router"],
  ["送 TP-Link Deco BE25 兩件裝 Wi-Fi 7 路由器（36 個月）", "Includes TP-Link Deco BE25 two-pack Wi-Fi 7 router (36 months)"],
  ["送 TP-Link Archer BE230 Wi-Fi 7 路由器（36 個月）", "Includes TP-Link Archer BE230 Wi-Fi 7 router (36 months)"],
  ["送 TP-Link Aginet EB810v Wi-Fi 7 路由器（24 個月）", "Includes TP-Link Aginet EB810v Wi-Fi 7 router (24 months)"],
  ["送 TP-Link Archer GE800 Wi-Fi 7 路由器（24 個月）", "Includes TP-Link Archer GE800 Wi-Fi 7 router (24 months)"],
  ["送指定 TP-Link Archer BE230 Wi-Fi 7 路由器（12 個月）", "Includes designated TP-Link Archer BE230 Wi-Fi 7 router (12 months)"],
  ["送 TP-Link BE230 Wi-Fi 7 路由器（合約後無須歸還）", "Includes TP-Link BE230 Wi-Fi 7 router (keep after contract)"],
  ["送指定 TP-Link Archer BE230 Wi-Fi 7 路由器", "Includes designated TP-Link Archer BE230 Wi-Fi 7 router"],
  ["送指定 TP-Link BE230 Wi-Fi 7 路由器", "Includes designated TP-Link BE230 Wi-Fi 7 router"],
  ["送指定 TP-Link Wi-Fi 6 路由器", "Includes designated TP-Link Wi-Fi 6 router"],
  ["送 TP-Link Archer BE220 Wi-Fi 7 路由器（價值每月 HK$39；24 個月，合約後無須歸還）", "Includes TP-Link Archer BE220 Wi-Fi 7 router (HK$39/month value; 24 months, keep after contract)"],
  ["三選一：Disney+ 標準計劃 24 個月、Netflix 標準計劃 24 個月或 HBO Max 標準計劃 24 個月", "Pick one: 24 months Disney+ Standard, 24 months Netflix Standard, or 24 months HBO Max Standard"],
  ["24 個月 5G 流動通訊 30GB 本地數據，送任用 15 款熱門串流及社交數據（原價每月 HK$98）", "24 months 5G mobile 30GB local data plus unlimited data for 15 streaming and social apps (HK$98/month value)"],
  ["1000M 四合一（Wi-Fi 7、OTT 及 5G 30GB｜24 個月）", "1000M four-in-one (Wi-Fi 7, OTT and 5G 30GB | 24 months)"],
  ["中國內地及澳門 4GB；通話 10 分鐘", "4GB Mainland & Macao data; 10 call minutes"],
  ["適合公屋、居屋或私人住宅，需要 1000M 光纖、Wi-Fi 7、影視會籍及手機數據之住戶", "For public housing, HOS or private homes that need 1000M fibre, Wi-Fi 7, a streaming membership and mobile data"],
  ["首 36 個月額外免費 1000M 副線", "Extra 1000M secondary line free for the first 36 months"],
  ["六選一：Disney+ 標準計劃 12 個月、Netflix 標準計劃 12 個月、HBO Max 標準計劃 12 個月、myTV GOLD 12 個月、愛奇藝黃金計劃 36 個月或 weTV 月費計劃 36 個月", "Pick one: 12 months Disney+ Standard, 12 months Netflix Standard, 12 months HBO Max Standard, 12 months myTV GOLD, 36 months iQIYI Gold, or 36 months weTV"],
  ["四選一：Disney+ 標準計劃 12 個月、Netflix 標準計劃 12 個月、HBO Max 標準計劃 12 個月或 myTV GOLD 12 個月", "Pick one: 12 months Disney+ Standard, 12 months Netflix Standard, 12 months HBO Max Standard, or 12 months myTV GOLD"],
  ["四選一：Disney+ 標準計劃 24 個月、Netflix 標準計劃 24 個月、HBO Max 標準計劃 24 個月或 myTV GOLD 24 個月", "Pick one: 24 months Disney+ Standard, 24 months Netflix Standard, 24 months HBO Max Standard, or 24 months myTV GOLD"],
  ["24 個月家居電話服務及 0030 IDD 每月 30 分鐘", "24 months home phone and 30 minutes 0030 IDD per month"],
  ["36 個月家居電話服務及 0030 IDD 每月 30 分鐘", "36 months home phone and 30 minutes 0030 IDD per month"],
  ["免費升級至 2×1000M 光纖", "Free upgrade to 2×1000M fibre"],
  ["12 個月 myTV SUPER 智能電視版", "12 months myTV SUPER smart TV"],
  ["1000M 新入伙特選（36 個月＋OTT）", "1000M new-move-in offer (36 months + OTT)"],
  ["2500M 新入伙特選（24 個月＋OTT）", "2500M new-move-in offer (24 months + OTT)"],
  ["2500M 新入伙特選（36 個月＋OTT）", "2500M new-move-in offer (36 months + OTT)"],
  ["2×1000M 新入伙特選（36 個月）", "2×1000M new-move-in offer (36 months)"],
  ["送 TP-Link BE230 Wi-Fi 7 路由器", "Includes TP-Link BE230 Wi-Fi 7 router"],
  ["送 TP-Link Wi-Fi 7 旗艦路由器", "Includes TP-Link Wi-Fi 7 flagship router"],
  ["送 TP-Link Wi-Fi 6 路由器", "Includes TP-Link Wi-Fi 6 router"],
  ["送 TP-Link AX55 路由器", "Includes TP-Link AX55 router"],
  ["送 TP-Link EX141 路由器", "Includes TP-Link EX141 router"],
  ["送指定 5G 路由器", "Includes designated 5G router"],
  ["送指定 Wi-Fi 6 路由器", "Includes designated Wi-Fi 6 router"],
  ["送指定 Wi-Fi 7 路由器", "Includes designated Wi-Fi 7 router"],
  ["包指定 Wi-Fi 6 路由器", "Wi-Fi 6 router included (may need to return after contract)"],
  ["包指定 Wi-Fi 7 路由器", "Wi-Fi 7 router included (may need to return after contract)"],
  ["送 HK$1,400 手機券", "Includes HK$1,400 handset coupon"],
  ["送 HK$500 超市現金券", "Includes HK$500 supermarket coupon"],
  ["送 Now TV 頻道", "Includes Now TV channels"],
  ["12 個月 WTFast 電競玩家專用網絡", "12 months WTFast gaming network"],
  ["12 個月 myTV SUPER 基本版（智能電視版）", "12 months myTV SUPER basic (smart TV)"],
  ["12 個月 myTV Gold 服務", "12 months myTV Gold"],
  ["12 個月 Disney+", "12 months Disney+"],
  ["24 個月 iQIYI 愛奇藝黃金會員", "24 months iQIYI Gold"],
  ["24 個月 Disney+ 標準計劃", "24 months Disney+ Standard"],
  ["24 個月 Netflix 標準計劃", "24 months Netflix Standard"],
  ["24 個月 100 分鐘 hgc on air Wi-Fi", "24 months of 100 minutes hgc on air Wi-Fi"],
  ["30 個月 100 分鐘 hgc on air Wi-Fi", "30 months of 100 minutes hgc on air Wi-Fi"],
  ["SAFE 網絡安全防護及防毒軟件 6 個月", "6 months SAFE security and antivirus"],
  ["SAFE 防毒軟件 6 個月", "6 months SAFE antivirus"],
  ["Money-Back 雙重保證（速度保證、低時延保證）", "Money-back double guarantee (speed and low latency)"],
  ["15 個常用流動應用程式數據任用（須受條款約束）", "Unlimited data for 15 popular apps (subject to terms)"],
  ["7 日冷靜期（服務啟用後連續使用 7 日）", "7-day cooling-off (7 consecutive days after service starts)"],
  ["每月免費 200 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5", "200 free China/Macao roaming minutes/month, then HK$0.5/min"],
  ["每月免費 100 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5", "100 free China/Macao roaming minutes/month, then HK$0.5/min"],
  ["每月免費 50 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5", "50 free China/Macao roaming minutes/month, then HK$0.5/min"],
  ["每月免費 10 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5", "10 free China/Macao roaming minutes/month, then HK$0.5/min"],
  ["30GB 香港、內地及澳門三地共用；另加每月 1GB 中國內地數據", "30GB shared across Hong Kong, Mainland and Macao, plus 1GB Mainland data/month"],
  ["50GB 中港共用數據；另加每月 4GB 澳門數據", "50GB HK–Mainland shared data, plus 4GB Macao data/month"],
  ["70GB 中國／香港／澳門三地共用", "70GB shared across China, Hong Kong and Macao"],
  ["香港、內地及澳門共享數據池", "Shared HK / Mainland / Macao data pool"],
  ["香港、內地、澳門共享 70GB", "70GB shared across HK, Mainland and Macao"],
  ["10GB 高速數據其後以 1Mbps 任用", "10GB high-speed data, then unlimited at 1Mbps"],
  ["首 10GB（42Mbps），其後以 128kbps 任用", "First 10GB (42Mbps), then unlimited at 128kbps"],
  ["首 14GB（42Mbps），其後以 2Mbps 任用", "First 14GB (42Mbps), then unlimited at 2Mbps"],
  ["其後本地無限，限速不超過 1Mbps", "Thereafter local unlimited, speed not exceeding 1Mbps"],
  ["其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps", "Then fair-use policy; P2P and Thunder capped at 128kbps"],
  ["其後無限任用，惟降低網絡優先權", "Then unlimited at lower priority"],
  ["其後提供 5G 任用數據", "Then 5G unlimited at reduced priority"],
  ["其後按計劃公平使用政策任用", "Then fair-use unlimited"],
  ["其後按計劃條款任用", "Then per plan terms"],
  ["其後以 128kbps 任用", "then unlimited at 128kbps"],
  ["其後以 1Mbps 任用", "then unlimited at 1Mbps"],
  ["其後以 2Mbps 任用", "then unlimited at 2Mbps"],
  ["其後限速無限上網（最高 1Mbps）", "Then unlimited at up to 1Mbps"],
  ["其後限速無限上網（最高 5Mbps）", "Then unlimited at up to 5Mbps"],
  ["其後限速無限上網", "Then unlimited at reduced speed"],
  ["其後無限（最高 2Mbps）", "Then unlimited at up to 2Mbps"],
  ["其後無限（最高 128kbps）", "Then unlimited at up to 128kbps"],
  ["大灣區其後無限（最高 384kbps）", "Then unlimited GBA data at up to 384kbps"],
  ["其後限速任用", "Then unlimited at reduced speed"],
  ["轉台本地數據雙倍至 60GB（至 2026/12/31）；轉台或學生上台可豁免每月行政費 HK$18", "Port-in local data doubled to 60GB (until 31 Dec 2026); port-in or student sign-up can waive HK$18 admin/month"],
  ["轉台送內地通話 10 分鐘；轉台可豁免每月行政費 HK$18", "Port-in includes 10 Mainland call minutes; port-in can waive HK$18 admin/month"],
  ["轉台可送 20,000 MyLink 積分（至 2026/09/30）；轉台可豁免每月行政費 HK$18", "Port-in may include 20,000 MyLink points (until 30 Sep 2026); port-in can waive HK$18 admin/month"],
  ["須由 3香港攜號轉台；轉台可豁免每月行政費 HK$18", "Must port in from 3HK; port-in can waive HK$18 admin/month"],
  ["轉台可雙倍本地數據至 60GB（至 2026/09/30）；轉台可豁免每月行政費 HK$18", "Port-in can double local data to 60GB (until 30 Sep 2026); port-in can waive HK$18 admin/month"],
  ["轉台可免第 4 個月月費（至 2026/09/30）；轉台可豁免每月行政費 HK$18", "Port-in can waive month 4 (until 30 Sep 2026); port-in can waive HK$18 admin/month"],
  ["轉台首兩月額外 15GB 大灣區數據；轉台可豁免每月行政費 HK$18", "Port-in extra 15GB GBA data in the first two months; port-in can waive HK$18 admin/month"],
  ["轉台或學生上台可豁免每月行政費 HK$18", "Port-in or student sign-up can waive HK$18 admin/month"],
  ["轉台可豁免每月行政費 HK$18", "Port-in can waive HK$18 admin/month"],
  ["豁免每月行政費 HK$18", "HK$18 admin/month waived"],
  ["每月行政費 HK$18，限時可豁免（至 2026/09/30）", "HK$18 admin/month, waiver available until 30 Sep 2026"],
  ["攜號轉台本地數據 60GB", "Port-in local data 60GB"],
  ["須由 3香港攜號轉台", "Must port in from 3HK"],
  ["20GB 加額外 10GB，合共 30GB", "20GB plus extra 10GB, 30GB total"],
  ["疊優惠可再 +10GB 本地", "Stacking offers can add another 10GB local"],
  ["限時可疊每月 HK$27 折扣（至 2026/09/30，實付約 HK$71）", "Limited-time extra HK$27/month off (until 30 Sep 2026; about HK$71 payable)"],
  ["約 30GB（10+5+限時 15GB）", "About 30GB (10+5 plus limited-time 15GB)"],
  ["10GB 加額外數據，合共約 30GB", "10GB plus extra data, about 30GB total"],
  ["3GB 加額外 3GB，合共 6GB", "3GB plus extra 3GB, 6GB total"],
  ["50GB 基數及額外 50GB，合共 100GB", "50GB base plus extra 50GB, 100GB total"],
  ["100GB 基數及額外 100GB，合共 200GB", "100GB base plus extra 100GB, 200GB total"],
  ["其後速度 2Mbps，快過多數 1Mbps 計劃", "After-quota speed 2Mbps, faster than most 1Mbps plans"],
  ["其後速度最高 5Mbps", "After-quota speed up to 5Mbps"],
  ["3HK 客專屬價", "3HK customer exclusive price"],
  ["限時計劃至 2026/09/30", "Limited-time plan until 30 Sep 2026"],
  ["送任用社交及娛樂數據組合（原價 HK$38／月）", "Includes unlimited social and entertainment data pack (was HK$38/month)"],
  ["青年可以 HK$9／月加購任用社交及娛樂數據組合（原價 HK$38）", "Youth can add unlimited social and entertainment data for HK$9/month (was HK$38)"],
  ["可 HK$9／月加購移動安全管家－進階版", "Add Mobile Security Manager Advanced for HK$9/month"],
  ["可 HK$9／月加購一卡多號", "Add multi-number SIM for HK$9/month"],
  ["免費移動安全管家－基礎版", "Free Mobile Security Manager Basic"],
  ["免費來電攔截服務（經 MyLink App 申請）", "Free call blocking via MyLink App"],
  ["可疊 HK$10 月費折扣", "Can stack a HK$10 monthly discount"],
  ["轉台免 6 個月月費（第 3/6/9/12/15/18 個月，至 2026/09/30）", "Port-in waives 6 months (months 3/6/9/12/15/18, until 30 Sep 2026)"],
  ["36 個月合約含 6 個月免月費", "36-month contract includes 6 free months"],
  ["最多 3 張副卡（純數據 HK$40／語音及數據 HK$80）", "Up to 3 extra SIMs (data-only HK$40 / voice+data HK$80)"],
  ["最多 3 張副卡", "Up to 3 extra SIMs"],
  ["可加副卡", "Optional extra SIMs"],
  ["200/300GB 副卡半價（至 2026/09/30，首月正價）", "200/300GB extra SIMs half-price until 30 Sep 2026 (first month full price)"],
  ["送 20,000 MyLink 積分", "Includes 20,000 MyLink points"],
  ["購機券 HK$1,200", "HK$1,200 handset coupon"],
  ["購機券 HK$600", "HK$600 handset coupon"],
  ["購機券 HK$300", "HK$300 handset coupon"],
  ["送 HK$150 單次旅遊保險券（至 2026/12/31，有效 180 日）", "HK$150 one-time travel insurance voucher (until 31 Dec 2026, valid 180 days)"],
  ["送中國內地通話 100 分鐘（至 2026/12/31）", "Includes 100 Mainland call minutes (until 31 Dec 2026)"],
  ["送中國內地通話 200 分鐘", "Includes 200 Mainland call minutes"],
  ["額外 5GB 中澳數據至 2026/12/31", "Extra 5GB Mainland & Macao data until 31 Dec 2026"],
  ["三地免費接聽", "Free incoming calls in three regions"],
  ["須出示年齡證明文件", "Proof of age required"],
  ["須年滿 65 歲並持綜援或長者生活津貼證明", "Must be 65+ with CSSA or Old Age Living Allowance proof"],
  ["18 至 29 歲適用", "Ages 18–29"],
  ["本地 35GB 加 15GB 大灣區數據", "35GB local plus 15GB Greater Bay Area data"],
  ["中澳 3GB；送內地通話 50 分鐘（至 2026/12/31）", "3GB Mainland & Macao; 50 Mainland call minutes (until 31 Dec 2026)"],
  ["中澳 1GB；限時額外 5GB 中澳（至 2026/12/31）", "1GB Mainland & Macao plus limited-time extra 5GB (until 31 Dec 2026)"],
  ["中澳 1+1GB；疊優惠再 +1GB（至 2026/09/30）", "Mainland & Macao 1+1GB; stacking offers add another 1GB until 30 Sep 2026"],
  ["接聽中港澳免費；撥打中港澳 HK$0.65／分鐘", "Free incoming HK/Mainland/Macao calls; outbound HK$0.65/min"],
  ["超出後 $0.5／MB（每日上限 HK$48）", "Thereafter $0.5/MB (daily cap HK$48)"],
  ["中澳 2GB；中港澳接聽免費，撥打 HK$0.65／分鐘", "2GB Mainland & Macao; free incoming HK/Mainland/Macao, outbound HK$0.65/min"],
  ["中澳 3+3GB", "Mainland & Macao 3+3GB"],
  ["中澳 4+2GB", "Mainland & Macao 4+2GB"],
  ["中澳 6+6GB", "Mainland & Macao 6+6GB"],
  ["中澳 2+2GB（轉台）", "Mainland & Macao 2+2GB (port-in)"],
  ["中澳 2+1+2GB（轉台）", "Mainland & Macao 2+1+2GB (port-in)"],
  ["中澳 2+2+2GB（轉台）", "Mainland & Macao 2+2+2GB (port-in)"],
  ["中港共用 10+5GB", "10+5GB shared HK–Mainland"],
  ["中港共用 20GB", "20GB shared HK–Mainland"],
  ["中港共用 50GB", "50GB shared HK–Mainland"],
  ["大灣區 15GB", "15GB Greater Bay Area data"],
  ["10GB 加 5GB 中港兩地共用", "10GB plus 5GB shared HK–Mainland"],
  ["20GB 中港兩地共用", "20GB shared HK–Mainland"],
  ["50GB 中港兩地共用", "50GB shared HK–Mainland"],
  ["每月 15GB 大灣區數據", "15GB Greater Bay Area data/month"],
  ["本地通話無限；包 100 分鐘中港通話", "Unlimited local calls; 100 HK–Mainland minutes included"],
  ["本地通話無限；中港首 200 分鐘免費", "Unlimited local calls; first 200 HK–Mainland minutes free"],
  ["本地通話無限；中／港／澳免費任聽；中／澳通話包 100 分鐘", "Unlimited local calls; free incoming in HK/Mainland/Macao; 100 Mainland/Macao minutes"],
  ["s/ash 每一實際使用人只可辦理一個計劃。實際月費、數據用量及轉台條款以電訊商確認為準。", "Each actual s/ash user may hold one plan. Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["須年滿 65 歲並持綜援或長者生活津貼證明。實際月費、數據用量及申請資格以電訊商確認為準。", "Must be 65+ with CSSA or Old Age Living Allowance proof. Monthly fee, data and eligibility are confirmed by the carrier."],
  ["須符合 18 至 29 歲或教職員資格。實際月費、數據用量及申請資格以電訊商確認為準。", "Must be 18–29 or teaching staff. Monthly fee, data and eligibility are confirmed by the carrier."],
  ["須核對現用 3香港客戶身份，只適用於由 3香港轉台之客戶。實際月費、數據用量及轉台條款以電訊商確認為準。", "Must verify current 3HK customer status; 3HK port-in only. Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["優惠代碼互斥；部分至 2026/09/30。實際月費、數據用量及轉台條款以電訊商確認為準。", "Promo codes cannot be combined; some end 30 Sep 2026. Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["限時計劃至 2026/09/30。實際月費、數據用量及轉台條款以電訊商確認為準。", "Limited-time plan until 30 Sep 2026. Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["轉台免 6 個月月費至 2026/09/30。實際月費、數據用量及轉台條款以電訊商確認為準。", "Port-in 6 free months until 30 Sep 2026. Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["實際月費、數據用量及轉台條款以電訊商確認為準。", "Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["須年滿 60 歲。實際月費、數據用量及申請資格以電訊商確認為準。", "Must be 60 or above. Monthly fee, data and eligibility are confirmed by the carrier."],
  ["須年滿 65 歲並出示證明文件。實際月費、數據用量及申請資格以電訊商確認為準。", "Must be 65 or above with proof of age. Monthly fee, data and eligibility are confirmed by the carrier."],
  ["18 至 29 歲適用。實際月費、數據用量及申請資格以電訊商確認為準。", "Ages 18–29. Monthly fee, data and eligibility are confirmed by the carrier."],
  ["只適用於由 3香港轉台之客戶。實際月費、數據用量及轉台條款以電訊商確認為準。", "For customers porting in from 3HK only. Monthly fee, data and port-in terms are confirmed by the carrier."],
  ["s/ash 5G 30GB（24 個月）", "s/ash 5G 30GB (24 months)"],
  ["s/ash 5G 10GB（24 個月）", "s/ash 5G 10GB (24 months)"],
  ["s/ash 5G 50GB（24 個月）", "s/ash 5G 50GB (24 months)"],
  ["s/ash 5G 100GB（24 個月）", "s/ash 5G 100GB (24 months)"],
  ["s/ash 5G 30GB", "s/ash 5G 30GB"],
  ["s/ash 5G 10GB", "s/ash 5G 10GB"],
  ["s/ash 5G 50GB", "s/ash 5G 50GB"],
  ["s/ash 5G 100GB", "s/ash 5G 100GB"],
  ["5G 體驗 20GB（24 個月）", "5G trial 20GB (24 months)"],
  ["5G 體驗 10GB（3HK 客專享，24 個月）", "5G trial 10GB (3HK exclusive, 24 months)"],
  ["5G 體驗 20GB", "5G trial 20GB"],
  ["5G 體驗 10GB（3香港轉台）", "5G trial 10GB (3HK port-in)"],
  ["移動 42Mbps 10+5GB（24 個月）", "CMHK 42Mbps 10+5GB (24 months)"],
  ["低用量 移動 42Mbps 3GB（24 個月）", "Light-use CMHK 42Mbps 3GB (24 months)"],
  ["低用量 移動 21Mbps 3+3GB（24 個月）", "Light-use CMHK 21Mbps 3+3GB (24 months)"],
  ["關愛長者 21Mbps 6GB（24 個月）", "Elderly care 21Mbps 6GB (24 months)"],
  ["長者 5G 10GB（24 個月）", "Elderly 5G 10GB (24 months)"],
  ["長者 5G 30GB（24 個月）", "Elderly 5G 30GB (24 months)"],
  ["長者 5G 10GB（中港 2 用，24 個月）", "Elderly 5G 10GB (HK–Mainland dual-use, 24 months)"],
  ["移動 42Mbps 10+5GB", "CMHK 42Mbps 10+5GB"],
  ["低用量 42Mbps 3GB", "Light-use 42Mbps 3GB"],
  ["低用量 21Mbps 3+3GB", "Light-use 21Mbps 3+3GB"],
  ["關愛長者 21Mbps 6GB", "Elderly care 21Mbps 6GB"],
  ["長者 5G 10GB", "Elderly 5G 10GB"],
  ["長者 5G 30GB", "Elderly 5G 30GB"],
  ["長者 5G 中港兩地", "Elderly 5G HK–Mainland"],
  ["5G 極致 50GB（24 個月）", "5G Ultimate 50GB (24 months)"],
  ["5G 極致 50GB（36 個月）", "5G Ultimate 50GB (36 months)"],
  ["5G 極致 100GB（24 個月）", "5G Ultimate 100GB (24 months)"],
  ["5G 極致 200GB（24 個月）", "5G Ultimate 200GB (24 months)"],
  ["5G 極致 100GB", "5G Ultimate 100GB"],
  ["5G 極致 200GB", "5G Ultimate 200GB"],
  ["5G 一咭兩地 20GB（18–29 青年及教職員，24 個月）", "5G two-places 20GB (ages 18–29 / teaching staff, 24 months)"],
  ["5G 一咭兩地 50GB（24 個月）", "5G two-places 50GB (24 months)"],
  ["5G 大灣區 15GB 新春（24 個月）", "5G Greater Bay Area 15GB CNY (24 months)"],
  ["一咭兩地 20GB 青年", "Two-places 20GB youth"],
  ["一咭兩地 50GB", "Two-places 50GB"],
  ["大灣區 15GB 新春", "Greater Bay Area 15GB CNY"],
  ["4G（最高 42Mbps）", "4G (up to 42Mbps)"],
  ["4G（最高 21Mbps）", "4G (up to 21Mbps)"],
  ["一次過支付 HK$2,800（平均每月約 HK$233.3）", "Pay HK$2,800 upfront (about HK$233.3/month)"],
  ["一次過付款連 myTV Gold", "one-off payment with myTV Gold"],
  ["一次過付款連影視／路由器", "one-off payment with streaming/router"],
  ["加購可享首 24 個月額外免費 1000M 副線", "Add-on: extra free 1000M line for the first 24 months"],
  ["首 36 個月額外免費 1000M 副線", "Extra free 1000M line for the first 36 months"],
  ["可選擇延遲服務生效日（最長 365 日）", "Defer service start up to 365 days"],
  ["攜號轉台本地數據雙倍；另加 HK$18 行政費", "Port-in local data doubled; plus HK$18 admin fee"],
  ["攜號轉台簽訂 36 個月合約或可享月費回贈", "Port-in on a 36-month contract may include a fee rebate"],
  ["攜號轉台本地數據雙倍", "Port-in local data doubled"],
  ["攜號轉台適用", "Port-in eligible"],
  ["轉台或可享 HK$100 回贈（視申請時優惠而定）", "Port-in may include a HK$100 rebate (confirm at application)"],
  ["轉台或附禮品（視申請時優惠而定）", "Port-in may include a gift (confirm at application)"],
  ["新客戶可加每月 HK$98 升級 2500M", "New customers can add HK$98/month to upgrade to 2500M"],
  ["新一代 iPhone 早鳥專屬優惠", "Early-bird offer for the latest iPhone"],
  ["不鎖定地區，可隨時搬遷", "No area lock; move anytime"],
  ["專人上門測試訊號", "On-site signal test"],
  ["豁免隧道費（原價每月 HK$28）", "Tunnel fee waived (was HK$28/month)"],
  ["豁免安裝費（原價 HK$680）", "Installation waived (was HK$680)"],
  ["豁免安裝費，免拉線，隨插即用", "Installation waived; no cabling, plug and play"],
  ["豁免安裝費，無需拉線", "Installation waived, no cabling"],
  ["豁免安裝費", "Installation waived"],
  ["須繳付 HK$780 安裝費", "Installation fee HK$780"],
  ["豁免搬遷費", "Relocation fee waived"],
  ["搬遷費津貼 HK$1,000", "HK$1,000 relocation subsidy"],
  ["免拉線，隨插即用，路由器隨計劃提供", "No cabling, plug and play; router included"],
  ["免拉線，隨插即用", "No cabling, plug and play"],
  ["無需室內拉線，路由器隨計劃提供", "No in-home cabling; router included"],
  ["無需室內拉線，即插即用", "No in-home cabling; plug and play"],
  ["無需室內拉線", "No in-home cabling"],
  ["須繳付安裝費 HK$680", "Installation HK$680"],
  ["首次需繳付 HK$680 安裝費", "First payment: HK$680 installation fee"],
  ["首次安裝須繳付 HK$480", "First install HK$480"],
  ["須另行繳付安裝費", "Installation fee extra"],
  ["安裝費 HK$180", "Installation HK$180"],
  ["標準企業安裝", "Standard business installation"],
  ["須另行核對", "To be confirmed separately"],
  ["計劃包含指定路由器", "Designated router included"],
  ["包 Wi-Fi 7 二合一路由器", "Includes 2-in-1 Wi-Fi 7 router"],
  ["包 Linksys EA9350 Wi-Fi 6 路由器", "Includes a Linksys EA9350 Wi-Fi 6 router"],
  ["包 Wi-Fi 7 路由器", "Includes Wi-Fi 7 router"],
  ["包指定 Wi-Fi 路由器", "Includes designated Wi-Fi router"],
  ["租借 Wi-Fi 7 路由器", "Wi-Fi 7 router on loan"],
  ["可加購家庭副卡", "Optional extra family SIMs"],
  ["可同時申請 csl 流動服務", "Can apply for csl mobile at the same time"],
  ["第 13 至第 15 個月免費", "Months 13–15 free"],
  ["首 3 個月免月費", "First 3 months free"],
  ["豁免第一個月月費", "First month waived"],
  ["50GB 基數及額外 50GB 優惠，合共 100GB；18 至 29 歲適用", "50GB base plus extra 50GB offer, 100GB total; for ages 18–29"],
  ["100GB 基數及額外 100GB 優惠，合共 200GB；18 至 29 歲適用", "100GB base plus extra 100GB offer, 200GB total; for ages 18–29"],
  ["學生或年青人專題，須符合資格", "Student or youth exclusive, must meet eligibility"],
  ["適用於 18 至 29 歲客戶。", "For ages 18–29."],
  ["適用於 18 至 29 歲", "For ages 18–29"],
  ["14 日冷靜期", "14-day cooling-off"],
  ["7 日免費試用", "7-day free trial"],
  ["7 日冷靜期", "7-day cooling-off"],
  ["內地副號", "Mainland secondary number"],
  ["免租／買機優惠", "Handset rental/purchase offer"],
  ["免還機", "Keep the router"],
  ["企業支援熱線", "Business support hotline"],
  ["企業支援", "Business support"],
  ["固定 IP 可選", "Optional fixed IP"],
  ["固定 IP", "Fixed IP"],
  ["家居／寬頻電話服務", "Home / broadband phone"],
  ["家居固網電話", "Home landline"],
  ["家居電話服務", "Home phone"],
  ["myTV SUPER 解碼器", "myTV SUPER decoder"],
  ["1GB 電郵儲存量", "1GB email storage"],
  ["200GB 本地高速數據", "200GB local high-speed data"],
  ["每月 10 分鐘中國內地及澳門通話", "10 Mainland & Macao minutes/month"],
  ["每月 12GB 中國及澳門數據", "12GB China & Macao data/month"],
  ["每月 1GB 中國內地及澳門數據", "1GB Mainland & Macao data/month"],
  ["每月 1GB 中國內地數據", "1GB Mainland data/month"],
  ["每月 2GB 中國內地及澳門數據", "2GB Mainland & Macao data/month"],
  ["每月 2–4GB 中澳數據", "2–4GB Mainland & Macao data/month"],
  ["合約期內每月 3GB 中國內地及澳門", "Monthly 3GB Mainland China & Macau during contract period"],
  ["每月 3GB 中國內地及澳門數據", "3GB Mainland & Macao data/month"],
  ["每月 3GB 中國內地數據", "3GB Mainland data/month"],
  ["每月 3GB 中澳數據", "3GB Mainland & Macao data/month"],
  ["每月 4GB 中國內地及澳門數據", "4GB Mainland & Macao data/month"],
  ["每月 4GB 中國內地數據", "4GB Mainland data/month"],
  ["每月 4GB 中國及澳門數據", "4GB China & Macao data/month"],
  ["加送 2GB 大灣區數據", "Includes extra 2GB Greater Bay Area data"],
  ["每月 500MB 中國及澳門數據", "500MB China & Macao data/month"],
  ["每月 8GB 中國內地數據", "8GB Mainland data/month"],
  ["每月 8GB 中國及澳門數據", "8GB China & Macao data/month"],
  ["無限本地數據（42Mbps）", "Unlimited local data (42Mbps)"],
  ["本地無限分鐘", "Unlimited local minutes"],
  ["本地通話無限", "Unlimited local calls"],
  ["無限本地通話", "Unlimited local calls"],
  ["本地 3,000 分鐘", "3,000 local minutes"],
  ["本地 3000 分鐘；其後 $1／分鐘", "Local 3,000 minutes; $1/minute thereafter"],
  ["本地 3000 分鐘", "3,000 local minutes"],
  ["42Mbps 無限任用", "Unlimited at 42Mbps"],
  ["4.5G 42Mbps 無限任用（24 個月）", "4.5G unlimited at 42Mbps (24 months)"],
  ["4.5G 首 10GB（24 個月）", "4.5G first 10GB (24 months)"],
  ["4.5G 首 14GB（24 個月）", "4.5G first 14GB (24 months)"],
  ["4.5G 10GB（24 個月）", "4.5G 10GB (24 months)"],
  ["4.5G 10GB（30 個月）", "4.5G 10GB (30 months)"],
  ["4.5G 20GB（24 個月）", "4.5G 20GB (24 months)"],
  ["5G 30GB 本地（含每月 3GB 中國內地及澳門）", "5G 30GB Local (incl. monthly 3GB Mainland China & Macau)"],
  ["5G 30GB 三地共用（24 個月）", "5G 30GB shared across 3 regions (24 months)"],
  ["5G 30GB 連手機券（36 個月）", "5G 30GB with handset coupon (36 months)"],
  ["5G 30GB 青年計劃（36 個月）", "5G 30GB youth plan (36 months)"],
  ["5G 60GB 青年計劃（36 個月）", "5G 60GB youth plan (36 months)"],
  ["5G 50GB 中港共用（24 個月）", "5G 50GB HK–Mainland shared (24 months)"],
  ["5G 70GB 三地共用（30 個月）", "5G 70GB shared across 3 regions (30 months)"],
  ["5G 70GB 中港澳共享", "5G 70GB HK–Mainland–Macao shared"],
  ["5G 本地服務計劃（30GB）", "5G local service plan (30GB)"],
  ["5G 100GB 超值計劃", "5G 100GB value plan"],
  ["5G 年青人計劃（100GB，18–29 歲）", "5G youth plan (100GB, ages 18–29)"],
  ["5G 年青人計劃（200GB，18–29 歲）", "5G youth plan (200GB, ages 18–29)"],
  ["5G 100GB 任用（24 個月）", "5G 100GB unlimited (24 months)"],
  ["5G 100GB（24 個月）", "5G 100GB (24 months)"],
  ["5G 100GB（30 個月）", "5G 100GB (30 months)"],
  ["5G 200GB 網上限定", "5G 200GB online exclusive"],
  ["5G 200GB（30 個月）", "5G 200GB (30 months)"],
  ["5G 30GB（28 個月）", "5G 30GB (28 months)"],
  ["5G 60GB（30 個月）", "5G 60GB (30 months)"],
  ["5G 家居 350GB（24 個月，租借 Wi-Fi 7）", "5G home 350GB (24 months, Wi-Fi 7 router on loan)"],
  ["5G 家居 350GB（30 個月，租借 Wi-Fi 7）", "5G home 350GB (30 months, Wi-Fi 7 router on loan)"],
  ["5G 家居 350GB（48 個月，租借 Wi-Fi 7）", "5G home 350GB (48 months, Wi-Fi 7 router on loan)"],
  ["5G 家居 500GB（24 個月，租借 Wi-Fi 7）", "5G home 500GB (24 months, Wi-Fi 7 router on loan)"],
  ["5G 家居 500GB（30 個月，租借 Wi-Fi 7）", "5G home 500GB (30 months, Wi-Fi 7 router on loan)"],
  ["5G 家居 500GB（48 個月，租借 Wi-Fi 7）", "5G home 500GB (48 months, Wi-Fi 7 router on loan)"],
  ["5G 家居 Wi-Fi 6 300GB（30 個月）", "5G home Wi-Fi 6 300GB (30 months)"],
  ["5G 家居 Wi-Fi 6 300GB（48 個月）", "5G home Wi-Fi 6 300GB (48 months)"],
  ["5G 家居 Wi-Fi 6 500GB（48 個月）", "5G home Wi-Fi 6 500GB (48 months)"],
  ["5G 家居 Wi-Fi 6 真無限（30 個月）", "5G home Wi-Fi 6 truly unlimited (30 months)"],
  ["5G 家居 Wi-Fi 7 真無限（30 個月）", "5G home Wi-Fi 7 truly unlimited (30 months)"],
  ["5G 家居 Wi-Fi 7 真無限（48 個月）", "5G home Wi-Fi 7 truly unlimited (48 months)"],
  ["5G 家居寬頻連路由器", "5G home broadband with router"],
  ["5G 家居寬頻包 Wi-Fi 7 路由器", "5G home broadband with Wi-Fi 7 router"],
  ["5G 家居寬頻包 Wi-Fi 6 路由器", "5G home broadband with Wi-Fi 6 router"],
  ["5G 家居寬頻 Wi-Fi 6", "5G home broadband Wi-Fi 6"],
  ["5G 家居寬頻", "5G home broadband"],
  ["5G 無線（Wi-Fi 7）", "5G wireless (Wi-Fi 7)"],
  ["5G 無線（Wi-Fi 6）", "5G wireless (Wi-Fi 6)"],
  ["5G 無線", "5G wireless"],
  ["5G 真無限", "5G truly unlimited"],
  ["須預繳 HK$3,600", "Prepaid HK$3,600"],
  ["須預繳 HK$200", "Prepaid HK$200"],
  ["須預繳 HK$300", "Prepaid HK$300"],
  ["連遊戲路由器及娛樂組合", "with gaming router and entertainment bundle"],
  ["連 Wi-Fi 7 及娛樂組合", "with Wi-Fi 7 and entertainment bundle"],
  ["連 Mesh Wi-Fi 7", "with Mesh Wi-Fi 7"],
  ["連 Wi-Fi 6 路由器", "with Wi-Fi 6 router"],
  ["連 Wi-Fi 7 路由器", "with Wi-Fi 7 router"],
  ["2500M 光纖連家居電話（24 個月＋Wi-Fi 7）", "2500M fibre with home phone (24 months + Wi-Fi 7)"],
  ["5000M 光纖連家居電話（24 個月）", "5000M fibre with home phone (24 months)"],
  ["2.5Gbps 高速上網連 Wi-Fi 7（12 個月）", "2.5Gbps high-speed internet with Wi-Fi 7 (12 months)"],
  ["1000M 基本月費計劃（12 個月）", "1000M basic monthly plan (12 months)"],
  ["1000M 家居寬頻（24 個月）", "1000M home broadband (24 months)"],
  ["1000M 家居寬頻計劃（24 個月）", "1000M home broadband plan (24 months)"],
  ["2500M GigaFast 寬頻（36 個月）", "2500M GigaFast broadband (36 months)"],
  ["指定屋苑專享", "Selected estates only"],
  ["送 HK$1,000 惠康超級市場及 Market Place 現金券（$50 × 20）", "HK$1,000 Wellcome and Market Place cash coupons ($50 × 20)"],
  ["適合指定屋苑、月費 $0 之 1000M 住戶", "For selected estates wanting 1000M at $0 monthly"],
  ["適合指定屋苑、需要 2500M 光纖及路由器之住戶", "For selected estates needing 2500M fibre and a router"],
  ["1000M 家居寬頻（36 個月）", "1000M home broadband (36 months)"],
  ["10000M 光纖入屋（24 個月）", "10000M FTTH (24 months)"],
  ["1000M 光纖入屋（48 個月）", "1000M FTTH (48 months)"],
  ["1000M 光纖入屋（36 個月）", "1000M FTTH (36 months)"],
  ["2500M 光纖入屋（36 個月）", "2500M FTTH (36 months)"],
  ["200M 光纖（36 個月）", "200M fibre (36 months)"],
  ["指定私人樓宇1000M光纖優惠", "Designated private-building 1000M fibre offer"],
  ["獨家私人樓宇 1000M 光纖＋Wi-Fi 6 路由器＋家居電話＋手提電話服務", "Exclusive private 1000M fibre + Wi-Fi 6 router + home phone + mobile phone service"],
  ["獨家私人樓宇 2500M 光纖＋Wi-Fi 7 路由器＋家居電話＋手提電話服務", "Exclusive private 2500M fibre + Wi-Fi 7 router + home phone + mobile phone service"],
  ["新居屋／簡約公屋 2000M（36 個月＋Wi-Fi 7）", "New HOS / Light Public Housing 2000M (36 months + Wi-Fi 7)"],
  ["公居屋 2500M 光纖（36 個月＋Wi-Fi 7 二合一）", "Public/HOS 2500M fibre (36 months + 2-in-1 Wi-Fi 7)"],
  ["公居屋 2500M 光纖（36 個月＋Wi-Fi 7）", "Public/HOS 2500M fibre (36 months + Wi-Fi 7)"],
  ["公居屋 1000M（39 個月＋Wi-Fi 6＋電話）", "Public/HOS 1000M (39 months + Wi-Fi 6 + phone)"],
  ["公居屋 1000M 光纖（36 個月＋路由器）", "Public/HOS 1000M fibre (36 months + router)"],
  ["公居屋 1000M 光纖（36 個月＋Wi-Fi 6）", "Public/HOS 1000M fibre (36 months + Wi-Fi 6)"],
  ["公居屋 1000M 光纖（36 個月）", "Public/HOS 1000M fibre (36 months)"],
  ["公居屋 1000M 光纖（48 個月）", "Public/HOS 1000M fibre (48 months)"],
  ["公居屋 2000M 光纖（24 個月）", "Public/HOS 2000M fibre (24 months)"],
  ["公居屋 2000M 光纖（36 個月）", "Public/HOS 2000M fibre (36 months)"],
  ["公居屋 2000M（36 個月）", "Public/HOS 2000M (36 months)"],
  ["公居屋轉台 1000M（36 個月）", "Public/HOS port-in 1000M (36 months)"],
  ["私人樓宇 1000M（39 個月＋Wi-Fi 6＋電話）", "Private 1000M (39 months + Wi-Fi 6 + phone)"],
  ["私人樓宇 1000M 光纖（24 個月＋Wi-Fi 6＋電話）", "Private 1000M fibre (24 months + Wi-Fi 6 + phone)"],
  ["私人樓宇 1000M 光纖（36 個月＋家居電話）", "Private 1000M fibre (36 months + home phone)"],
  ["私人樓宇 1000M 光纖（36 個月＋路由器）", "Private 1000M fibre (36 months + router)"],
  ["私人樓宇 1000M 光纖（36 個月＋Wi-Fi 6）", "Private 1000M fibre (36 months + Wi-Fi 6)"],
  ["私人樓宇 1000M 光纖（36 個月）", "Private 1000M fibre (36 months)"],
  ["私人樓宇 2000M 光纖（36 個月）", "Private 2000M fibre (36 months)"],
  ["私人樓宇 2000M（36 個月）", "Private 2000M (36 months)"],
  ["私人樓宇 2500M 光纖（36 個月＋Wi-Fi 7）", "Private 2500M fibre (36 months + Wi-Fi 7)"],
  ["特選村屋 2000M 連 Wi-Fi 7（24 個月）", "Selected village 2000M with Wi-Fi 7 (24 months)"],
  ["特選村屋 2000M 光纖（24 個月）", "Selected village 2000M fibre (24 months)"],
  ["特選村屋 2500M 光纖（24 個月）", "Selected village 2500M fibre (24 months)"],
  ["村屋／唐樓 1000M 光纖（36 個月）", "Village/tong lau 1000M fibre (36 months)"],
  ["村屋 1000M 光纖計劃（24 個月）", "Village 1000M fibre plan (24 months)"],
  ["村屋 1000M 光纖計劃（36 個月）", "Village 1000M fibre plan (36 months)"],
  ["村屋／唐樓 2500M 光纖（36 個月）", "Village/tong lau 2500M fibre (36 months)"],
  ["村屋 2500M 光纖計劃（24 個月）", "Village 2500M fibre plan (24 months)"],
  ["村屋 2500M 光纖計劃（36 個月）", "Village 2500M fibre plan (36 months)"],
  ["村屋 2500M 升級旗艦（27 個月＋Wi-Fi 7）", "Village 2500M flagship upgrade (27 months + Wi-Fi 7)"],
  ["村屋 2G 連 Wi-Fi 6＋電話（30 個月）", "Village 2G with Wi-Fi 6 + phone (30 months)"],
  ["村屋 2G 連 Wi-Fi 7＋電話（30 個月）", "Village 2G with Wi-Fi 7 + phone (30 months)"],
  ["村屋 2G 連電視娛樂（30 個月）", "Village 2G with TV entertainment (30 months)"],
  ["村屋 1G 連路由器＋電話（30 個月）", "Village 1G with router + phone (30 months)"],
  ["村屋 1G 連電話（24 個月）", "Village 1G with phone (24 months)"],
  ["村屋 2G 純寬頻（24 個月）", "Village 2G broadband only (24 months)"],
  ["村屋 1000M 光纖（27 個月）", "Village 1000M fibre (27 months)"],
  ["村屋 200M 光纖（27 個月）", "Village 200M fibre (27 months)"],
  ["村屋 500M 光纖（27 個月）", "Village 500M fibre (27 months)"],
  ["留學生 1000M（12 個月）", "Student 1000M (12 months)"],
  ["商業 10000M", "Business 10000M"],
  ["商業 1000M", "Business 1000M"],
  ["商業 2500M", "Business 2500M"],
  ["商業 5000M", "Business 5000M"],
  ["光纖專線／商用", "Leased line / business"],
  ["光纖入屋", "FTTH"],
  ["光纖寬頻", "Fibre broadband"],
  ["商業寬頻", "Business fibre"],
  ["手機月費", "Mobile"],
  ["不適用", "N/A"],
  ["視計劃而定", "Depends on plan"],
  ["香港寬頻", "HKBN"],
  ["網上行", "Netvigator"],
  ["電訊盈科", "HKT"],
  ["中國移動香港", "CMHK"],
  ["數碼通", "SmarTone"],
  ["3香港", "3HK"],
  ["有線寬頻", "i-Cable"],
  ["公屋", "public housing"],
  ["居屋", "HOS"],
  ["私人樓", "private"],
  ["村屋", "village house"],
];

const BEST_FOR: [string, string][] = [
  ["適合符合學生或年青人資格之用戶", "Suitable for users meeting student or youth eligibility"],
  ["適合 18 至 29 歲、需要 5G 30GB 之用戶", "For ages 18–29 who need 5G 30GB"],
  ["適合 18 至 29 歲、需要 5G 60GB 之用戶", "For ages 18–29 who need 5G 60GB"],
  ["適合 18 至 29 歲、需要 5G 100GB 之用戶", "For ages 18–29 who need 5G 100GB"],
  ["適合 18 至 29 歲、需要 5G 200GB 之用戶", "For ages 18–29 who need 5G 200GB"],
  ["適合一星期多次往返內地或澳門之用戶", "For people who travel to the Mainland or Macao several times a week"],
  ["適合一次過付款、需要 myTV Gold 之住戶", "For households paying upfront who want myTV Gold"],
  ["適合一次過付款、需要影視會籍或路由器之住戶", "For households paying upfront who want a streaming membership or router"],
  ["適合中型辦公室", "For mid-size offices"],
  ["適合中小型商戶", "For SMEs"],
  ["適合中等 4.5G 數據用量之用戶", "For moderate 4.5G data use"],
  ["適合中等數據用量，以及使用即時通訊與串流應用之用戶", "For moderate data use plus messaging and streaming"],
  ["適合以即時通訊為主、較少串流之用戶", "For mostly messaging, little streaming"],
  ["適合公屋、居屋或私人樓宇、需要 1000M 光纖之住戶", "For public housing, HOS or private buildings that need 1000M fibre"],
  ["適合公屋、居屋或私人住宅、需要 1000M 光纖之住戶", "For public housing, HOS or private homes that need 1000M fibre"],
  ["適合公屋、居屋或私人住宅之入門 1000M 住戶", "For entry-level 1000M in public housing, HOS or private homes"],
  ["適合公屋、居屋或私人住宅，需要 10000M 光纖之住戶", "For public housing, HOS or private homes that need 10000M fibre"],
  ["適合公屋、居屋或私人住宅，需要 1000M 光纖及路由器之住戶", "For public housing, HOS or private homes that need 1000M fibre and a router"],
  ["適合指定新入伙屋苑、需要 1000M 光纖及影視會籍之住戶", "For selected new-move-in estates that need 1000M fibre and a streaming membership"],
  ["適合指定新入伙屋苑、需要 2500M 光纖、家居電話及影視會籍之住戶", "For selected new-move-in estates that need 2500M fibre, a home phone and a streaming membership"],
  ["適合指定新入伙屋苑、接受 36 個月合約及影視會籍之住戶", "For selected new-move-in estates on a 36-month contract with a streaming membership"],
  ["適合指定新入伙屋苑、需要雙線 1000M 光纖之住戶", "For selected new-move-in estates that need dual 1000M fibre"],
  ["適合公屋、居屋或私人住宅，需要 5000M 光纖及家居電話之住戶", "For public housing, HOS or private homes that need 5000M fibre and a home phone"],
  ["適合公屋或居屋、接受 36 個月合約之住戶", "For public or HOS homes on a 36-month contract"],
  ["適合公屋或居屋、接受較短合約之住戶", "For public or HOS homes on a shorter contract"],
  ["適合公屋或居屋、需要 1000M 光纖之住戶", "For public or HOS homes that need 1000M fibre"],
  ["適合公屋或居屋、需要 2000M 光纖之住戶", "For public or HOS homes that need 2000M fibre"],
  ["適合公屋或居屋、需要 2500M 光纖之住戶", "For public or HOS homes that need 2500M fibre"],
  ["適合公屋或居屋、需要路由器及家居電話之住戶", "For public or HOS homes that need a router and home phone"],
  ["適合公屋或居屋轉台、需要 1000M 光纖之住戶", "For public or HOS port-in that need 1000M fibre"],
  ["適合多樓層辦公室", "For multi-floor offices"],
  ["適合多部電腦同時使用之寫字樓", "For offices with many PCs in use at once"],
  ["適合大型辦公室", "For large offices"],
  ["適合店舖或小型寫字樓", "For shops or small offices"],
  ["適合指定村屋、需要 1000M 光纖之住戶", "For selected village houses that need 1000M fibre"],
  ["適合指定村屋、需要 200M 光纖之住戶", "For selected village houses that need 200M fibre"],
  ["適合指定村屋、需要 500M 光纖之住戶", "For selected village houses that need 500M fibre"],
  ["適合指定村屋、需要升級至 2500M 及 Wi-Fi 7 之住戶", "For selected village houses that need an upgrade to 2500M and Wi-Fi 7"],
  ["適合指定獨家私人樓宇、需要 2500M 光纖及家居電話之住戶", "For selected exclusive private buildings that need 2500M fibre and a home phone"],
  ["適合接受 12 個月合約及自選禮遇之住戶", "For a 12-month contract with a choice of extras"],
  ["適合需要本地 5G 100GB 之用戶", "For local 5G 100GB"],
  ["適合需要本地 5G 之用戶", "For local 5G use"],
  ["適合新入伙居屋或簡約公屋住戶", "For new HOS or Light Public Housing move-ins"],
  ["適合日常 5G 用量，以及不時前往內地或澳門之用戶", "For everyday 5G plus occasional Mainland or Macao travel"],
  ["適合村屋、需要 1G 光纖及電話之住戶", "For village houses that need 1G fibre and a phone"],
  ["適合村屋、需要 1000M 光纖及 24 個月合約之住戶", "For village houses that need 1000M fibre on a 24-month contract"],
  ["適合村屋、需要 1000M 光纖及 36 個月合約之住戶", "For village houses that need 1000M fibre on a 36-month contract"],
  ["適合村屋、需要 2500M 光纖及 24 個月合約之住戶", "For village houses that need 2500M fibre on a 24-month contract"],
  ["適合村屋、需要 2500M 光纖及 36 個月合約之住戶", "For village houses that need 2500M fibre on a 36-month contract"],
  ["適合村屋、需要 2G 光纖之住戶", "For village houses that need 2G fibre"],
  ["適合村屋、需要 Wi-Fi 6 之住戶", "For village houses that need Wi-Fi 6"],
  ["適合村屋、需要 Wi-Fi 7 之住戶", "For village houses that need Wi-Fi 7"],
  ["適合村屋、需要影視娛樂之住戶", "For village houses that want TV entertainment"],
  ["適合村屋、需要路由器之住戶", "For village houses that need a router"],
  ["適合村屋或唐樓、需要 1000M 光纖之住戶", "For village houses or tong lau that need 1000M fibre"],
  ["適合村屋或唐樓、需要 2500M 光纖之住戶", "For village houses or tong lau that need 2500M fibre"],
  ["適合沒有家居寬頻、主要依靠手機熱點之用戶", "For people without home broadband who mainly use a phone hotspot"],
  ["適合流動數據用量中等之用戶", "For moderate mobile data use"],
  ["適合特選村屋、需要 2000M 光纖之住戶", "For selected village houses that need 2000M fibre"],
  ["適合特選村屋、需要 2000M 光纖及 Wi-Fi 7 之住戶", "For selected village houses that need 2000M fibre and Wi-Fi 7"],
  ["適合特選村屋、需要 2500M 光纖之住戶", "For selected village houses that need 2500M fibre"],
  ["適合現有 csl 或網上行客戶，需要 Wi-Fi 6 路由器之住戶", "For existing csl or Netvigator customers who need a Wi-Fi 6 router"],
  ["適合現有 csl 或網上行客戶，需要 Wi-Fi 7 路由器之住戶", "For existing csl or Netvigator customers who need a Wi-Fi 7 router"],
  ["適合現有 csl 或網上行客戶", "For existing csl or Netvigator customers"],
  ["適合留學生短約之住戶", "For short student contracts"],
  ["適合私人屋苑、需要 1000M 光纖之住戶", "For private estates that need 1000M fibre"],
  ["適合私人屋苑、需要 2000M 光纖之住戶", "For private estates that need 2000M fibre"],
  ["適合私人屋苑、需要 2500M 光纖之住戶", "For private estates that need 2500M fibre"],
  ["適合私人屋苑轉台、需要 1000M 光纖之住戶", "For private estate port-in that need 1000M fibre"],
  ["適合私人樓宇、可升級 2500M 之住戶", "For private buildings that can upgrade to 2500M"],
  ["適合私人樓宇、需要 1000M 光纖之住戶", "For private buildings that need 1000M fibre"],
  ["適合私人樓宇、需要 1000M 光纖及家居電話之住戶", "For private buildings that need 1000M fibre and a home phone"],
  ["適合私人樓宇、需要 2000M 光纖之住戶", "For private buildings that need 2000M fibre"],
  ["適合私人樓宇、需要 Wi-Fi 6 及家居電話之住戶", "For private buildings that need Wi-Fi 6 and a home phone"],
  ["適合租住單位、接受 24 個月合約之住戶", "For renters on a 24-month contract"],
  ["適合經常往返中港澳之用戶", "For frequent HK–Mainland–Macao travel"],
  ["適合經常往返內地，以及需要澳門數據之用戶", "For frequent Mainland travel plus Macao data"],
  ["適合經常連海外總部之企業", "For businesses that often connect to an overseas HQ"],
  ["適合較大單位、需要全屋 Mesh 覆蓋之住戶", "For larger flats that need whole-home Mesh"],
  ["適合較高本地數據用量之用戶", "For higher local data use"],
  ["適合輕量上網、攜號轉台之用戶", "For light use and number port-in"],
  ["適合輕量上網、需要無限本地通話之用戶", "For light use with unlimited local calls"],
  ["適合輕量上網、需要無限通話之用戶", "For light use with unlimited calls"],
  ["適合輕量上網、需要 s/ash 5G 之用戶", "For light use on s/ash 5G"],
  ["適合需要 s/ash 5G 30GB，以及轉台加數據之用戶", "For s/ash 5G 30GB plus extra data on port-in"],
  ["適合需要 5G 體驗計劃 30GB 之用戶", "For a 5G trial plan with 30GB"],
  ["適合由 3香港轉台、需要 5G 10GB 之用戶", "For 3HK port-in customers who need 5G 10GB"],
  ["適合中等 4G 數據用量之用戶", "For moderate 4G data use"],
  ["適合低用量、需要 42Mbps 之用戶", "For light use at 42Mbps"],
  ["適合低用量、需要 21Mbps 之用戶", "For light use at 21Mbps"],
  ["適合 65 歲或以上、需要入門數據之用戶", "For age 65+ who need entry-level data"],
  ["適合 60 歲或以上、需要 5G 10GB 之用戶", "For age 60+ who need 5G 10GB"],
  ["適合 60 歲或以上、需要 5G 30GB 之用戶", "For age 60+ who need 5G 30GB"],
  ["適合 60 歲或以上、需要中港兩地數據之用戶", "For age 60+ who need HK–Mainland data"],
  ["適合需要 s/ash 5G 100GB 之用戶", "For s/ash 5G 100GB"],
  ["適合需要 s/ash 5G 200GB 之用戶", "For s/ash 5G 200GB"],
  ["適合需要 5G 極致 50GB 之用戶", "For 5G Ultimate 50GB"],
  ["適合接受較長合約、需要 5G 極致 50GB 之用戶", "For a longer contract and 5G Ultimate 50GB"],
  ["適合需要 5G 極致 100GB 之用戶", "For 5G Ultimate 100GB"],
  ["適合高本地數據用量、需要 5G 極致之用戶", "For high local data on 5G Ultimate"],
  ["適合 18 至 29 歲、需要中港兩地數據之用戶", "For ages 18–29 who need HK–Mainland data"],
  ["適合需要中港兩地共用 50GB 之用戶", "For 50GB shared HK–Mainland data"],
  ["適合新春期間需要大灣區數據之用戶", "For Greater Bay Area data during Chinese New Year"],
  ["適合本地中用量、學生或轉台客", "For moderate local use, students or port-in"],
  ["適合輕用量、以即時通訊為主", "For light use, mostly messaging"],
  ["適合轉台、想用限時折扣再減月費", "For port-in with a limited-time extra discount"],
  ["適合現用 3香港、準備轉台", "For current 3HK users preparing to port in"],
  ["適合不需要 5G、想要較快限速後備速度", "For users who do not need 5G but want a faster after-quota speed"],
  ["適合備用卡、極輕用量", "For a backup SIM and very light use"],
  ["適合備用卡、比 3GB 版需要多一點數據", "For a backup SIM that needs a little more than 3GB"],
  ["適合合資格長者", "For eligible seniors"],
  ["適合 60 歲或以上、想用 5G 的長者", "For age 60+ who want 5G"],
  ["適合 60 歲或以上、用量接近一般大眾的長者", "For age 60+ with typical data use"],
  ["適合 60 歲或以上、經常過關探親之長者", "For age 60+ who often cross the border to visit family"],
  ["適合重用量、短片用戶", "For heavy use and short-video users"],
  ["適合極重用量或家庭熱點", "For very heavy use or a home hotspot"],
  ["適合要副卡、不受 s/ash 一人一計劃限制", "For extra SIMs without the s/ash one-plan-per-user rule"],
  ["適合接受較長合約、轉台想免多個月月費", "For a longer contract and extra waived months on port-in"],
  ["適合重用量但不想受 s/ash 一人一計劃限制", "For heavy use without the s/ash one-plan-per-user rule"],
  ["適合家庭熱點或極重用量", "For a home hotspot or very heavy use"],
  ["適合 18–29 歲或教職員、經常往返中港", "For ages 18–29 or teaching staff who travel between HK and the Mainland"],
  ["適合每周北上或經常過關", "For weekly northbound or frequent border crossings"],
  ["適合經常走粵港澳、司機或大灣區業務", "For frequent GBA travel, drivers or GBA business"],
  ["適合重視地鐵沿線覆蓋之用戶", "For coverage along MTR lines"],
  ["適合需要 10000M 光纖、Wi-Fi 7 及影視娛樂之住戶", "For those who need 10000M fibre, Wi-Fi 7 and TV entertainment"],
  ["適合需要 10000M 光纖及電競路由器之住戶", "For those who need 10000M fibre and a gaming router"],
  ["適合需要 1000M 光纖及 Wi-Fi 7 路由器之住戶", "For those who need 1000M fibre and a Wi-Fi 7 router"],
  ["適合需要 24 個月合約及 350GB 高速數據之住戶", "For a 24-month contract and 350GB high-speed data"],
  ["適合需要 24 個月合約及 500GB 高速數據之住戶", "For a 24-month contract and 500GB high-speed data"],
  ["適合需要 2500M 光纖及 Wi-Fi 7 路由器之住戶", "For those who need 2500M fibre and a Wi-Fi 7 router"],
  ["適合需要 2500M 光纖及家居電話之住戶", "For those who need 2500M fibre and a home phone"],
  ["適合需要 30 個月合約及 300GB 高速數據之住戶", "For a 30-month contract and 300GB high-speed data"],
  ["適合需要 30 個月合約及 350GB 高速數據之住戶", "For a 30-month contract and 350GB high-speed data"],
  ["適合需要 30 個月合約及 500GB 高速數據之住戶", "For a 30-month contract and 500GB high-speed data"],
  ["適合需要 30 個月合約及 5G 真無限之住戶", "For a 30-month contract and 5G truly unlimited"],
  ["適合需要 30 個月合約及 Wi-Fi 7 真無限之住戶", "For a 30-month contract and Wi-Fi 7 truly unlimited"],
  ["適合需要 4.5G 無限數據及無限本地通話之用戶", "For 4.5G unlimited data and unlimited local calls"],
  ["適合需要中港澳三地共用數據之用戶", "For shared HK–Mainland–Macao data"],
  ["適合需要中澳數據，以及其後仍保持 2Mbps 之用戶", "For Mainland/Macao data that stays at 2Mbps after the quota"],
  ["適合需要入門光纖之住戶", "For entry-level fibre"],
  ["適合需要即插即用之住戶", "For plug-and-play service"],
  ["適合需要換機優惠及 5G 30GB 之用戶", "For a handset offer and 5G 30GB"],
  ["適合需要較穩定上傳之商戶", "For businesses that need more stable upload"],
  ["適合需要較長合約、免還機及 300GB 高速數據之住戶", "For a longer contract, keep-the-router and 300GB high-speed data"],
  ["適合需要較長合約、免還機及 500GB 高速數據之住戶", "For a longer contract, keep-the-router and 500GB high-speed data"],
  ["適合需要較長合約、免還機及 Wi-Fi 7 真無限之住戶", "For a longer contract, keep-the-router and Wi-Fi 7 truly unlimited"],
  ["適合需要較長合約及 350GB 高速數據之住戶", "For a longer contract and 350GB high-speed data"],
  ["適合需要較長合約及 500GB 高速數據之住戶", "For a longer contract and 500GB high-speed data"],
  ["適合需要電訊盈科商用支援之客戶", "For customers who want HKT business support"],
  ["適合需要高於 1000M 之公屋、居屋或私人住宅住戶", "For public housing, HOS or private homes above 1000M"],
  ["適合頻密上載之商戶", "For businesses with heavy upload"],
  ["適合香港寬頻客戶加設無線後備線路", "For HKBN customers adding a wireless backup line"],
  ["適合高本地數據用量之用戶", "For high local data use"],
  ["適合高本地數據用量，以及使用串流應用之用戶", "For high local data plus streaming"],
  ["適合高本地數據用量，以及需要較多內地數據之用戶", "For high local data plus extra Mainland data"],
  ["適合高流量企業", "For high-traffic businesses"],
];

const SORTED = [...BEST_FOR, ...PHRASES].sort((a, b) => b[0].length - a[0].length);

const cache = new Map<string, string>();

export function toEnglish(text: string): string {
  if (!text) return text;
  const hit = cache.get(text);
  if (hit) return hit;
  let out = EXACT[text] ?? text;
  if (CJK.test(out)) {
    for (const [zh, en] of SORTED) {
      if (out.includes(zh)) out = out.split(zh).join(en);
    }
    out = out
      .replace(/(\d+)\s*個月/g, "$1 months")
      .replace(/（/g, "(")
      .replace(/）/g, ")")
      .replace(/／/g, "/")
      .replace(/，/g, ", ")
      .replace(/、/g, ", ")
      .replace(/；/g, "; ")
      .replace(/。/g, ".")
      .replace(/\s+/g, " ")
      .replace(/\s+([,.;])/g, "$1")
      .replace(/\(\s+/g, "(")
      .replace(/\s+\)/g, ")")
      .replace(/([A-Za-z0-9])\(/g, "$1 (")
      .replace(/ \+/g, " +")
      .trim();
  }
  cache.set(text, out);
  return out;
}

/** @deprecated use toEnglish — kept so older imports still typecheck during edits */
export const PLAN_EN: Record<string, string> = EXACT;
