export type Category = "broadband" | "mobile" | "home5g" | "business";
export type Housing = "public" | "hos" | "private" | "village";
export type Generation = "4g" | "5g";
export type SpeedMbps = 200 | 500 | 1000 | 2000 | 2500 | 5000 | 10000;

export type ProviderId =
  | "hkbn"
  | "netvigator"
  | "cmhk"
  | "hgc"
  | "smartone"
  | "three"
  | "csl"
  | "icable";

export type Provider = {
  id: ProviderId;
  name: string;
  nameEn: string;
  initial: string;
  tone: string;
};

export const PROVIDERS: Provider[] = [
  { id: "hkbn", name: "香港寬頻", nameEn: "HKBN", initial: "寬", tone: "bg-provider-hkbn" },
  { id: "netvigator", name: "網上行", nameEn: "Netvigator", initial: "網", tone: "bg-provider-netvigator" },
  { id: "cmhk", name: "中國移動香港", nameEn: "CMHK", initial: "移", tone: "bg-provider-cmhk" },
  { id: "hgc", name: "HGC 寬頻", nameEn: "HGC", initial: "H", tone: "bg-provider-hgc" },
  { id: "smartone", name: "數碼通", nameEn: "SmarTone", initial: "S", tone: "bg-provider-smartone" },
  { id: "three", name: "3香港", nameEn: "3HK", initial: "3", tone: "bg-provider-three" },
  { id: "csl", name: "csl.", nameEn: "csl.", initial: "C", tone: "bg-provider-csl" },
  { id: "icable", name: "有線寬頻", nameEn: "i-Cable", initial: "線", tone: "bg-provider-icable" },
];

export const PROVIDER_MAP = Object.fromEntries(PROVIDERS.map((p) => [p.id, p])) as Record<
  ProviderId,
  Provider
>;

export type Plan = {
  id: string;
  providerId: ProviderId;
  category: Category;
  name: string;
  monthlyFee: number;
  freeMonths: number;
  contractMonths: number;
  speedMbps?: number;
  dataGb?: number;
  highSpeedGb?: number;
  fupNote?: string;
  voice?: string;
  roaming?: string;
  install: string;
  housing: Housing[] | "all";
  network: string;
  perks: string[];
  portInPerk?: string;
  prepaid?: string;
  limits?: string;
  hot?: boolean;
  bestFor: string;
};

const LIMITS_HKBN_10G =
  "本計劃為自動續約。優惠適用於指定公屋、居屋及私人住宅，且該地址於登記前 120 日內未曾使用香港寬頻之寬頻服務。實際安裝費用及網絡覆蓋視乎個別大廈基礎設施而定。不適用於村屋。";
const LIMITS_HKBN_5G =
  "本計劃為自動續約。家居 5000M 光纖入屋現時主要由香港寬頻提供，適用於指定公屋、居屋及私人住宅。不適用於村屋。";
const LIMITS_HKBN_FTTH =
  "本計劃為自動續約。可選擇延遲服務生效日（最長 365 日）。適用於指定公屋、居屋及私人住宅。不適用於村屋。";
const LIMITS_HKBN_VILLAGE_27 =
  "僅適用於指定村屋地址。本計劃為 27 個月合約。可選擇延遲服務生效日（最長 365 日）。香港寬頻之公屋、居屋及私人樓宇計劃不適用於村屋地址。實際覆蓋須另行核對。";
const LIMITS_HKBN_VILLAGE_SELECT_24 =
  "僅適用於指定村屋地址。本計劃為 24 個月合約。可選擇延遲服務生效日（最長 365 日）。實際覆蓋須另行核對。";
const LIMITS_NETVIGATOR_FTTH =
  "可選擇先安裝後啟動服務（最長 365 日）。實際覆蓋視乎個別樓宇而定。";
const LIMITS_NETVIGATOR_10G =
  "家居 10000M 光纖入屋現時主要由香港寬頻及電訊盈科網上行提供，適用於公屋、居屋及私人住宅。首次安裝須繳付安裝費。實際覆蓋視乎個別樓宇基礎設施而定。";
const LIMITS_NETVIGATOR_VILLAGE =
  "適用於指定村屋及唐樓地址。須另行繳付安裝費。實際覆蓋須核對門牌。網上行之公屋、居屋及私人樓宇計劃不適用於村屋或唐樓。";
const LIMITS_HGC_VILLAGE =
  "適用於村屋地址。馬灣或若干指定村落未必享有額外特別優惠，詳情請向當值銷售員查詢。不適用於公屋、居屋及私人樓宇。實際覆蓋須核對門牌。";
const LIMITS_HOME5G_SPEED =
  "實際速度介乎 100M 至 1000M，視乎訊號覆蓋、裝置數量及現場環境而定。";
const LIMITS_CMHK_HOME5G =
  "實際速度介乎 100M 至 1000M，視乎訊號覆蓋、裝置數量及現場環境而定。本計劃為自動續約。P2P 及 Thunder 下載期間限速至 128kbps。";
const PERK_CMHK_HOME_ROUTER = "租借 Wi-Fi 7 路由器";
const PERK_CMHK_HOME_COOL = "7 日冷靜期（服務啟用後連續使用 7 日）";
const PERK_CMHK_HOME_DEPOSIT = "以信用卡自動轉賬可豁免按金 HK$1,500";
const PERK_NETVIGATOR_NOWTV =
  "Now TV 體驗組合或國際新聞組合（智能電視版）；可加 HK$38 升級機頂盒";
const PERK_NETVIGATOR_MOVE = "搬遷費津貼 HK$1,000";
const PERK_NETVIGATOR_RELO = "豁免搬遷費";
const PERK_NETVIGATOR_APPLIANCE = "可加購每月 HK$68 換購指定家電（須符合資格）";
const PERK_THREE_HOME_MOVE = "不鎖定地區，可隨時搬遷";
const PERK_THREE_HOME_COOL = "7 日冷靜期";
const PERK_THREE_HOME_VISIT = "專人上門測試訊號";
const PERK_THREE_TUNNEL = "豁免隧道費（原價每月 HK$28）";
const PERK_THREE_CN_NUM = "內地副號";
const PERK_THREE_SOCIAL =
  "任用社交組合 15 個應用程式（Facebook、Instagram、WhatsApp、LINE、WeChat、Signal、Zoom、YouTube、Netflix、Apple TV、myTV SUPER、Disney+、hmvod、Douyin 及 Teams；不包括下載）";
const PERK_SMARTONE_PORT = "攜號轉台本地數據雙倍";
const PERK_HKBN_PORT = "攜號轉台適用";
const PREPAID_HGC_300 = "須預繳 HK$300";
const PREPAID_HKBN_200 = "須預繳 HK$200，第 1 至第 4 個月每月從預繳費用中扣減月費 HK$50";
const PERK_HKBN_365 = "可選擇延遲服務生效日（最長 365 日）";
const PERK_HKBN_SAFE = "SAFE 網絡安全防護及防毒軟件 6 個月";

export const PLANS: Plan[] = [
  {
    id: "hkbn-ftth-1000-36m-98",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 連 Wi-Fi 6 路由器（36 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: [
      "送 TP-Link Archer AX23 Wi-Fi 6 路由器",
      "首 36 個月額外免費 1000M 副線",
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    hot: true,
    bestFor: "適合公屋、居屋或私人住宅，需要 1000M 光纖及路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-36m-108",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 連 Wi-Fi 7 路由器（36 個月）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: ["送 TP-Link Archer BE230 Wi-Fi 7 路由器（36 個月）", PERK_HKBN_365],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合需要 1000M 光纖及 Wi-Fi 7 路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-24m-109",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 家居寬頻（24 個月）",
    monthlyFee: 109,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: [
      "加購可享首 24 個月額外免費 1000M 副線",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合租住單位、接受 24 個月合約之住戶",
  },
  {
    id: "hkbn-ftth-1000-36m-128",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 連 Mesh Wi-Fi 7（36 個月）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: PREPAID_HKBN_200,
    perks: ["送 TP-Link Deco BE25 兩件裝 Wi-Fi 7 路由器（36 個月）", PERK_HKBN_365],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合較大單位、需要全屋 Mesh 覆蓋之住戶",
  },
  {
    id: "hkbn-ftth-1000-12m-168",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 基本月費計劃（12 個月）",
    monthlyFee: 168,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "須繳付安裝費 HK$680",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "四選一：TP-Link Archer AX23 路由器、愛奇藝黃金會員 12 個月、JOOX VIP 12 個月或 WeTV 12 個月",
      "SAFE 防毒軟件 6 個月",
      "可選擇延遲服務生效日（最長 365 日）",
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合接受 12 個月合約及自選禮遇之住戶",
  },
  {
    id: "hkbn-ftth-1000-12m-2800",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 一次過付款連影視／路由器（12 個月）",
    monthlyFee: 233,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "一次過支付 HK$2,800（平均每月約 HK$233.3）",
      "四選一：Disney+ 標準版 12 個月、Netflix 標準版 12 個月、愛奇藝鑽石會員 12 個月或 TP-Link Archer AX23 路由器",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合一次過付款、需要影視會籍或路由器之住戶",
  },
  {
    id: "hkbn-ftth-1000-12m-mytv",
    providerId: "hkbn",
    category: "broadband",
    name: "1000M 一次過付款連 myTV Gold（12 個月）",
    monthlyFee: 233,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "一次過支付 HK$2,800（平均每月約 HK$233.3）",
      "12 個月 myTV Gold 服務",
      "12 個月 myTV SUPER 基本版（智能電視版）",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合一次過付款、需要 myTV Gold 之住戶",
  },
  {
    id: "hkbn-ftth-2500-24m-149",
    providerId: "hkbn",
    category: "broadband",
    name: "2500M 光纖連家居電話（24 個月＋Wi-Fi 7）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["送指定 TP-Link BE230 Wi-Fi 7 路由器", "家居電話服務"],
    limits: LIMITS_HKBN_FTTH,
    hot: true,
    bestFor: "適合需要 2500M 光纖及家居電話之住戶",
  },
  {
    id: "hkbn-ftth-2500-12m-218",
    providerId: "hkbn",
    category: "broadband",
    name: "2.5Gbps 高速上網連 Wi-Fi 7（12 個月）",
    monthlyFee: 218,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 2500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "送指定 TP-Link Archer BE230 Wi-Fi 7 路由器（12 個月）",
      "SAFE 網絡安全防護及防毒軟件 6 個月",
      "可選擇延遲服務生效日（最長 365 日）",
    ],
    limits: LIMITS_HKBN_FTTH,
    bestFor: "適合需要 2500M 光纖及 Wi-Fi 7 路由器之住戶",
  },
  {
    id: "hkbn-ftth-5000",
    providerId: "hkbn",
    category: "broadband",
    name: "5000M 光纖連家居電話（24 個月）",
    monthlyFee: 249,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 5000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["家居電話服務", PERK_HKBN_SAFE, PERK_HKBN_365, "Money-Back 雙重保證（速度保證、低時延保證）"],
    limits: LIMITS_HKBN_5G,
    bestFor: "適合公屋、居屋或私人住宅，需要 5000M 光纖及家居電話之住戶",
  },
  {
    id: "hkbn-ftth-10000-entertainment",
    providerId: "hkbn",
    category: "broadband",
    name: "10000M 連 Wi-Fi 7 及娛樂組合（24 個月）",
    monthlyFee: 998,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [
      "送 TP-Link Aginet EB810v Wi-Fi 7 路由器（24 個月）",
      "24 個月 Disney+ 標準計劃",
      "24 個月 Netflix 標準計劃",
      "24 個月 iQIYI 愛奇藝黃金會員",
      "myTV SUPER 解碼器",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
      "Money-Back 雙重保證（速度保證、低時延保證）",
    ],
    limits: LIMITS_HKBN_10G,
    bestFor: "適合需要 10000M 光纖、Wi-Fi 7 及影視娛樂之住戶",
  },
  {
    id: "hkbn-ftth-10000-ge800",
    providerId: "hkbn",
    category: "broadband",
    name: "10000M 連遊戲路由器及娛樂組合（24 個月）",
    monthlyFee: 998,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    prepaid: "須預繳 HK$3,600，第 1 至第 24 個月每月回贈 HK$150",
    perks: [
      "送 TP-Link Archer GE800 Wi-Fi 7 路由器（24 個月）",
      "12 個月 WTFast 電競玩家專用網絡",
      "24 個月 Disney+ 標準計劃",
      "24 個月 Netflix 標準計劃",
      "24 個月 iQIYI 愛奇藝黃金會員",
      "myTV SUPER 解碼器",
      PERK_HKBN_SAFE,
      PERK_HKBN_365,
    ],
    limits: LIMITS_HKBN_10G,
    bestFor: "適合需要 10000M 光纖及電競路由器之住戶",
  },
  {
    id: "hkbn-village-200-27m",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 200M 光纖（27 個月）",
    monthlyFee: 298,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 200,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["第 13 至第 15 個月免費", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_27,
    bestFor: "適合指定村屋、需要 200M 光纖之住戶",
  },
  {
    id: "hkbn-village-500-27m",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 500M 光纖（27 個月）",
    monthlyFee: 328,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["第 13 至第 15 個月免費", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_27,
    bestFor: "適合指定村屋、需要 500M 光纖之住戶",
  },
  {
    id: "hkbn-village-1000-27m",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 1000M 光纖（27 個月）",
    monthlyFee: 378,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["第 13 至第 15 個月免費", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_27,
    hot: true,
    bestFor: "適合指定村屋、需要 1000M 光纖之住戶",
  },
  {
    id: "hkbn-village-2500-upgrade",
    providerId: "hkbn",
    category: "broadband",
    name: "村屋 2500M 升級旗艦（27 個月＋Wi-Fi 7）",
    monthlyFee: 424,
    freeMonths: 3,
    contractMonths: 27,
    speedMbps: 2500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: [
      "原 1000M 計劃加購每月 HK$46（24 個月），合約期內自動升級至 2500M",
      "送 TP-Link BE230 Wi-Fi 7 路由器（合約後無須歸還）",
      "可選擇延遲服務生效日（最長 365 日）",
    ],
    limits: LIMITS_HKBN_VILLAGE_27,
    bestFor: "適合指定村屋、需要升級至 2500M 及 Wi-Fi 7 之住戶",
  },
  {
    id: "hkbn-village-2000-24m",
    providerId: "hkbn",
    category: "broadband",
    name: "特選村屋 2000M 光纖（24 個月）",
    monthlyFee: 229,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_SELECT_24,
    bestFor: "適合特選村屋、需要 2000M 光纖之住戶",
  },
  {
    id: "hkbn-village-2000-be230",
    providerId: "hkbn",
    category: "broadband",
    name: "特選村屋 2000M 連 Wi-Fi 7（24 個月）",
    monthlyFee: 275,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 TP-Link BE230 Wi-Fi 7 路由器", "可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_SELECT_24,
    bestFor: "適合特選村屋、需要 2000M 光纖及 Wi-Fi 7 之住戶",
  },
  {
    id: "hkbn-village-2500-24m",
    providerId: "hkbn",
    category: "broadband",
    name: "特選村屋 2500M 光纖（24 個月）",
    monthlyFee: 258,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["可選擇延遲服務生效日（最長 365 日）"],
    limits: LIMITS_HKBN_VILLAGE_SELECT_24,
    bestFor: "適合特選村屋、需要 2500M 光纖之住戶",
  },
  {
    id: "hgc-ftth-1000-public-36m",
    providerId: "hgc",
    category: "broadband",
    name: "公居屋轉台 1000M（36 個月）",
    monthlyFee: 75,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    hot: true,
    bestFor: "適合公屋或居屋轉台、需要 1000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-2000-hos-36m",
    providerId: "hgc",
    category: "broadband",
    name: "新居屋／簡約公屋 2000M（36 個月＋Wi-Fi 7）",
    monthlyFee: 75,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 7 路由器", "豁免搬遷費"],
    hot: true,
    bestFor: "適合新入伙居屋或簡約公屋住戶",
  },
  {
    id: "hgc-ftth-1000-public-39m",
    providerId: "hgc",
    category: "broadband",
    name: "公居屋 1000M（39 個月＋Wi-Fi 6＋電話）",
    monthlyFee: 89,
    freeMonths: 0,
    contractMonths: 39,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送指定 TP-Link Wi-Fi 6 路由器", "家居電話服務", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要路由器及家居電話之住戶",
  },
  {
    id: "hgc-ftth-2000-public-36m",
    providerId: "hgc",
    category: "broadband",
    name: "公居屋 2000M（36 個月）",
    monthlyFee: 119,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要 2000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-1000-private-39m",
    providerId: "hgc",
    category: "broadband",
    name: "私人樓宇 1000M（39 個月＋Wi-Fi 6＋電話）",
    monthlyFee: 89,
    freeMonths: 0,
    contractMonths: 39,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 TP-Link Wi-Fi 6 路由器", "家居電話服務", "豁免搬遷費"],
    bestFor: "適合私人屋苑轉台、需要 1000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-2000-private-36m",
    providerId: "hgc",
    category: "broadband",
    name: "私人樓宇 2000M（36 個月）",
    monthlyFee: 129,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合私人屋苑、需要 2000M 光纖之住戶",
  },
  {
    id: "hgc-ftth-1000-student",
    providerId: "hgc",
    category: "broadband",
    name: "留學生 1000M（12 個月）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 12,
    speedMbps: 1000,
    install: "安裝費 HK$180",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合留學生短約之住戶",
  },
  {
    id: "hgc-village-1g-phone-24m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 1G 連電話（24 個月）",
    monthlyFee: 319,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "須另行核對",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "家居／寬頻電話服務",
      "24 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 1G 光纖及電話之住戶",
  },
  {
    id: "hgc-village-1g-router-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 1G 連路由器＋電話（30 個月）",
    monthlyFee: 329,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    install: "須另行核對",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 TP-Link EX141 路由器",
      "家居／寬頻電話服務",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要路由器之住戶",
  },
  {
    id: "hgc-village-2g-24m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 純寬頻（24 個月）",
    monthlyFee: 329,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "須另行核對",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: ["24 個月 100 分鐘 hgc on air Wi-Fi", "1GB 電郵儲存量", "豁免搬遷費"],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 2G 光纖之住戶",
  },
  {
    id: "hgc-village-2g-tv-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 連電視娛樂（30 個月）",
    monthlyFee: 329,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 2000,
    install: "須另行核對",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 24 個月 myTV SUPER 組合（基本、TVB 外購節目、精選基本、跨屏幕同時睇）",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要影視娛樂之住戶",
  },
  {
    id: "hgc-village-2g-wifi6-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 連 Wi-Fi 6＋電話（30 個月）",
    monthlyFee: 349,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 2000,
    install: "須另行核對",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 TP-Link Wi-Fi 6 路由器",
      "家居／寬頻電話服務",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 Wi-Fi 6 之住戶",
  },
  {
    id: "hgc-village-2g-wifi7-30m",
    providerId: "hgc",
    category: "broadband",
    name: "村屋 2G 連 Wi-Fi 7＋電話（30 個月）",
    monthlyFee: 359,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 2000,
    install: "須另行核對",
    housing: ["village"],
    network: "光纖入屋",
    prepaid: PREPAID_HGC_300,
    perks: [
      "送 TP-Link Wi-Fi 7 旗艦路由器",
      "家居／寬頻電話服務",
      "30 個月 100 分鐘 hgc on air Wi-Fi",
      "1GB 電郵儲存量",
      "豁免搬遷費",
    ],
    limits: LIMITS_HGC_VILLAGE,
    bestFor: "適合村屋、需要 Wi-Fi 7 之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月＋家居電話）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE, "可加 HK$10 選配 Linksys EA9350 Wi-Fi 6 路由器"],
    limits: LIMITS_NETVIGATOR_FTTH,
    hot: true,
    bestFor: "適合私人樓宇、需要 1000M 光纖及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m-198",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月）",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: [PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE, "新客戶可加每月 HK$98 升級 2500M"],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、可升級 2500M 之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-24m",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（24 個月＋Wi-Fi 6＋電話）",
    monthlyFee: 186,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 6 路由器", "家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合私人樓宇、需要 Wi-Fi 6 及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-2500-public-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 2500M 光纖（36 個月＋Wi-Fi 7）",
    monthlyFee: 178,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["12 個月 Disney+", "送指定 Wi-Fi 7 路由器", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: LIMITS_NETVIGATOR_FTTH,
    bestFor: "適合公屋或居屋、需要 2500M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-2500-private-24m",
    providerId: "netvigator",
    category: "broadband",
    name: "獨家私人樓宇 2500M 光纖（24 個月＋Wi-Fi 7＋家居電話）",
    monthlyFee: 244,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["送指定 Wi-Fi 7 路由器", "家居固網電話", PERK_NETVIGATOR_NOWTV, PERK_NETVIGATOR_MOVE],
    limits: `${LIMITS_NETVIGATOR_FTTH}僅適用於指定獨家私人樓宇。`,
    bestFor: "適合指定獨家私人樓宇、需要 2500M 光纖及家居電話之住戶",
  },
  {
    id: "netvigator-ftth-1000-public-36m-108",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 1000M 光纖（36 個月＋路由器）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["包指定 Wi-Fi 路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    hot: true,
    bestFor: "適合公屋或居屋、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-private-36m-118",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月＋路由器）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["包指定 Wi-Fi 路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    bestFor: "適合私人屋苑、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-2500-public-36m-156",
    providerId: "netvigator",
    category: "broadband",
    name: "公居屋 2500M 光纖（36 個月＋Wi-Fi 7 二合一）",
    monthlyFee: 156,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["包 Wi-Fi 7 二合一路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    hot: true,
    bestFor: "適合公屋或居屋、需要 2500M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-2500-private-36m-176",
    providerId: "netvigator",
    category: "broadband",
    name: "私人樓宇 2500M 光纖（36 個月＋Wi-Fi 7）",
    monthlyFee: 176,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["包 Wi-Fi 7 二合一路由器", "送 Now TV 頻道", PERK_NETVIGATOR_RELO, PERK_NETVIGATOR_APPLIANCE],
    bestFor: "適合私人屋苑、需要 2500M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-1000-village-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "村屋／唐樓 1000M 光纖（36 個月）",
    monthlyFee: 268,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "須另行繳付安裝費",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 Now TV 頻道", PERK_NETVIGATOR_APPLIANCE],
    limits: LIMITS_NETVIGATOR_VILLAGE,
    bestFor: "適合村屋或唐樓、需要 1000M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-2500-village-36m",
    providerId: "netvigator",
    category: "broadband",
    name: "村屋／唐樓 2500M 光纖（36 個月）",
    monthlyFee: 398,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2500,
    install: "須另行繳付安裝費",
    housing: ["village"],
    network: "光纖入屋",
    perks: ["送 Now TV 頻道", PERK_NETVIGATOR_APPLIANCE],
    limits: LIMITS_NETVIGATOR_VILLAGE,
    bestFor: "適合村屋或唐樓、需要 2500M 光纖之住戶",
  },
  {
    id: "netvigator-ftth-10000",
    providerId: "netvigator",
    category: "broadband",
    name: "10000M 光纖入屋（24 個月）",
    monthlyFee: 998,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "首次安裝須繳付 HK$480",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [],
    limits: LIMITS_NETVIGATOR_10G,
    bestFor: "適合公屋、居屋或私人住宅，需要 10000M 光纖之住戶",
  },
  {
    id: "icable-ftth-200-36m",
    providerId: "icable",
    category: "broadband",
    name: "200M 光纖（36 個月）",
    monthlyFee: 68,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 200,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    hot: true,
    bestFor: "適合需要入門光纖之住戶",
  },
  {
    id: "icable-ftth-1000-private-36m",
    providerId: "icable",
    category: "broadband",
    name: "私人樓宇 1000M 光纖（36 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合私人樓宇、需要 1000M 光纖之住戶",
  },
  {
    id: "icable-ftth-1000-public-48m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 1000M 光纖（48 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link EX141 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要 1000M 光纖之住戶",
  },
  {
    id: "icable-ftth-1000-public-36m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 1000M 光纖（36 個月）",
    monthlyFee: 93,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link EX141 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、接受 36 個月合約之住戶",
  },
  {
    id: "icable-ftth-2000-private-36m",
    providerId: "icable",
    category: "broadband",
    name: "私人樓宇 2000M 光纖（36 個月）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["private"],
    network: "光纖入屋",
    perks: ["豁免搬遷費"],
    bestFor: "適合私人樓宇、需要 2000M 光纖之住戶",
  },
  {
    id: "icable-ftth-2000-public-36m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 2000M 光纖（36 個月）",
    monthlyFee: 129,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link AX55 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、需要 2000M 光纖之住戶",
  },
  {
    id: "icable-ftth-2000-public-24m",
    providerId: "icable",
    category: "broadband",
    name: "公居屋 2000M 光纖（24 個月）",
    monthlyFee: 149,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2000,
    install: "豁免安裝費",
    housing: ["public", "hos"],
    network: "光纖入屋",
    perks: ["送 TP-Link AX55 路由器", "豁免搬遷費"],
    bestFor: "適合公屋或居屋、接受較短合約之住戶",
  },
  {
    id: "cmhk-ftth-1000",
    providerId: "cmhk",
    category: "broadband",
    name: "1000M 光纖入屋（36 個月）",
    monthlyFee: 78,
    freeMonths: 3,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["首 3 個月免月費"],
    bestFor: "適合公屋、居屋或私人住宅之入門 1000M 住戶",
  },
  {
    id: "cmhk-ftth-2500",
    providerId: "cmhk",
    category: "broadband",
    name: "2500M 光纖入屋（36 個月）",
    monthlyFee: 128,
    freeMonths: 2,
    contractMonths: 36,
    speedMbps: 2500,
    install: "豁免安裝費",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: ["豁免安裝費"],
    bestFor: "適合需要高於 1000M 之公屋、居屋或私人住宅住戶",
  },
  {
    id: "smartone-ftth-1000",
    providerId: "smartone",
    category: "broadband",
    name: "1000M 家居寬頻（36 個月）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 36,
    speedMbps: 1000,
    install: "豁免安裝費（原價 HK$680）",
    housing: ["public", "hos", "private"],
    network: "光纖入屋",
    perks: [],
    bestFor: "適合公屋、居屋或私人住宅、需要 1000M 光纖之住戶",
  },
  {
    id: "three-home5g-a-118",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 300GB（30 個月）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    highSpeedGb: 300,
    fupNote: "其後提供 5G 任用數據",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免租／買機優惠", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要 30 個月合約及 300GB 高速數據之住戶",
  },
  {
    id: "three-home5g-b-158",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 真無限（30 個月）",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    fupNote: "5G 真無限",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免租／買機優惠", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要 30 個月合約及 5G 真無限之住戶",
  },
  {
    id: "three-home5g-c-190",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 7 真無限（30 個月）",
    monthlyFee: 190,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    fupNote: "5G 真無限",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: ["免租／買機優惠", "送指定 Wi-Fi 7 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要 30 個月合約及 Wi-Fi 7 真無限之住戶",
  },
  {
    id: "three-home5g-w6",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 300GB（48 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 300,
    fupNote: "其後提供 5G 任用數據",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免還機", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    hot: true,
    bestFor: "適合需要較長合約、免還機及 300GB 高速數據之住戶",
  },
  {
    id: "three-home5g-e-108",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 6 500GB（48 個月）",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後提供 5G 任用數據",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 6）",
    perks: ["免還機", "送指定 Wi-Fi 6 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要較長合約、免還機及 500GB 高速數據之住戶",
  },
  {
    id: "three-home5g-w7",
    providerId: "three",
    category: "home5g",
    name: "5G 家居 Wi-Fi 7 真無限（48 個月）",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    fupNote: "5G 真無限",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: ["免還機", "送指定 Wi-Fi 7 路由器", PERK_THREE_HOME_MOVE, PERK_THREE_HOME_COOL, PERK_THREE_HOME_VISIT],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要較長合約、免還機及 Wi-Fi 7 真無限之住戶",
  },
  {
    id: "smartone-home5g-w6",
    providerId: "smartone",
    category: "home5g",
    name: "5G 家居寬頻 Wi-Fi 6",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "無需室內拉線，即插即用",
    housing: "all",
    network: "5G 無線",
    perks: ["送指定 5G 路由器"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合需要即插即用之住戶",
  },
  {
    id: "cmhk-home5g-350-48-88",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 350GB（48 個月，租借 Wi-Fi 7）",
    monthlyFee: 88,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 350,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    hot: true,
    bestFor: "適合需要較長合約及 350GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-350-30-118",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 350GB（30 個月，租借 Wi-Fi 7）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    highSpeedGb: 350,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 30 個月合約及 350GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-w7",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 350GB（24 個月，租借 Wi-Fi 7）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    highSpeedGb: 350,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 24 個月合約及 350GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-500-48-118",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 500GB（48 個月，租借 Wi-Fi 7）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 48,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要較長合約及 500GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-500-30-148",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 500GB（30 個月，租借 Wi-Fi 7）",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 30,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 30 個月合約及 500GB 高速數據之住戶",
  },
  {
    id: "cmhk-home5g-500-24-178",
    providerId: "cmhk",
    category: "home5g",
    name: "5G 家居 500GB（24 個月，租借 Wi-Fi 7）",
    monthlyFee: 178,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    highSpeedGb: 500,
    fupNote: "其後按公平使用政策；P2P 及 Thunder 下載限速至 128kbps",
    install: "豁免安裝費，無需拉線",
    housing: "all",
    network: "5G 無線（Wi-Fi 7）",
    perks: [PERK_CMHK_HOME_ROUTER, PERK_CMHK_HOME_COOL, PERK_CMHK_HOME_DEPOSIT],
    limits: LIMITS_CMHK_HOME5G,
    bestFor: "適合需要 24 個月合約及 500GB 高速數據之住戶",
  },
  {
    id: "csl-home5g",
    providerId: "csl",
    category: "home5g",
    name: "5G 家居寬頻",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "無需室內拉線",
    housing: "all",
    network: "5G 無線",
    perks: ["14 日冷靜期", "可同時申請 csl 流動服務"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合現有 csl 或網上行客戶",
  },
  {
    id: "hkbn-home5g",
    providerId: "hkbn",
    category: "home5g",
    name: "5G 家居寬頻連路由器",
    monthlyFee: 168,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    highSpeedGb: 300,
    fupNote: "其後無限任用，惟降低網絡優先權",
    install: "無需室內拉線，路由器隨計劃提供",
    housing: "all",
    network: "5G 無線",
    perks: ["計劃包含指定路由器", "7 日免費試用"],
    limits: LIMITS_HOME5G_SPEED,
    bestFor: "適合香港寬頻客戶加設無線後備線路",
  },
  {
    id: "three-45g-44",
    providerId: "three",
    category: "mobile",
    name: "4.5G 10GB（30 個月）",
    monthlyFee: 44,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 10,
    highSpeedGb: 10,
    voice: "本地 3000 分鐘",
    roaming: "每月 500MB 中國及澳門數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [PERK_THREE_TUNNEL],
    hot: true,
    bestFor: "適合以即時通訊為主、較少串流之用戶",
  },
  {
    id: "three-5g-60-79",
    providerId: "three",
    category: "mobile",
    name: "5G 60GB（30 個月）",
    monthlyFee: 79,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 60,
    highSpeedGb: 60,
    voice: "本地 3000 分鐘",
    roaming: "每月 4GB 中國及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [
      PERK_THREE_TUNNEL,
      PERK_THREE_CN_NUM,
      "每月免費 10 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5",
      PERK_THREE_SOCIAL,
    ],
    bestFor: "適合中等數據用量，以及使用即時通訊與串流應用之用戶",
  },
  {
    id: "three-5g-100-105",
    providerId: "three",
    category: "mobile",
    name: "5G 100GB（30 個月）",
    monthlyFee: 105,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 100,
    highSpeedGb: 100,
    voice: "本地 3000 分鐘",
    roaming: "每月 8GB 中國及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [
      PERK_THREE_TUNNEL,
      PERK_THREE_CN_NUM,
      "每月免費 50 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5",
      PERK_THREE_SOCIAL,
    ],
    bestFor: "適合較高本地數據用量之用戶",
  },
  {
    id: "three-5g-70-cga",
    providerId: "three",
    category: "mobile",
    name: "5G 70GB 三地共用（30 個月）",
    monthlyFee: 139,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 70,
    highSpeedGb: 70,
    voice: "本地 3000 分鐘",
    roaming: "70GB 中國／香港／澳門三地共用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [
      PERK_THREE_TUNNEL,
      PERK_THREE_CN_NUM,
      "每月免費 200 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5",
    ],
    bestFor: "適合經常往返中港澳之用戶",
  },
  {
    id: "three-5g-200-145",
    providerId: "three",
    category: "mobile",
    name: "5G 200GB（30 個月）",
    monthlyFee: 145,
    freeMonths: 0,
    contractMonths: 30,
    dataGb: 200,
    highSpeedGb: 200,
    voice: "本地 3000 分鐘",
    roaming: "每月 12GB 中國及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [
      PERK_THREE_TUNNEL,
      PERK_THREE_CN_NUM,
      "每月免費 100 分鐘中國及澳門漫遊通話，其後每分鐘 HK$0.5",
      PERK_THREE_SOCIAL,
    ],
    bestFor: "適合高本地數據用量，以及使用串流應用之用戶",
  },
  {
    id: "cmhk-45g-68",
    providerId: "cmhk",
    category: "mobile",
    name: "4.5G 8GB",
    monthlyFee: 68,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 8,
    highSpeedGb: 8,
    fupNote: "8GB 高速數據其後以 128kbps 任用",
    voice: "本地 3000 分鐘",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["MyLink 積分計劃"],
    bestFor: "適合備用卡或較低用量之用戶",
  },
  {
    id: "csl-45g-78",
    providerId: "csl",
    category: "mobile",
    name: "4.5G 10GB",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: "10GB 高速數據其後以 1Mbps 任用",
    voice: "本地無限分鐘",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["轉台或附禮品（視申請時優惠而定）"],
    bestFor: "適合輕量上網、需要無限通話之用戶",
  },
  {
    id: "csl-5g-30",
    providerId: "csl",
    category: "mobile",
    name: "5G 30GB",
    monthlyFee: 108,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後以 1Mbps 任用",
    voice: "本地無限分鐘",
    roaming: "每月 3GB 中澳數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["轉台或可享 HK$100 回贈（視申請時優惠而定）"],
    portInPerk: "攜號轉台簽訂 36 個月合約或可享月費回贈",
    bestFor: "適合重視地鐵沿線覆蓋之用戶",
  },
  {
    id: "cmhk-5g-100",
    providerId: "cmhk",
    category: "mobile",
    name: "5G 100GB",
    monthlyFee: 149,
    freeMonths: 1,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: "其後以 5Mbps 任用",
    voice: "本地無限分鐘",
    roaming: "每月 3GB 中澳數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["MyLink 積分計劃"],
    portInPerk: "攜號轉台或可免 1–3 個月月費",
    bestFor: "適合數據用量大、經常串流之用戶",
  },
  {
    id: "smartone-45g-78",
    providerId: "smartone",
    category: "mobile",
    name: "4.5G 首 10GB（24 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: "首 10GB（42Mbps），其後以 128kbps 任用",
    voice: "無限本地通話",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_SMARTONE_PORT,
    hot: true,
    bestFor: "適合輕量上網、需要無限本地通話之用戶",
  },
  {
    id: "smartone-45g-98",
    providerId: "smartone",
    category: "mobile",
    name: "4.5G 首 14GB（24 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 14,
    highSpeedGb: 14,
    fupNote: "首 14GB（42Mbps），其後以 2Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 1GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_SMARTONE_PORT,
    bestFor: "適合需要中澳數據，以及其後仍保持 2Mbps 之用戶",
  },
  {
    id: "smartone-5g-30-youth",
    providerId: "smartone",
    category: "mobile",
    name: "5G 30GB 青年計劃（36 個月）",
    monthlyFee: 98,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 3GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["適用於 18 至 29 歲"],
    portInPerk: PERK_SMARTONE_PORT,
    limits: "適用於 18 至 29 歲客戶。",
    bestFor: "適合 18 至 29 歲、需要 5G 30GB 之用戶",
  },
  {
    id: "smartone-45g-120",
    providerId: "smartone",
    category: "mobile",
    name: "4.5G 42Mbps 無限任用（24 個月）",
    monthlyFee: 120,
    freeMonths: 0,
    contractMonths: 24,
    fupNote: "42Mbps 無限任用",
    voice: "無限本地通話",
    roaming: "每月 1GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: ["無限本地數據（42Mbps）"],
    portInPerk: PERK_SMARTONE_PORT,
    bestFor: "適合需要 4.5G 無限數據及無限本地通話之用戶",
  },
  {
    id: "smartone-5g-60-youth",
    providerId: "smartone",
    category: "mobile",
    name: "5G 60GB 青年計劃（36 個月）",
    monthlyFee: 138,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 60,
    highSpeedGb: 60,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 4GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["適用於 18 至 29 歲"],
    portInPerk: PERK_SMARTONE_PORT,
    limits: "適用於 18 至 29 歲客戶。",
    bestFor: "適合 18 至 29 歲、需要 5G 60GB 之用戶",
  },
  {
    id: "smartone-5g-30-iphone",
    providerId: "smartone",
    category: "mobile",
    name: "5G 30GB 連手機券（36 個月）",
    monthlyFee: 139,
    freeMonths: 0,
    contractMonths: 36,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 2GB 中國內地及澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["新一代 iPhone 早鳥專屬優惠", "送 HK$1,400 手機券"],
    portInPerk: "攜號轉台本地數據雙倍；另加 HK$18 行政費",
    bestFor: "適合需要換機優惠及 5G 30GB 之用戶",
  },
  {
    id: "smartone-5g-60",
    providerId: "smartone",
    category: "mobile",
    name: "5G Premier 60GB",
    monthlyFee: 179,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 60,
    highSpeedGb: 60,
    fupNote: "其後以 1Mbps 任用",
    voice: "無限本地通話",
    roaming: "每月 2–4GB 中澳數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["可加購家庭副卡"],
    bestFor: "適合流動數據用量中等之用戶",
  },
  {
    id: "hkbn-45g-10",
    providerId: "hkbn",
    category: "mobile",
    name: "4.5G 10GB（24 個月）",
    monthlyFee: 78,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 10,
    highSpeedGb: 10,
    fupNote: "首 10GB（42Mbps），其後以 128kbps 任用",
    voice: "不適用",
    roaming: "每月 1GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    hot: true,
    bestFor: "適合輕量上網、攜號轉台之用戶",
  },
  {
    id: "hkbn-5g-30",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 30GB（28 個月）",
    monthlyFee: 98,
    freeMonths: 2,
    contractMonths: 28,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後按計劃條款任用",
    voice: "不適用",
    roaming: "每月 4GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["15 個常用流動應用程式數據任用（須受條款約束）", "每月 10 分鐘中國內地及澳門通話"],
    portInPerk: PERK_HKBN_PORT,
    hot: true,
    bestFor: "適合日常 5G 用量，以及不時前往內地或澳門之用戶",
  },
  {
    id: "hkbn-45g-20",
    providerId: "hkbn",
    category: "mobile",
    name: "4.5G 20GB（24 個月）",
    monthlyFee: 118,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 20,
    highSpeedGb: 20,
    fupNote: "其後按計劃公平使用政策任用",
    voice: "不適用",
    install: "不適用",
    housing: "all",
    network: "4.5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合中等 4.5G 數據用量之用戶",
  },
  {
    id: "hkbn-5g-100",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 100GB（24 個月）",
    monthlyFee: 128,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: "其後以 1Mbps 任用",
    voice: "不適用",
    roaming: "每月 8GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合高本地數據用量，以及需要較多內地數據之用戶",
  },
  {
    id: "hkbn-5g-100-148",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 100GB 任用（24 個月）",
    monthlyFee: 148,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 100,
    highSpeedGb: 100,
    fupNote: "其後按計劃條款任用",
    voice: "不適用",
    roaming: "每月 3GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合高本地數據用量之用戶",
  },
  {
    id: "hkbn-5g-cga-70",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 70GB 中港澳共享",
    monthlyFee: 158,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 70,
    highSpeedGb: 70,
    roaming: "香港、內地、澳門共享 70GB",
    voice: "不適用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["香港、內地及澳門共享數據池"],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合一星期多次往返內地或澳門之用戶",
  },
  {
    id: "hkbn-5g-50-cga",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 50GB 中港共用（24 個月）",
    monthlyFee: 179,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 50,
    highSpeedGb: 50,
    fupNote: "其後以 1Mbps 任用",
    voice: "不適用",
    roaming: "50GB 中港共用數據；另加每月 4GB 澳門數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["送 HK$500 超市現金券"],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合經常往返內地，以及需要澳門數據之用戶",
  },
  {
    id: "hkbn-5g-30-cga",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 30GB 三地共用（24 個月）",
    monthlyFee: 188,
    freeMonths: 0,
    contractMonths: 24,
    dataGb: 30,
    highSpeedGb: 30,
    fupNote: "其後按計劃條款任用",
    voice: "不適用",
    roaming: "30GB 香港、內地及澳門三地共用；另加每月 1GB 中國內地數據",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: [],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合需要中港澳三地共用數據之用戶",
  },
  {
    id: "hkbn-5g-200",
    providerId: "hkbn",
    category: "mobile",
    name: "5G 200GB 網上限定",
    monthlyFee: 199,
    freeMonths: 1,
    contractMonths: 24,
    dataGb: 200,
    highSpeedGb: 200,
    voice: "不適用",
    install: "不適用",
    housing: "all",
    network: "5G",
    perks: ["200GB 本地高速數據"],
    portInPerk: PERK_HKBN_PORT,
    bestFor: "適合沒有家居寬頻、主要依靠手機熱點之用戶",
  },
  {
    id: "cmhk-biz-1000",
    providerId: "cmhk",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 198,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP 可選"],
    bestFor: "適合店舖或小型寫字樓",
  },
  {
    id: "hgc-biz-1000",
    providerId: "hgc",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 228,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["企業支援"],
    bestFor: "適合需要較穩定上傳之商戶",
  },
  {
    id: "hkbn-biz-1000",
    providerId: "hkbn",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 248,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP 可選"],
    bestFor: "適合中小型商戶",
  },
  {
    id: "netvigator-biz-1000",
    providerId: "netvigator",
    category: "business",
    name: "商業 1000M",
    monthlyFee: 268,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 1000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["企業支援熱線"],
    bestFor: "適合需要電訊盈科商用支援之客戶",
  },
  {
    id: "hgc-biz-2500",
    providerId: "hgc",
    category: "business",
    name: "商業 2500M",
    monthlyFee: 388,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP"],
    bestFor: "適合多部電腦同時使用之寫字樓",
  },
  {
    id: "hkbn-biz-2500",
    providerId: "hkbn",
    category: "business",
    name: "商業 2500M",
    monthlyFee: 398,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 2500,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP 可選"],
    bestFor: "適合中型辦公室",
  },
  {
    id: "hgc-biz-5000",
    providerId: "hgc",
    category: "business",
    name: "商業 5000M",
    monthlyFee: 588,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 5000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP", "企業支援"],
    bestFor: "適合多樓層辦公室",
  },
  {
    id: "hkbn-biz-5000",
    providerId: "hkbn",
    category: "business",
    name: "商業 5000M",
    monthlyFee: 598,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 5000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP"],
    bestFor: "適合頻密上載之商戶",
  },
  {
    id: "hgc-biz-10000",
    providerId: "hgc",
    category: "business",
    name: "商業 10000M",
    monthlyFee: 788,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP", "企業支援"],
    bestFor: "適合大型辦公室",
  },
  {
    id: "hkbn-biz-10000",
    providerId: "hkbn",
    category: "business",
    name: "商業 10000M",
    monthlyFee: 798,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP"],
    bestFor: "適合高流量企業",
  },
  {
    id: "netvigator-biz-10000",
    providerId: "netvigator",
    category: "business",
    name: "商業 10000M",
    monthlyFee: 798,
    freeMonths: 0,
    contractMonths: 24,
    speedMbps: 10000,
    install: "標準企業安裝",
    housing: ["private"],
    network: "光纖專線／商用",
    perks: ["固定 IP", "企業支援"],
    bestFor: "適合經常連海外總部之企業",
  },
];

export type PlansSearch = {
  cat: Category;
  housing?: Housing;
  maxFee?: number;
  speed?: SpeedMbps;
  minSpeed?: number;
  minData?: number;
  provider?: ProviderId;
  portIn?: boolean;
  generation?: Generation;
  gba?: boolean;
  q?: string;
  estate?: string;
  sort?: "fee" | "avg" | "speed" | "data";
  saved?: boolean;
};

export function averageFee(plan: Plan) {
  if (!plan.freeMonths) return plan.monthlyFee;
  return Math.round(((plan.monthlyFee * (plan.contractMonths - plan.freeMonths)) / plan.contractMonths) * 10) / 10;
}

export function matchesHousing(plan: Plan, housing?: Housing) {
  if (!housing) return true;
  if (plan.housing === "all") return true;
  return plan.housing.includes(housing);
}

export function planGeneration(plan: Plan): Generation | undefined {
  if (plan.category !== "mobile") return undefined;
  return plan.network.startsWith("5G") ? "5g" : "4g";
}

export function hasGba(plan: Plan) {
  const blob = `${plan.roaming ?? ""} ${plan.name} ${plan.perks.join(" ")} ${plan.limits ?? ""}`;
  return /中澳|中港|大灣區|三地|澳門|內地/.test(blob);
}

export function filterPlans(search: PlansSearch, savedIds: string[] = []) {
  let rows = PLANS.filter((plan) => {
    if (plan.category !== search.cat) return false;
    if (!matchesHousing(plan, search.housing)) return false;
    if (search.maxFee && plan.monthlyFee > search.maxFee) return false;
    if (search.speed && plan.speedMbps !== search.speed) return false;
    if (search.minSpeed && (plan.speedMbps ?? 0) < search.minSpeed) return false;
    if (search.minData) {
      const data = plan.dataGb ?? plan.highSpeedGb ?? (plan.fupNote ? 0 : 9999);
      if (data < search.minData) return false;
    }
    if (search.provider && plan.providerId !== search.provider) return false;
    if (search.portIn && !plan.portInPerk) return false;
    if (search.generation && planGeneration(plan) !== search.generation) return false;
    if (search.gba && !hasGba(plan)) return false;
    if (search.saved && !savedIds.includes(plan.id)) return false;
    if (search.q) {
      const provider = PROVIDER_MAP[plan.providerId];
      const extra = plan.providerId === "netvigator" ? "電訊盈科 PCCW" : "";
      const blob =
        `${plan.name} ${provider.name} ${provider.nameEn} ${plan.network} ${plan.perks.join(" ")} ${plan.prepaid ?? ""} ${plan.limits ?? ""} ${extra}`.toLowerCase();
      if (!blob.includes(search.q.trim().toLowerCase())) return false;
    }
    return true;
  });

  const sort = search.sort ?? "fee";
  rows = [...rows].sort((a, b) => {
    if (sort === "avg") return averageFee(a) - averageFee(b);
    if (sort === "speed") return (b.speedMbps ?? 0) - (a.speedMbps ?? 0);
    if (sort === "data") return (b.dataGb ?? b.highSpeedGb ?? 0) - (a.dataGb ?? a.highSpeedGb ?? 0);
    return a.monthlyFee - b.monthlyFee;
  });
  return rows;
}

export function getPlan(id: string) {
  return PLANS.find((p) => p.id === id);
}

export function formatFee(value: number) {
  return Number.isInteger(value) ? `HK$${value}` : `HK$${value.toFixed(1)}`;
}

export function minMonthlyFee(category: Category) {
  const fees = PLANS.filter((p) => p.category === category).map((p) => p.monthlyFee);
  return fees.length ? Math.min(...fees) : 0;
}

export function minVillageBroadbandFee() {
  const fees = PLANS.filter((p) => {
    if (p.category !== "broadband") return false;
    return p.housing === "all" || p.housing.includes("village");
  }).map((p) => p.monthlyFee);
  return fees.length ? Math.min(...fees) : 0;
}

export function formatMonthly(value: number) {
  return `${formatFee(value)}／月`;
}

export function formatSpeed(mbps?: number, network?: string) {
  if (!mbps) return network || "視計劃而定";
  return network ? `${mbps}M ${network}` : `${mbps}M`;
}

export function formatPlanSpeed(plan: Plan) {
  if (plan.category === "home5g") return "100M–1000M";
  return formatSpeed(plan.speedMbps);
}

export function formatInstall(plan: Plan) {
  return plan.category === "mobile" ? "不適用" : plan.install;
}

export function formatPrepaidShort(prepaid: string) {
  const match = prepaid.match(/須預繳 HK\$[0-9,]+/);
  return match ? match[0] : prepaid;
}

export function planPerks(plan: Plan) {
  const extra = plan.providerId === "hgc" && !plan.perks.includes("豁免搬遷費") ? ["豁免搬遷費"] : [];
  const list = [...plan.perks, ...extra];
  return list.filter((perk) => {
    if (plan.install.includes("豁免安裝") && perk.includes("豁免安裝")) return false;
    return true;
  });
}

export const CATEGORY_LABEL: Record<Category, string> = {
  broadband: "光纖寬頻",
  mobile: "手機月費",
  home5g: "5G 家居寬頻",
  business: "商業寬頻",
};

export const HOUSING_LABEL: Record<Housing, string> = {
  public: "公屋",
  hos: "居屋",
  private: "私人樓",
  village: "村屋",
};
