/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EstatesRouteImport } from './routes/estates'
import { Route as GuidesSlugRouteImport } from './routes/guides_.$slug'
import { Route as PlansPlanIdRouteImport } from './routes/plans_.$planId'
import { Route as EstatesSlugRouteImport } from './routes/estates_.$slug'
import { Route as OffersOfferIdRouteImport } from './routes/offers_.$offerId'
import { Route as TechNewsRouteImport } from './routes/tech-news'
import { Route as TechNewsSlugRouteImport } from './routes/tech-news_.$slug'
import { Route as TechNewsDeskRouteImport } from './routes/tech-news_.desk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesRoute = EstatesRouteImport.update({
  id: '/estates',
  path: '/estates',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides_/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdRoute = PlansPlanIdRouteImport.update({
  id: '/plans_/$planId',
  path: '/plans/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatesSlugRoute = EstatesSlugRouteImport.update({
  id: '/estates_/$slug',
  path: '/estates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersOfferIdRoute = OffersOfferIdRouteImport.update({
  id: '/offers_/$offerId',
  path: '/offers/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechNewsRoute = TechNewsRouteImport.update({
  id: '/tech-news',
  path: '/tech-news',
  getParentRoute: () => rootRouteImport,
} as any)
const TechNewsSlugRoute = TechNewsSlugRouteImport.update({
  id: '/tech-news_/$slug',
  path: '/tech-news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TechNewsDeskRoute = TechNewsDeskRouteImport.update({
  id: '/tech-news_/desk',
  path: '/tech-news/desk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/spend': typeof SpendRoute
  '/staff': typeof StaffRoute
  '/desk': typeof DeskRoute
  '/staff': typeof StaffRoute
  '/desk': typeof DeskRoute
  '/estates': typeof EstatesRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/estates/$slug': typeof EstatesSlugRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/tech-news': typeof TechNewsRoute
  '/tech-news/$slug': typeof TechNewsSlugRoute
  '/tech-news/desk': typeof TechNewsDeskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/spend': typeof SpendRoute
  '/staff': typeof StaffRoute
  '/desk': typeof DeskRoute
  '/staff': typeof StaffRoute
  '/desk': typeof DeskRoute
  '/estates': typeof EstatesRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/plans/$planId': typeof PlansPlanIdRoute
  '/estates/$slug': typeof EstatesSlugRoute
  '/offers/$offerId': typeof OffersOfferIdRoute
  '/tech-news': typeof TechNewsRoute
  '/tech-news/$slug': typeof TechNewsSlugRoute
  '/tech-news/desk': typeof TechNewsDeskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/spend': typeof SpendRoute
  '/staff': typeof StaffRoute
  '/desk': typeof DeskRoute
  '/staff': typeof StaffRoute
  '/desk': typeof DeskRoute
  '/estates': typeof EstatesRoute
  '/guides_/$slug': typeof GuidesSlugRoute
  '/plans_/$planId': typeof PlansPlanIdRoute
  '/estates_/$slug': typeof EstatesSlugRoute
  '/offers_/$offerId': typeof OffersOfferIdRoute
  '/tech-news': typeof TechNewsRoute
  '/tech-news_/$slug': typeof TechNewsSlugRoute
  '/tech-news_/desk': typeof TechNewsDeskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand'
    | '/compare'
    | '/guides'
    | '/plans'
    | '/privacy'
    | '/quote'
    | '/spend'
    | '/staff'
    | '/desk'
    | '/estates'
    | '/guides/$slug'
    | '/plans/$planId'
    | '/estates/$slug'
    | '/offers/$offerId'
    | '/tech-news'
    | '/tech-news/$slug'
    | '/tech-news/desk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand'
    | '/compare'
    | '/guides'
    | '/plans'
    | '/privacy'
    | '/quote'
    | '/spend'
    | '/staff'
    | '/desk'
    | '/estates'
    | '/guides/$slug'
    | '/plans/$planId'
    | '/estates/$slug'
    | '/offers/$offerId'
    | '/tech-news'
    | '/tech-news/$slug'
    | '/tech-news/desk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand'
    | '/compare'
    | '/guides'
    | '/plans'
    | '/privacy'
    | '/quote'
    | '/spend'
    | '/staff'
    | '/desk'
    | '/estates'
    | '/guides_/$slug'
    | '/plans_/$planId'
    | '/estates_/$slug'
    | '/offers_/$offerId'
    | '/tech-news'
    | '/tech-news_/$slug'
    | '/tech-news_/desk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandRoute: typeof BrandRoute
  CompareRoute: typeof CompareRoute
  GuidesRoute: typeof GuidesRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  SpendRoute: typeof SpendRoute
  EstatesRoute: typeof EstatesRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PlansPlanIdRoute: typeof PlansPlanIdRoute
  EstatesSlugRoute: typeof EstatesSlugRoute
  OffersOfferIdRoute: typeof OffersOfferIdRoute
  TechNewsRoute: typeof TechNewsRoute
  TechNewsSlugRoute: typeof TechNewsSlugRoute
  TechNewsDeskRoute: typeof TechNewsDeskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates': {
      id: '/estates'
      path: '/estates'
      fullPath: '/estates'
      preLoaderRoute: typeof EstatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides_/$slug': {
      id: '/guides_/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans_/$planId': {
      id: '/plans_/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estates_/$slug': {
      id: '/estates_/$slug'
      path: '/estates/$slug'
      fullPath: '/estates/$slug'
      preLoaderRoute: typeof EstatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers_/$offerId': {
      id: '/offers_/$offerId'
      path: '/offers/$offerId'
      fullPath: '/offers/$offerId'
      preLoaderRoute: typeof OffersOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-news': {
      id: '/tech-news'
      path: '/tech-news'
      fullPath: '/tech-news'
      preLoaderRoute: typeof TechNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-news_/$slug': {
      id: '/tech-news_/$slug'
      path: '/tech-news/$slug'
      fullPath: '/tech-news/$slug'
      preLoaderRoute: typeof TechNewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-news_/desk': {
      id: '/tech-news_/desk'
      path: '/tech-news/desk'
      fullPath: '/tech-news/desk'
      preLoaderRoute: typeof TechNewsDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandRoute: BrandRoute,
  CompareRoute: CompareRoute,
  GuidesRoute: GuidesRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  SpendRoute: SpendRoute,
  StaffRoute: StaffRoute,
  DeskRoute: DeskRoute,
  EstatesRoute: EstatesRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PlansPlanIdRoute: PlansPlanIdRoute,
  EstatesSlugRoute: EstatesSlugRoute,
  OffersOfferIdRoute: OffersOfferIdRoute,
  TechNewsRoute: TechNewsRoute,
  TechNewsSlugRoute: TechNewsSlugRoute,
  TechNewsDeskRoute: TechNewsDeskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
